### ISSUE TITLE
[BUG]: Checker is losing the Element role, Requirements, rule tab menu bar

### ISSUE THREAD

**Issue by eirckr** [IBMa/equal-access#1005]
### Project

a11y checker extension

### Browser

Chrome

### Operating system

MacOS

### Description

Tested with lates master build (tag 3.1.33)
The tab menu is lost after the user goes back to list view from _lean more_ item. 
The menu in not visible to the user, relaunching the checker will show the menu again. Unable to release 3.1.33 due to this issue. 

### Steps to reproduce

1. Install the master build
2. Conduct a scan on any site 
3. Select learn more from the results list
4. Select Back to list view

Results: User is not able to see the top menu. Please review attachment: 
<img width="1279" alt="Screen Shot 2022-07-06 at 9 56 54 PM" src="https://user-images.githubusercontent.com/62436670/177682636-ead2ca06-99a3-4658-a557-66355bcef00c.png">
<img width="1479" alt="Screen Shot 2022-07-06 at 9 57 22 PM" src="https://user-images.githubusercontent.com/62436670/177682645-9e99aa79-6f12-4439-8317-7ed984818a63.png">

**Comment by drjoho** [comment]
Ok, I have located the two commits: one on June 13th that works as it should and the one on June 20th by Tom which has introduced an error. I will investigate further to determine the exact cause.

**Comment by drjoho** [comment]
I have determine the cause: <div ref={this.itemSelectedRef(item)}> was added by Tom and it causes the problem.

**Comment by eirckr** [comment]
https://github.com/IBMa/equal-access/pull/1006
