### ISSUE TITLE
[A11y_Bug]: Why my id is not approved on IBM?

### ISSUE THREAD

**Issue by checkout1253** [IBMa/equal-access#1015]
### Project

able site

### Browser

Chrome

### Operating System

Windows

### Description

I apply for IBM and they did not approve me as a member. I can have two websites which I will be sharing with everyone for the support.

### Steps to reproduce

I apply for IBM and they did not approve me as a member. I can have two websites which I will be sharing with everyone for support.

**Comment by checkout1253** [comment]
My websites are https://thealightmotion.com/ & http://eskatesboardsriders.com/

**Comment by dime421** [comment]
Hello

I have activated my IBM id but I'm not recognized in the License Key Center

I don't know why.
Check my Ibm System id is [IBM](https://bit.ly/3oDzpe4)

Regards Sébastien
