### ISSUE TITLE
[New Rule] Elements with presentational children only

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#1027]
Give the following test case:
![Screen Shot 2022-08-02 at 11.51.23 AM.png](https://images.zenhubusercontent.com/61d72f5790898928dfc7024b/3278a8db-ee74-443a-a5a7-3268622273ac)

The li with role='option' is an element with "children presentational:true" (presentational element in the following text). According to the [aria spec](https://w3c.github.io/aria/#tree_exclusion), all the descendants, including the elements with the role 'tablist' and 'tab', of the li element should not be included in the accessibility tree (or should be invisible to an AT).

In the current engine context, the aria-paths for all the descendants are the same with the presentational parent or ascendant. In the above example, all have "/document[1]/listbox[1]/option[1]" (see the following attached screenshot).  This is fine.  However, when a descendant element is subsequently passed to various rules for checking, if the rules happen to use the aria-paths in their logic, various false positives can be produced because the aria-paths are not their own (a descendant of a presentation child shouldn't require an aria-path).  In the following screenshot, two false positives are displayed.

![Screen Shot 2022-08-02 at 12.11.20 PM.png](https://images.zenhubusercontent.com/61d72f5790898928dfc7024b/67ceefbb-1082-4c83-881c-f93f0493d4b4)

**Comment by shunguoy** [comment]
The elements with the following roles have "Children Presentational: True":

[button](https://www.w3.org/TR/wai-aria-1.2/#button)
[checkbox](https://www.w3.org/TR/wai-aria-1.2/#checkbox)
[img](https://www.w3.org/TR/wai-aria-1.2/#img)
[menuitemcheckbox](https://www.w3.org/TR/wai-aria-1.2/#menuitemcheckbox)
[menuitemradio](https://www.w3.org/TR/wai-aria-1.2/#menuitemradio)
[meter](https://www.w3.org/TR/wai-aria-1.2/#meter)
[option](https://www.w3.org/TR/wai-aria-1.2/#option)
[progressbar](https://www.w3.org/TR/wai-aria-1.2/#progressbar)
[radio](https://www.w3.org/TR/wai-aria-1.2/#radio)
[scrollbar](https://www.w3.org/TR/wai-aria-1.2/#scrollbar)
[separator](https://www.w3.org/TR/wai-aria-1.2/#separator)
[slider](https://www.w3.org/TR/wai-aria-1.2/#slider)
[switch](https://www.w3.org/TR/wai-aria-1.2/#switch)
[tab](https://www.w3.org/TR/wai-aria-1.2/#tab)

**Comment by shunguoy** [comment]
box note for the rule: https://ibm.ent.box.com/notes/1003150355488

**Comment by shunguoy** [comment]
discussion result in the box note: https://ibm.ent.box.com/notes/1003150355488
branch: dev-1027

**Comment by shunguoy** [comment]
rule logic and test cases are created.  Further tests are needed.

**Comment by marcjohlic** [comment]
#1067 is related - Shunguo will finish #1067 and then assign to Tom for review.

**Comment by shunguoy** [comment]
test case: test/v2/checker/accessibility/rules/aria_descendant_valid_ruleunit/aria-descendant-tablist.html

**Comment by eirckr** [comment]
Validated wit test case:

test case: test/v2/checker/accessibility/rules/aria_descendant_valid_ruleunit/aria-descendant-tablist.html

<img width="1374" alt="Screen Shot 2022-10-10 at 9 58 33 PM" src="https://user-images.githubusercontent.com/62436670/194987462-93953cb9-0db7-4bd9-85af-a2b36bbe04e9.png">
