### ISSUE TITLE
Validation of Aria attributes for the elements without an explicit role failed

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#1034]
when an element doesn't have an implicit role, the engine report might contain false positives or negatives.  For example,  the following elements should cause a violation, but we don't report them: 
              <datalist id="f" aria-activedescendant="true" aria-atomic="false" />
              <wbr aria-details="detail">my label</label>
              <title aria-details="detail">xxx</track>
               <template aria-details="detail">xxx</template>
               <var aria-checked="detail">xxx</var>
               <script aria-details="detail" aria-checked="detail">xxx</script>
               <picture aria-details="detail" aria-checked="detail">xxx</picture>

Per [team discussion](https://ibm.ent.box.com/notes/994215482156), the rule "aria_semantics_attribute" should be modified to make the code fix, an additional issue is to open for updating the help content. 

- [x]  code change
- [x]  test cases
- [x]  message change
- [x]   help content update #1035

**Comment by shunguoy** [comment]
investigate the different cases: 
  1.  neither implicit nor explicit role, Not global attributes either
  2.  neither implicit nor explicit role, but allow certain specific attributes
  3.  neither implicit nor explicit role, but allow global attributes 
  4.  neither implicit nor explicit role doesn't mean "none" role, the element can still be mapped over to AT by the browser user agent (such as label, link, legend, caption).

**Comment by shunguoy** [comment]
updated aria definition, and messages, and added more test cases.

**Comment by shunguoy** [comment]
working to modify the existing test cases that failed after the aria updates

**Comment by shunguoy** [comment]
encountered an error in opening the help link:  

<img width="740" alt="Screen Shot 2022-08-15 at 10 28 54 AM" src="https://user-images.githubusercontent.com/18539498/184665563-88c4df2d-47c8-49df-8c1d-b9154f17f6eb.png">

**Comment by shunguoy** [comment]
after the current aria changes, 33 existing test cases failed, which need to be reviewed and updated one by one.

**Comment by shunguoy** [comment]
continuing the test cases, help content test, and the baseline updates.

**Comment by eirckr** [comment]
@shunguoy please provide a test file

**Comment by eirckr** [comment]
Validated
