### ISSUE TITLE
[Question]: Can karma-accessibility-checker used in typescript scenario

### ISSUE THREAD

**Issue by infogdigdeep** [IBMa/equal-access#1052]
### Project

karma accessibility checker

### Description

Hi,

Our testing project is using karma, typescript, and mocha environment,  I have problem getting the aChecker instance in the test spec by using the steps mentioned in the quick start guide.

I just want to confirm if it is supported in typescript.  If yes, are there any examples you can share.

Thanks

**Comment by aliunwala** [comment]
From Triage:
Hi we have been wanting to try and make a custom boiler plate for you to test out but we have not had the free cycles yet to do it. For now can you look at the boilerplates here:
https://github.com/IBMa/equal-access/tree/master/accessibility-checker/boilerplates
Do any of them get you closer to doing what you wanted?

**Comment by tombrunet** [comment]
See https://github.com/IBMa/equal-access/tree/master/karma-accessibility-checker/boilerplates/typescript
It doesn't use the types from the checker, but it shows how you can use the checker within a typescript environment.
