### ISSUE TITLE
Rule exceptions in FF:  RPT_Style_HinderFocus1 and element_tabbable_visible

### ISSUE THREAD

**Issue by marcjohlic** [IBMa/equal-access#1054]
In FF, scanning ibm.com these two rules keep erroring out.  Josiah will pass this along to Shunguo

![image.png](https://images.zenhubusercontent.com/58d3fa1c51aa2c3057794e7f/c58578f2-19f7-472d-b859-f8ef1167585d)

From Josiah:

@thbrunet @shunguoy @johlic FIREFOX -  There are some pages (ibm.com) where there we are getting rule exceptions with: RPT_Style_HinderFocus1 and element_tabbable_visible which we use to have issues with in chrome

![image.png](https://images.zenhubusercontent.com/58d3fa1c51aa2c3057794e7f/f84474f8-0aa2-4485-ab47-81ecd27df4c1)

The rule exception does not happen on chrome:
![image.png](https://images.zenhubusercontent.com/58d3fa1c51aa2c3057794e7f/414e9e48-d577-476e-8a59-7133865be5d9)

**Comment by shunguoy** [comment]
the issue was because FF rejects loading the referenced stylesheet files due to cross-origin security violation or a referenced stylesheet was unavailable. The error is fixed in another issue. so close this issue.
