### ISSUE TITLE
Checker extension FF:  Unable to toggle KCM off on some pages

### ISSUE THREAD

**Issue by marcjohlic** [IBMa/equal-access#1055]
Unable to toggle KCM 'off' once enabled in FF. Josiah knows what the problem is (an empty string is being passed in via the getElementbyID()) - now just needs to figure out the 'why'.

![image.png](https://images.zenhubusercontent.com/58d3fa1c51aa2c3057794e7f/d4a23caf-2f76-4c61-b755-6bae22eb75c3)

**Comment by drjoho** [comment]
This work will continue with a new issue for next sprint.
