### ISSUE TITLE
[KCM Hardening] what to do about fixed position items on page

### ISSUE THREAD

**Issue by marcjohlic** [IBMa/equal-access#1056]
Here is an example on our able page:

Note that the heading is fixed and the number 18 and 23 is fixed as you will see when I moved down the page

![image.png](https://images.zenhubusercontent.com/58d3fa1c51aa2c3057794e7f/45ef4784-cfb3-430f-ba60-73ad821d5c51)

Here I have moved down the page a bit - the heading tabs stops visualization have moved up but heading did not move and the same with 18 and 23.

![image.png](https://images.zenhubusercontent.com/58d3fa1c51aa2c3057794e7f/5f5a0049-abd2-4fe4-a258-f293346bc614)

This is tricky.

**Comment by marcjohlic** [comment]
Possibly add a user-selectable option for re-draws when the page is reflowed or scrolled. It would have a note to the user that this option could impact performance.

It appears another tool redraws the tab stop indicators when the page is scrolled. This allows them to "track" fixed position items, but it does come at a performance cost.

Maybe giving the user the option for this (off by default) would be a decent option. Something to discuss with Design and Dev.

**Comment by aliunwala** [comment]
Triage:
We will put this into the back log this is a limitation of when the scan was taken. And scrolling moves elements around so another scan would be needed to redraw things. We could trigger another redraw but on many webpages this "continuous" redraw method would be too much processing for uses browsers.

**Comment by drjoho** [comment]
We are working on the issues for the Checker and thus the KCM re-architecture. Tom and I will figure out where this should be addressed.

**Comment by MHoov** [comment]
@tombrunet do you recall why we put this in Checker implementation waiting on Designs?

**Comment by tombrunet** [comment]
@MHoov I think we should be able to automate this, but I think there was a proposal to put up a warning that the page changed and needed to be refreshed.

**Comment by MHoov** [comment]
@tombrunet I don't believe we ever created an issue for this. 

We did update the user guide to state "**Important note**: the keyboard checker mode does not track page changes. Turn the mode off and on again to update the visualization."

Question, do want this warning to pop-up for every page change (i.e., are there other types of page changes where this warning wouldn't apply?)

**Comment by MHoov** [comment]
Completed R6.x
