### ISSUE TITLE
[KCM] Unable to select section on a site when feature is enable

### ISSUE THREAD

**Issue by marcjohlic** [IBMa/equal-access#1061]
The KCM feature can prevent the user from navigation(selecting) elements in a page. It create a soft filter on some section where the tabstop overlays. 

Repro steps: 
Navigate to https://able-test.mybluemix.net/able/toolkit
Run the tabstop feature 
try to close the Equal Access Toolkit (dropdown menu)

Or, try to select the overview option. 

Please review attachment: 

https://ibm.box.com/s/i5b1v6jwy5pm7s0vtmdydtpuupyipug8

Interesting that using keyboard all works fine - it's only the mouse pointer that is getting "blocked".

**Comment by aliunwala** [comment]
Triage:

This is annoying but there are work arounds for it. By turning on an off the drawings

**Comment by drjoho** [comment]
When keyboard off make placeholder 
<svg id="svgCircle" class="dynamic" width="1px" height="1px"></svg>

**Comment by drjoho** [comment]
Fixed
<img width="1826" alt="image" src="https://user-images.githubusercontent.com/64442976/193134814-ccdeaeb9-c69e-448d-89fb-59b784c43a5a.png">

**Comment by drjoho** [comment]
To test use ibm.com/able
Use current version on store. Scan. Open tab visualization. You will not be able to open the equal access toolkit accordion.
Use this PR and you will be able to open/close equal access toolkit accordion while tab visualization displayed.

**Comment by eirckr** [comment]
@drjoho No pr attached to this ticket.

**Comment by drjoho** [comment]
PR #1093

**Comment by eirckr** [comment]
validated 
<img width="1003" alt="Screen Shot 2022-10-04 at 2 27 09 PM" src="https://user-images.githubusercontent.com/62436670/193908472-7921ea4f-1196-4fcb-b85c-064350c62960.png">
