### ISSUE TITLE
[KCM] Info pop-up is not showing the whole content unless you make the window larger.  Change to a modal

### ISSUE THREAD

**Issue by marcjohlic** [IBMa/equal-access#1062]
**KCM(Keyboard checker mode)**
**Test branch6/21** : joho-tabStops-SoftLaunch5

User is not able to see the full information pop-up unless they expand the window larger. 

Change this from a "Notification" to a "Modal". 

Please review attachment

![image.png](https://images.zenhubusercontent.com/58d3fa1c51aa2c3057794e7f/c9c2caeb-ee36-43c4-b010-27807746e6ed)

![image.png](https://images.zenhubusercontent.com/58d3fa1c51aa2c3057794e7f/0618b216-40d7-4792-b068-19cf4b94afd1)

**Comment by marcjohlic** [comment]
Original issue was internal:  [4625](https://zenhub.ibm.com/workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/issues/ibma/e2e/4625)

**Comment by drjoho** [comment]
Change Toast Notification to a Modal:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/64442976/192682066-5855b3a5-52ef-48dd-a143-14a80ab7c95c.png">
