### ISSUE TITLE
[BUG]: Preview rules set is give us issue with the strict child/parent 

### ISSUE THREAD

**Issue by eirckr** [IBMa/equal-access#1063]
### Project

a11y checker

### Browser

Chrome

### Operating system

MacOS

### Description

Our automation check with a11y checker is giving us multiple errors. We need to check if these errors are false positives and need to fix the rule. This might be related to https://github.com/IBMa/equal-access/issues/600. 

The automation checker for able site is using a different rule set to bypass this issue. 

<img width="916" alt="Screen Shot 2022-08-29 at 10 24 51 AM" src="https://user-images.githubusercontent.com/62436670/187244105-5c6b88e6-3230-438f-8c14-6f90202e6e6a.png">

We have an internal branch to test this issue under the E2E board. 

### Steps to reproduce

1. Open the able site project 
2. Change the rule set to preview under achecker.js
3. Run the build locally 
4. Once the build is running locally run the accessibility test locally. 
5. Review the failure logs.

**Comment by shunguoy** [comment]
@eirckr  still not sure of the purpose.  Do you think the "strict child/parent" related issues are false positives?  can you post some examples?

**Comment by eirckr** [comment]
@shunguoy the logs can be found in https://travis.ibm.com/IBMa/ibm.com-able-v2/jobs/74632061

**Comment by shunguoy** [comment]
@eirckr  all the errors are the same: The element with role "list" does not own any child element with any of the following role(s): "listitem".  The element with a "list" role is expecting a child element with a "listitem" to form a parent-child relationship.  Based on the rule, this is correct reporting, rather than a false positive.

**Comment by aliunwala** [comment]
Fixed this with @shunguoy and @philljenkins 
![image](https://user-images.githubusercontent.com/4451128/187299702-0a7811f0-a6b0-49a7-8411-c038d4b28d4d.png)

![image](https://user-images.githubusercontent.com/4451128/187299752-7d2e8fa1-38d4-4167-8399-31e3c7fac52e.png)

This fixes the accessibility issue with the UL in the "hidden" middle column

**Comment by aliunwala** [comment]
PR here:
https://github.ibm.com/IBMa/ibm.com-able-v2/pull/809

**Comment by eirckr** [comment]
Not related to the checker
