### ISSUE TITLE
[KCM] Firefox "Could not select element" error on some websites - crashes KCM

### ISSUE THREAD

**Issue by marcjohlic** [IBMa/equal-access#1065]
This error occurs when user tries to turn off the KCM visualization. After which the KCM is stuck.
Note: this error does not occur on all websites. For example it does not occur on our demo page, UT website, etc. It does occur on ibm.com, ibm.com/able. 

![image.png](https://zenhub.ibm.com/images/5873eb2bfdfd5b9223bc3fe2/bb942dd4-90cf-404d-90e5-4d4c7469ffc9)

**Comment by aliunwala** [comment]
Triage:
Same as https://github.com/IBMa/equal-access/issues/1066

Should get closed at the same time.

**Comment by drjoho** [comment]
DONE. Dup of 1066.
