### ISSUE TITLE
Checker extension FF:  User unable to toggle KCM off on some pages Part 2

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1066]
Unable to toggle KCM 'off' once enabled in FF. Josiah knows what the problem is (an empty string is being passed in via the getElementbyID()) - now just needs to figure out the 'why'.

![image](https://user-images.githubusercontent.com/64442976/187768138-6dec3e6e-1d71-47b3-9053-8d2e1cd5bdbf.png)

**Comment by drjoho** [comment]
Error that I am receiving:
<img width="1551" alt="image" src="https://user-images.githubusercontent.com/64442976/187768990-98ea66cf-7c71-43f5-8450-00df0c822073.png">

**Comment by drjoho** [comment]
Still working on it...

**Comment by drjoho** [comment]
Progress - the handling of iFrames is different for FF so will try to address the differences so it works for both FF and Chrome.

**Comment by drjoho** [comment]
So here is the code that works differently in FF:

let frames = document.getElementsByTagName("iframe");
    
    for (let i = 0; i < frames.length; i++) {
        if (frames[i] != null) {
            frames[i].contentWindow?.addEventListener('keyup', function(event:any) {
                console.log("iframe key catcher");
                let iframePath = getXPathForElement(frames[i]); // since iframes in main doc
                handleTabHighlight(event,frames[i].contentWindow?.document,"iframe",iframePath);
            })
        }
    }

**Comment by drjoho** [comment]
Ok there are issues with the above code but there are other iframe issues that I am investigating with clicking the circles are triangles.

**Comment by drjoho** [comment]
Made sure all logs not showing in console. Working to get to build with no errors.

**Comment by eirckr** [comment]
good and merged
