### ISSUE TITLE
Update existing rules, test cases and baselines as the result of the new rule "aria_descendant_valid"

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#1067]
The fix aims to reduce false positives and overlaps among different rules. The following rules need to be updated as the result of the new rule "aria_descendant_valid":

- [ ]  aria_child_valid: 
- [ ]  IBMA_Focus_MultiTab
- [ ]  IBMA_Focus_Tabbable
- [ ]  Rpt_Aria_RequiredParent_Native_Host_Sematics

- [ ]  test case updates.   test cases need to be re-tested because of the rule update. Potentially, new test cases need to be created for the rules. 

- [ ]  baseline updates  The selenium and karma baseline needs to be updated for the changes.

**Comment by shunguoy** [comment]
The rules are updated, and working on test cases.

**Comment by shunguoy** [comment]
adding more test cases for corner cases.

**Comment by eirckr** [comment]
The checks have passed and changes were been review. Baselines are passing in the CI, closing ticket
