### ISSUE TITLE
Keyboard Checker Mode - Turn off RPT_Style_HinderFocus1 rule in Keyboard Visualization

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1068]
Analysis of current KCM rules
(https://app.zenhub.com/files/247104254/e5b21e75-b5a6-4da3-9d2a-f1f73fcc38a1/download)

**Comment by drjoho** [comment]
Note the RPT_Style_HinderFocus1 is only turned off in KCM - Still in issues list.

**Comment by drjoho** [comment]
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/64442976/188929109-5d318444-886b-49d3-8471-95d28e976e46.png">

**Comment by eirckr** [comment]
Good to go
