### ISSUE TITLE
[Feature]: Support Cypress 10

### ISSUE THREAD

**Issue by elizabethsjudd** [IBMa/equal-access#1076]
### Project

cypress accessibility checker

### Description

Currently the latest version of this tool is only supported up to Cypress 9. It would be nice it we could use the latest version of Cypress which is 10.8.0

**Comment by aliunwala** [comment]
Triage meeting:
We will add this to our backlog and prioritize it.

**Comment by dwwhalen** [comment]
Hi, just curious if there is an approximate ETA on this.   We would really like to use it but we're at Cypress 10, and considering an upgrade to Cypress 12.  Thanks.

**Comment by elizabethsjudd** [comment]
Wanting to also check back in on this. There are some higher vulnerabilities in these old versions of Cypress that are security team is asking us to resolve which we can't without losing our accessibility tests.

**Comment by cknabe** [comment]
My team is also blocked on updating to Cypress 12 by cypress-accessibility-checker.

**Comment by tombrunet** [comment]
Just finishing up some cleanup of the browser extensions. Circling back to the automated tools next. Sorry for the delay.

**Comment by cknabe** [comment]
@tombrunet how is this going for you?

**Comment by tombrunet** [comment]
Looking at this now.

**Comment by tombrunet** [comment]
@cknabe @elizabethsjudd PR: #1451 . I had to fight a little with the Cypress Promise vs Node Promise vs command structure, but it's running fine locally for me now. I'm getting some test error on loading our test web server, but unrelated to the actual Cypress code. If you have a chance to try this, this would replace your cypress-accessibility-checker folder in node_modules:
[package.zip](https://github.com/IBMa/equal-access/files/11491272/package.zip)
(Running on Node 18, Cypress 12)

**Comment by tombrunet** [comment]
See [4.0.0-rc.0](https://www.npmjs.com/package/accessibility-checker/v/4.0.0-rc.0) for Cypress 12 support. If you encounter issues with this version, please open new issues. Thank you.

**Comment by cknabe** [comment]
Thanks a lot!

**Comment by tombrunet** [comment]
The 3.x branch now works with Cypress 12. See 3.1.59
