### ISSUE TITLE
The extension crashed when an element with an id = 'ace' in the page,

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#1077]
this is related to the issue: https://github.com/IBMa/equal-access/issues/331
 this issue doesn't occur in the command line or the automated test. it seems extension-specific.

![Screen Shot 2022-09-15 at 10.24.35 AM.png](https://images.zenhubusercontent.com/61d72f5790898928dfc7024b/a1918e5e-2b31-4de9-a183-1ec26adcd8ba)

**Comment by eirckr** [comment]
Can you please provide the version and the browser this is happing in?

**Comment by shunguoy** [comment]
The extension version and 
<img width="405" alt="Screen Shot 2022-09-15 at 10 53 16 AM" src="https://user-images.githubusercontent.com/18539498/190451973-ec293068-cbd2-4ca8-a7e5-80df28ec1e68.png">

test case:

```
<html lang="en">
<body>
<div aria-grabbed="true" style="border: 2px solid" id="ace">
       element with aria-grabbed=true
</div>
<div aria-dropeffect="copy" style="border: 2px solid" >
        element with aria-dropeffect=copy
</div>
</body>
</html>
```

**Comment by drjoho** [comment]
For the extension I will change the following lines:
https://files.slack.com/files-pri/T27SFGS2W-F042M2W0690/image.png

**Comment by drjoho** [comment]
Not clear will finish this may take a few days
.

**Comment by drjoho** [comment]
Done with needed fix. Will clean up logging and then will PR.

**Comment by eirckr** [comment]
This is not passing test with: https://codesandbox.io/s/issue-331-id-gdb5ud back to dev @shunguoy

**Comment by shunguoy** [comment]
@eirckr  should back to @drjoho

**Comment by eirckr** [comment]
Validated
