### ISSUE TITLE
[BUG] Review issues from the India QA team

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1083]
Video that demonstrates the issues:
https://ibm.webex.com/ibm/ldr.php?RCID=204c29615c7140a7eb58e1d64e76a539
Password: 27qTaXJc

**Comment by drjoho** [comment]
Met today and reviewed most of the issues as to their relevancy. First we need to prioritize then a dev will have to dig a bit deeper to determine where the problem is: coding, Carbon, FF only, and if fix easy or hard.

**Comment by MHoov** [comment]
@marcjohlic will copy this issue to the internal board.

**Comment by drjoho** [comment]
Review done. New issues will result.
