### ISSUE TITLE
[BUG] Revisit issue 1077 (Deals with a web page to be scanned that has an ace javascript object)  in that it is not working in FF .

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1097]
So, FF does not scan from PR #1087 on

![image.png](https://images.zenhubusercontent.com/61081394ffd52d20c363a4cd/99cebab6-1efa-4e58-a877-701464af2533)

**Comment by drjoho** [comment]
Still working on it.

**Comment by drjoho** [comment]
PR #1108

**Comment by drjoho** [comment]
The extension crashed when an element with an id = 'ace' in the page. We now rename the engine to aceIBMa to fix.

**Comment by eirckr** [comment]
Validated on chrome and FF
