### ISSUE TITLE
Add excel spreadsheet reports to Checker Packages

### ISSUE THREAD

**Issue by MHoov** [IBMa/equal-access#1102]
Automated tools currently support a .csv format, but this format does not contain all of the content that is provided by the checker extension. Port the xls format from the checker extension as a new report format in the tools

**Comment by aliunwala** [comment]
This issue has several parts that need to come together to make this happen:
1) accessibility-checker/src-ts/lib/ACReportManager.ts needs to have a new config for xlsx
2) accessibility-checker/src-ts/lib/ACReportManager.ts needs to splice the data in a way that is acceptable for the xlsx script to parse
3) accessibility-checker-extension/src/ts/xlsxReport/multiScanReport/xlsx/multiScanReport.tsx needs to be cloned and moved over to the accessibility-checker 
4) accessibility-checker-extension/src/ts/xlsxReport/multiScanReport/xlsx/multiScanReport.tsx needs to be adapted to write locally (and not a download from chrome)


I have done step 1 and in the process of working on step 2. I estimate Step 2 will the majority of the work.

**Comment by MHoov** [comment]
@aliunwala please update this record.  (fyi @tombrunet )

**Comment by aliunwala** [comment]
Update:
This ticket is still in progress. I have moved most of the code that was creating the spreadsheets from the extension area and replicated it in the accessiblity-checker area. I am now going through the process of hooking it up to data. As well as getting a few kinks ironed out as a result of moving the code over.

**Comment by aliunwala** [comment]
Update. Making progress, now I am able to run a few of the functions that are part of the excel sheets. I am finding the variables from the reports sometimes dont match so I am working on getting the pieces and extra calculations match up

**Comment by aliunwala** [comment]
Update. Got single run excel sheet working. (There is still some clean up to do.) But I was automatically able to get an excel sheet to get created per page in the test suite.

The next step is to make this into a multiscan so all the scans get dumped into one excel sheet.

**Comment by aliunwala** [comment]
Sample:
[test-sync.xlsx](https://github.com/IBMa/equal-access/files/10230092/test-sync.xlsx)

**Comment by MHoov** [comment]
@aliunwala will getting the multiscans into one sheet complete this activity or is there additional work? Thanks

**Comment by aliunwala** [comment]
Got multiscans working and opening up a PR. I also did a short scan on two pages that are the same with the extension/CI tool and fixed any small discrepancies I saw.

**Comment by eirckr** [comment]
Validated
