### ISSUE TITLE
[BUG]: opacity based interactions raise contrast warning

### ISSUE THREAD

**Issue by stuntsman** [IBMa/equal-access#1117]
### Project

a11y checker extension

### Browser

Chrome

### Operating system

Windows

### Description

We have images with links in a page. 

There's a tooltip-like concept for the images: 

- for desktop users, hovering the images reveal a visible label text in the center of the image (also linked)
- for keyboard users, focusing (tabbing to) the label link also reveals the visible label.

However the accessibility checker reports a warning for low contrast and detects #ffffff as foreground and background, if we use opacity for displaying/hiding the label div (visibility property would not raise a warning, however it has not transition which we'd need).

As it's used in a series of images, it results in many warning occurences, thus the status percent of the page is lower, which is unfortunate as we consider this as an accessible solution otherwise.

### Steps to reproduce

```
<html lang="en">
<head>

<title>test</title>

<style>
.card { 
  width: 200px; 
  height: 200px; 
}

.card img { 
  position: relative;
}

.card .card-body {
  position: relative;
  margin-top: -100px;
  text-align: center;

  background-color: black; /* this is ignored by the checker due to opacity=0, but is OK with visibility: hidden */

  transition: 0.5s all;
  opacity: 0;
  /* visibility: hidden; */ /* visibility property could be used, however it has no transition support */

}

.card:hover .card-body, 
.card:focus-within .card-body {
  opacity: 1;
  /* visibility: visible; */ /* visibility property could be used, however it has no transition support */
}

.label {
  color: white !important;
  background-color: black !important; /* even the local background color doesn't affect the checker result */
  display: block;
}

</style>

</head>

<body>

<main>

<div class="card">

  <a href="#" aria-label="label text"><img alt="" src="https://picsum.photos/200"></a>
  <div class="card-body">
    <h2><a href="#" class="label">text</a></h2>
  </div>

</div>

</main>

</body>
</html>
```

**Comment by tombrunet** [comment]
Note that you can combine the visibility and opacity. If you use both, it will still do the transition, but the text will be removed completely when not focused. This rule is set as potential violation / needs review as opposed to violation because there are scenarios where you might still want that text there, but usually you wouldn't. Note that if you don't make the content visibility:hidden, and you select that area, that text is included in a copy paste even though you can't see it.
