### ISSUE TITLE
Rename and word spacing check for the rule WCAG20_Text_LetterSpacing

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#1135]
see details at https://ibm.ent.box.com/notes/1054236933860
1. rename the rule to text_whitespace_valid
2. add "Potential_word": "Verify space characters are not being used to create space between the words"
3.  New test cases

**Comment by eirckr** [comment]
Not ready for QA, waiting for https://github.com/ibma/equal-access/issues/1141

**Comment by eirckr** [comment]
Validated: 
<img width="1522" alt="Screen Shot 2022-12-07 at 12 23 21 AM" src="https://user-images.githubusercontent.com/62436670/206104359-d5a419e4-c2d1-48f7-ab8f-ff9f4f76df2c.png">
