### ISSUE TITLE
[BUG]: Keyboard checker mode popup is not showing correctly 

### ISSUE THREAD

**Issue by eirckr** [IBMa/equal-access#1145]
### Project

a11y checker extension

### Browser

Chrome

### Operating system

MacOS

### Description

The KCM popup text is overlapping the background text 

### Steps to reproduce

<img width="842" alt="Screen Shot 2022-11-08 at 4 34 18 PM" src="https://user-images.githubusercontent.com/62436670/200691301-6ba31e1d-23b9-4b39-9d55-d305b0c1556c.png">

**Comment by drjoho** [comment]
Fixed in #945

**Comment by eirckr** [comment]
validated
