### ISSUE TITLE
Rule firing sometimes results in triangle

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1163]
Here is initial showing of keyboard mode
![image.png](https://images.zenhubusercontent.com/61081394ffd52d20c363a4cd/792d01d9-648e-4906-bade-ad338efd409b)
Then I fixed the "Bad button" (tab stop 6) and refreshed the page and got:
![image.png](https://images.zenhubusercontent.com/61081394ffd52d20c363a4cd/f36c65f0-4dd6-429c-84df-0193192a8ac6)

So need to figure out what caused the new triangles to show up.

**Comment by MHoov** [comment]
@drjoho can you remind me when we plan to address this high priority bug? Thanks

**Comment by shunguoy** [comment]
this issue was fixed in #1389.

**Comment by ErickRenteria** [comment]
validated
