### ISSUE TITLE
Add new checker keyboard mode icon

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1173]
![image.png](https://images.zenhubusercontent.com/61081394ffd52d20c363a4cd/a6ae9714-8be3-4cce-9cad-ef59ca16814f)

Also, update tooltip text
<img width="395" alt="image" src="https://user-images.githubusercontent.com/64442976/204891351-158a1ebb-384c-4c45-8aff-563453b2a084.png">

**Comment by drjoho** [comment]
Done - ready for QA

**Comment by eirckr** [comment]
Validated
