### ISSUE TITLE
Change triangle to  normal tab stop circle with number and includes salmon colored notification circle

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1176]
![image.png](https://images.zenhubusercontent.com/61081394ffd52d20c363a4cd/0bb70e45-5345-4b44-bd20-8a88e24cd9b6)

**Comment by drjoho** [comment]
Have put in initial code for Notification dot but not active yet. 
Next I will redo the triangle code to be circles - this is tricky because the boundary conditions relate to the geometry.

**Comment by drjoho** [comment]
All issues are now circles. Today I will work on the Notification Dot for the circles with keyboard issues.

**Comment by drjoho** [comment]
Everything is now circles.
Now I need to differentiate the regular circles and error circles via css and classes.

**Comment by drjoho** [comment]
Before could differentiate with elements (circle vs polygon) so now am working on differentiating between circles using classes. So a bit more complicated but moving forward.

**Comment by drjoho** [comment]
Getting closer

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/64442976/206575420-789da277-dba3-4be3-aaf9-53086932a92c.png">

**Comment by MHoov** [comment]
:blush:

**Comment by drjoho** [comment]
Alex and I met to review what I had. She had some new designs: some I did while we were talking and some others
Increase red circles from 32 to 36px and increase text size from 24 to 28 or 26 pts
Add a 1px border around the notification dot the same grey as the background of the circle
Make the numbers bold when you tab over
Make the text of the numbers smaller when you enter three digits so they can fit inside the circle

**Comment by drjoho** [comment]
Here is the status now:
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/64442976/206750587-2d397bd5-9371-498e-adff-6043b3782654.png">

**Comment by drjoho** [comment]
Added Dec 9th
- Increase red circles from 32 to 36px and increase text size from 24 to 28 or 26 pts
- Add a 1px border around the notification dot the same grey as the background of the circle
- Make the numbers bold when you tab over
- Make the text of the numbers smaller when you enter three digits so they can fit inside the circle

**Comment by drjoho** [comment]
This issue is done:
1. Change triangle to normal tab stop circle with number and includes salmon colored notification circle [DONE]
2. Increase red circles from 32 to 36px and increase text size from 24 to 28 or 26 pts [DONE]
3. Add a 1px border around the notification dot the same grey as the background of the circle [DONE]

**Comment by drjoho** [comment]
Approved by Alex / Design so I will close.
