### ISSUE TITLE
[BUG]: Color contrast not processing transparency correctly

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#1182]
### Project

a11y checker engine

### Browser

Chrome

### Operating system

MacOS

### Description

Detected a false positive

### Steps to reproduce

See https://codesandbox.io/s/issue-1182-uxbgi1

**Comment by eirckr** [comment]
Validated: 
<img width="1529" alt="Screen Shot 2023-01-17 at 4 17 01 PM" src="https://user-images.githubusercontent.com/62436670/213024642-0277bf21-bdd6-4461-aa1d-fccb83b20b45.png">
