### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by smokiebabygirl** [IBMa/equal-access#1186]
### Project

able site

### Browser

Safari

### Operating system

Other

### Description

Identify theft, from domestic terriosm, treasonists, threaten too kill over you tube stations,  etc., etc. this message is coming from AG DEPUTY CHIEF LONZETTA WASHINGTON GROVES CLEVELAND USM JAG, DOJ ADDRESS: RESIDING : now, 131 WEST CONCORD DRIVE APT. A AN COMMENDED APARTMENT COMPLEX WITH OTHERS UNDER A FAKE NAME "THE RETREAT OF CONCORD VILLAGE", CLARKSVILLE, TN. 37042.

### Steps to reproduce

NEED POLICE PROTECTION . USE GOOGLE/ EDGE

**Comment by marcjohlic** [comment]
Reported as spam
