### ISSUE TITLE
[ACT:afw4f7] Background color calculation issue when the background is gradient 

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#1201]
When the background is gradient, the background color cannot be calculated.  

see pass & fail example 2 [ACT afw4f7](https://wai-wcag-act-rules.netlify.app/standards-guidelines/act/rules/afw4f7/proposed/).
example 7 with an exception (reason not known)

**Comment by ErickRenteria** [comment]
Pushed
