### ISSUE TITLE
[A11y_Bug]: 

### ISSUE THREAD

**Issue by jayayuvi161** [IBMa/equal-access#1215]
### Project

karma accessibility checker

### Browser

Chrome

### Operating System

Windows

### Automated testing tool and ruleset

devops and aws

### Assistive technology

maven

### Description

N/A of the maven build tool and ci/cd and docker containers 
terrafom using 

### Steps to reproduce

devops and aws using the one jare file

**Comment by tombrunet** [comment]
Problem not stated clearing. Closing and deleting.
