### ISSUE TITLE
[BUG] Fix Keyboard Mode zoom problem

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1221]
Here is KCM visualization when browser page is "actual size" and the visualization works appropriately:

![image.png](https://images.zenhubusercontent.com/61081394ffd52d20c363a4cd/33621c9b-f12c-4542-b066-f4dd37a71438)

Here is what happens to the KCM visualization after two instances of Cmd-+

![image.png](https://images.zenhubusercontent.com/61081394ffd52d20c363a4cd/7da8bdd5-fdf3-4fd8-b8c0-60adffb5d6a2)

Note that the Chrome browser yields element location and size according to the "actual size" page no matter the zooming.

**Comment by eirckr** [comment]
Validated
