### ISSUE TITLE
R5.1 Planning for the extension

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#1241]

**Comment by drjoho** [comment]
Tom and I met for 2 hours yesterday and worked on a mural populated with the initial breakdown of the large components for the extension. https://app.mural.co/t/ibmaccessibility7766/m/ibmaccessibility7766/1674155456069/39349dbd9e49ee4e9a5edca843da2a8fad8c3f4d?sender=josiahhoskins2556

**Comment by drjoho** [comment]
An initial set of broad tasks for the "Refactoring"
1. Rearchitecture the list data to a tree
2. Refactor the components to smaller components
3. Cleanup code to make code smaller and easier to maintain.
