### ISSUE TITLE
[Ext] Create KCMOverview

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#1262]
<img width="508" alt="image" src="https://user-images.githubusercontent.com/19577713/214137106-20c1b511-fd2c-4a45-b0dd-641471b9640f.png">

**Comment by drjoho** [comment]
Bit of work left at the bottom of the KCM guidance popup - an icon and a checkbox.

**Comment by drjoho** [comment]
Latest
<img width="553" alt="image" src="https://user-images.githubusercontent.com/64442976/227578212-c06f86ff-3cf9-4ed6-bc58-05bb8770b943.png">

**Comment by drjoho** [comment]
DONEN
