### ISSUE TITLE
[Ext] Create BrowserKCM - Data Setup

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#1263]
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/19577713/214136976-039a8c6d-2936-4258-81fd-e238c8cdc002.png">
See draw.ts

**Comment by drjoho** [comment]
The initial task here is to cleanup the code and make it smaller, cleaner and easier to understand. After Tom has rearchitected the messages I will incorporate them into the clean code.

**Comment by drjoho** [comment]
Cleaning up the highlighting code which took a lot of time to get right. Now messing with it again. Trying to reduce LOC (lines of code) by introducing more functions to replace repeated code.

**Comment by drjoho** [comment]
Reduced more code in highlighting section. Found more code related to doc type (main, iframe, shadowdom) that I should be able to cut down.

**Comment by drjoho** [comment]
KCM messages

1. DRAW_TABS_TO_CONTEXT_SCRIPTS - listener  Event to massage report data and drawKCM 
2. TABSTOP_RESZE - send to background to execute  Try to redraw if Web page is resized  
3. HIGHLIGHT_TABSTOP_TO_CONTEXT_SCRIPTS - listener  As user tabs to a tabstop or mouse clicks on a tab stop it becomes highlighted 
4. DELETE_DRAW_TABS_TO_CONTEXT_SCRIPTS - listener  When user toggles the KCM button and the tabs are drawn on the web page delete the visualization. 
5. TABSTOP_XPATH_ONCLICK - send to background to execute  This message containing xpath and circleNumber + 1 is sent to the background and the corresponding circle object is returned. 

New KCM messages

1. ViewState listener - if KCM is active === true; else false.  Notes: Scan must occur before viewState.kcm can be set to true.              Also, maps to DRAW_TABS_TO_CONTEXT_SCRIPTS and              DELETE_DRAW_TABS_TO_CONTEXT_SCRIPTS above 
2. Report listener to get the data for KCM panel and the visualization   Gets the data needed when viewState.kcm == true 
3. Highlight listener 
4. GetTabStopElement send to  background and execute

**Comment by drjoho** [comment]
Working on getting the KCM Rule Issues in the right place in the code.

**Comment by drjoho** [comment]
Progress:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/64442976/220410814-e381b5c2-eb4d-4047-8385-5b837206a2d9.png">

**Comment by drjoho** [comment]
Continuing in #1310

**Comment by drjoho** [comment]
Closing moving to #1310
