### ISSUE TITLE
Ensure keyboard mode error circles have a keyboard issue

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1279]
As we can see in the screenshot below Tab Stop number 20 is confused:

![image.png](https://images.zenhubusercontent.com/61081394ffd52d20c363a4cd/b9d4847c-d9c3-41fb-85a5-07b9b7f3b751)

**Comment by drjoho** [comment]
Figured out the problem. It was not the rules. The problem was that there was a regular circle exactly on top of a error circle. So now have to come up with a way to deal with circle that lie on top of each other.

**Comment by sct-will** [comment]
Dependency on another issue.

**Comment by drjoho** [comment]
Exact overlapping tab stop circles (i.e., circles for the same element) fixed:
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/64442976/225407420-282c145c-00b8-48ca-977d-cb8137f636de.png">
