### ISSUE TITLE
[BUG]: possible false positive for elements created using React.createPortal 

### ISSUE THREAD

**Issue by TannerS** [IBMa/equal-access#1299]
### Project

a11y checker

### Browser

Chrome, Firefox

### Operating system

MacOS

### Description

based on this conversation, we think there is a false positive. Please see section about Content within landmark issue 

https://ibm-cloudplatform.slack.com/archives/C2K6RFJ1G/p1663108123574489

### Steps to reproduce

Code posted in https://ibm-cloudplatform.slack.com/archives/C2K6RFJ1G/p1663108123574489

**Comment by aliunwala** [comment]
Triage:
We think this is a valid false positive and we will take a look at it in a later sprint.

**Comment by shunguoy** [comment]
a simple test case: https://codesandbox.io/s/cranky-sunset-3yxyf4?file=/index.js

**Comment by shunguoy** [comment]
note the way the React.createPortal works is it adds the portal nodes directly under the parent specified in the second parameter. It doesn't look like a false positive.
