### ISSUE TITLE
504 error [A11y_Bug]: 

### ISSUE THREAD

**Issue by boolamatara** [IBMa/equal-access#1303]
### Project

a11y checker engine, a11y checker extension, a11y checker

### Browser

Chrome

### Operating System

Windows

### Description

Hello and thank you 
we are trying to use your informaton data and reciving 

504 error 

you can check this here 
https://able.ibm.com/rules/archives/preview/doc/en-US/Rpt_Aria_MultipleNavigationLandmarks_Implicit.html

please assist us 

### Steps to reproduce

you can click:
https://able.ibm.com/rules/archives/preview/doc/en-US/Rpt_Aria_MultipleNavigationLandmarks_Implicit.html

**Comment by aliunwala** [comment]
Triage meeting:

We saw some instability on this URL/server in the last day or so this should be working now. 

If you are still seeing this please reopen this issue.

**Comment by Purplelens** [comment]
Hello there is issue again 

Project
a11y checker engine, a11y checker extension, a11y checker

Browser
Chrome

Operating System
Windows

Automated testing tool and ruleset
No response

Assistive technology
No response

Description
Hello and thank you
we are trying to use your informaton data and reciving

504 error

you can check this here
https://able.ibm.com/rules/archives/preview/doc/en-US/Rpt_Aria_MultipleNavigationLandmarks_Implicit.html

please assist us

Steps to reproduce
you can click:
https://able.ibm.com/rules/archives/preview/doc/en-US/Rpt_Aria_MultipleNavigationLandmarks_Implicit.html
