### ISSUE TITLE
ARIA in HTML update: disallow aria-hidden on body element

### ISSUE THREAD

**Issue by scottaohara** [IBMa/equal-access#1336]
In tandem with [efforts moving forward with the ARIA WG](https://github.com/w3c/aria/issues/1254), ARIA in HTML is being updated to disallow the use of `aria-hidden` on the `body` element.

The intent would be that the same error that the checker already exposes for using `aria-hidden=true` on the `html` element would also be raised if the attribute was used on the `body` element.

We consider this rule already partially supported by this checker, due to the fact that if focusable elements are used on a web page, which would be quite common, that the misuse of `aria-hidden` is indirectly exposed that way.

**Comment by aliunwala** [comment]
Triage:
This is in the spec here:
https://w3c.github.io/html-aria/

<img width="821" alt="image" src="https://user-images.githubusercontent.com/4451128/223234110-f66368f4-4434-4d4e-b6ce-ecf43c3cfd74.png">

We still need to discuss supporting editor's drafts. Will leave this in the Triage pipeline until this discussion is complete.

**Comment by aliunwala** [comment]
We see it now published at https://www.w3.org/TR/html-aria/ as well

**Comment by ErickRenteria** [comment]
Validated
