### ISSUE TITLE
[BUG]: make sure to provide an accessible name when it's required by ARIA

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#1338]
### Project

a11y checker engine

### Browser

Chrome

### Operating system

MacOS

### Description

ARIA requires an accessible name for the elements with certain roles:

    alertdialog (author)
    application (author)
    button (author/content)
    checkbox (author/content)
    columnheader (author/content)
    combobox (author)
    dialog (author)
    form(author)
    grid(author)
    heading (author/content)
    img (author)
    link (author/content)
    listbox (author)
    meter (author)
    menuitem (author/content)
    menuitemcheckbox (author/content)
    menuitemradio (author/content)
    option (author/content)
    progressbar (author)
    radio (author/content) 
    radiogroup (author)
    region (author)
    rowheader (author/content)
    searchbox (author)
    slider (author)
    spinbutton (author)
    switch (author/content)
    table (author)
    tabpanel (author)
    textbox (author)
    tooltip (author/content)
    tree (author)
    treegrid (author)
    treeitem (author/content)
    

### Steps to reproduce

test/v2/checker/accessibility/rules/Valerie_Table_DataCellRelationships_ruleunit/dataTableWithThNotInFirstRowOrCol.html

the table element with an implicit role 'table' doesn't have an accessible name, but the checker doesn't report the issue:

<img width="1470" alt="Screenshot 2023-03-03 at 12 03 47 PM" src="https://user-images.githubusercontent.com/18539498/222794787-00389b2b-cef0-4185-97cc-6826397c794d.png">

**Comment by MHoov** [comment]
We may or may not have an existing rule that addresses this. Tom is aware of some specific cases that we check.

**Comment by ErickRenteria** [comment]
Validated
