### ISSUE TITLE
[BUG]: Checker xlsx report is getting an alert "problem with some content" 

### ISSUE THREAD

**Issue by ErickRenteria** [IBMa/equal-access#1345]
### Project

a11y checker extension

### Browser

Chrome, Firefox

### Operating system

MacOS

### Description

After downloading a report from the checker and trying to open, user gets an Alert: 
<img width="399" alt="Screenshot 2023-03-09 at 12 30 39 PM" src="https://user-images.githubusercontent.com/62436670/224365722-ab8ae656-f87d-4a62-b868-6e33a445c63d.png">

Tested with Checker version 3.1.46
Report attached for review: 
[Accessibility_Report-Altoro Accessibility Testing Site.xlsx](https://github.com/IBMa/equal-access/files/10943829/Accessibility_Report-Altoro.Accessibility.Testing.Site.xlsx)

### Steps to reproduce

1. Navigate to a site and run a scan with checker
2. Download the current scan
3. Try to open the scan 

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>Repair Result to Accessibility_Report-IBM Software - Project MaX1.xml</logFileName><summary>Errors were detected in file '/Users/erick/Plugin_test/March_09_release/Accessibility_Report-IBM Software - Project MaX.xlsx'</summary><repairedRecords summary="Following is a list of repairs:"><repairedRecord>Repaired Records: String properties from /xl/sharedStrings.xml part (Strings)</repairedRecord></repairedRecords></recoveryLog>`

**Comment by aliunwala** [comment]
Okay looks like we were able to reproduce it here:
https://w3.ibm.com/w3publisher/cloud-cognitive/project-max

So looks like a valid issue. Will drop it into to backlog to get priortized

**Comment by aliunwala** [comment]
We thought this might be a bug with how the title of the page or the length of an field might be causing the XLSX to error out. This could be one avenue for investigation.

**Comment by tombrunet** [comment]
Looks like the code snippets are over the Excel limit because they have images encoded in the style attribute. Kicking this back to the backlog since we need to discuss what to do about this.

**Comment by MHoov** [comment]
Tom's recommendation:  truncate it at 32,000 charactes
