### ISSUE TITLE
[Question]: Usage with Storybook a11y extension (hence usage with axe-core)?

### ISSUE THREAD

**Issue by blazejpawlak** [IBMa/equal-access#1349]
### Project

a11y checker engine

### Description

Hi,

We're looking into extending our Storybook based a11y extension to take `equal-access` rules into consideration.
Storybook is using `axe-core`, do we have any way interfacing `equal-access` with that component?

Cheers,
Blaze

**Comment by tombrunet** [comment]
We don't have a pre-built Storybook plugin. However, the engine itself is JavaScript and can be accessed in a browser environment. You can pull the engine in from an NPM CDN like unpkg and integrate it - See https://www.npmjs.com/package/accessibility-checker-engine for more information.

**Comment by aliunwala** [comment]
@blazejpawlak If you need any additional help feel free to reopen this ticket.
