### ISSUE TITLE
[A11y_Bug]: 

### ISSUE THREAD

**Issue by ssljc5775** [IBMa/equal-access#1364]
### Project

able site, a11y checker engine, a11y checker extension, a11y checker, cypress accessibility checker, karma accessibility checker, rule-server, other

### Browser

Chrome, Safari, Firefox

### Operating System

MacOS, Windows, Other

### Assistive technology

hi ferdie

### Description

very satisfying

### Steps to reproduce

by copyright and copyleft

**Comment by tombrunet** [comment]
No information
