### ISSUE TITLE
[BUG] Accessibility Checker plugins generate Use of Color (1.4.1) warnings for stylesheets

### ISSUE THREAD

**Issue by jendowns** [IBMa/equal-access#137]
## What tool(s) are you using?

- [ ] `accessibility-checker-engine`
- [x] `accessibility-checker`
- [ ] `karma-accessibility-checker`
- [ ] `rule-server`
- [ ] `boilerplates`
- [ ] `other`

## Detailed description

Whenever you run the Accessibility Checker plugin (Firefox and Chrome), the plugin will generate warnings for all stylesheet link elements on the page (i.e., `<link href="path/to/styles" rel="stylesheet" />`), saying that there may be a Use of Color (checkpoint 1.4.1) issue.

```
Needs review
Verify color is not used as the only visual means of conveying information
Combine color and descriptive markup to convey information

IBM 1.4.1 Use of color
```

<img width="1110" alt="Screen shot of 'Use of Color' warning in the Accessibility Checker plugin for a stylesheet import." src="https://user-images.githubusercontent.com/9057921/86385552-12646480-bc56-11ea-8281-d1366c2c8c63.png">

Is this intentional? I'm thinking that it may be best to ignore things that are recognized as stylesheet imports in this case, since they aren't the same as interactive links, etc. But please let me know what you think -- thank you!

**Comment by eirckr** [comment]
Thanks for the ticket, we will review and get back to you.

**Comment by tombrunet** [comment]
The rule does look a bit into the stylesheet. It won't trigger on an external stylesheet that does not define colors. There is still the question of whether this is more noisy than helpful, however, the intent was to help identify stylesheets that are contributing color to the page. We're still discussing.

**Comment by tombrunet** [comment]
Will only trigger once per page in the Oct 07, 2020 rulepack
