### ISSUE TITLE
performance issue with deeply nested layout tables and other structures

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#1384]
When a page with deeply nested layout tables, the page hangs. The issue was introduced when we changed the implicit role of a tr element into 'row' per the ARIA definition change in 3.1.36. see details in the change: https://github.com/IBMa/equal-access/compare/3.1.35...3.1.36

**Comment by shunguoy** [comment]
nested DOM Walkers caused a large number of stack frames, dragging down the performance and even hanging.  The fix is to add caching to eliminate duplications to improve performance.

**Comment by ErickRenteria** [comment]
Merged
