### ISSUE TITLE
Erro ao acessar página https://w3.ibm.com/hr/badge-me/application/64357f20bef84cae4d04e5a9

### ISSUE THREAD

**Issue by raquelgarcia39** [IBMa/equal-access#1387]
### Project

other

### Browser

Chrome, Safari

### Operating System

Windows

### Description

Bom dia! estou tentando acessar a página abaixo e aparece uma mensagem de erro em anexo
![Erro página](https://user-images.githubusercontent.com/130498932/231477606-05fa4037-3e4d-4a21-82a1-c6bc84e069bc.jpg)

https://w3.ibm.com/hr/badge-me/application/64357f20bef84cae4d04e5a9

### Steps to reproduce

https://w3.ibm.com/hr/badge-me/application/64357f20bef84cae4d04e5a9

**Comment by tombrunet** [comment]
This repository is for the ibm.com/able site and the Equal Access Accessibility Checker tools. The URL you mentioned does not seem to be related to this scope. If we are linking to that page somewhere, please re-open the issue with more information regarding where we link to that site.
