### ISSUE TITLE
Total count to right of issue filters should be disabled if total count is 0

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1401]
If Issues found is 0. Then disable. If > 0 then enable.

![image.png](https://images.zenhubusercontent.com/61081394ffd52d20c363a4cd/e424fa8e-826d-4d82-b594-2aeda52fc27b)

**Comment by drjoho** [comment]
Ready for QA

**Comment by ErickRenteria** [comment]
@drjoho can you please provide the PR/branch to validate?

**Comment by drjoho** [comment]
Tom already put it in the main branch

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: ErickR ***@***.***>
Sent: Thursday, April 27, 2023 2:59:11 PM
To: IBMa/equal-access ***@***.***>
Cc: Josiah Hoskins ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [IBMa/equal-access] Total count to right of issue filters should be disabled if total count is 0 (Issue #1401)

@drjoho can you please provide the PR/branch to validate? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <IBMa/equal-access/issues/1401/1526317198@ github. com>
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

@drjoho<https://github.com/drjoho> can you please provide the PR/branch to validate?

**Comment by ErickRenteria** [comment]
Validated
