### ISSUE TITLE
Fix issue filters/counting

### ISSUE THREAD

**Issue by MHoov** [IBMa/equal-access#1409]
Refer to internal design issue [#5370](https://github.ibm.com/ibma/e2e/issues/5370)

***Current implementation:***
<img width="693" alt="image" src="https://media.github.ibm.com/user/1218/files/357ea12c-db8e-421e-a06d-76574dccbcea">

KCM design:
<img width="516" alt="image" src="https://media.github.ibm.com/user/1218/files/95a47c99-e817-40ca-a101-8a867788202e">

* For current scans, report titles are below the filters, and for KCM the report titles are above. Can we add the tab list as just another tab - it's really just another view of the latest scan, so not really any reason to not let people flip back and forth if desired. However, if the filter labels change, it might make sense to have those tabs above the checkboxes?
* Location of the issue count inconsistent
* Checkbox labels - do we keep what we have? The capitalization and verbosity don't seem consistent.

***New design for implementation***
this is the final [design on figma](https://www.figma.com/file/intddqthciXilHQCLWppQ7/a11y-checker?node-id=0-1&t=wGf5WZN8TOffGjOT-0) from Jess

![Screen Shot 2023-04-24 at 10.35.35 AM.png](https://zenhub.ibm.com/images/5d641f030c9aa55544dba60a/aec7eeba-c6db-4d52-8f6a-70320a1a8512)

**Comment by drjoho** [comment]
Tom says ready to close.
