### ISSUE TITLE
[BUG]: FF unable to display the help from a scan - continue spinning 

### ISSUE THREAD

**Issue by ErickRenteria** [IBMa/equal-access#1419]
### Project

a11y checker extension

### Browser

Firefox

### Operating system

MacOS

### Description

When conduct a scan on FF and select the help is not coming up. We get a blank page with a spinner. 
Please review attachment 
<img width="1171" alt="Screenshot 2023-04-26 at 11 56 27 AM" src="https://user-images.githubusercontent.com/62436670/234648459-f7ce4ebc-bffd-4639-bb18-d9085b9d5cbe.png">

### Steps to reproduce

Scan a page then select a help or lear more

**Comment by tombrunet** [comment]
@ErickRenteria We might need to get on a webex, or look into this in the office tomorrow. I can't reproduce this.

**Comment by shunguoy** [comment]
triage: Josiah is going to investigate the issue more to see if it's reproducible in the current code.

**Comment by shunguoy** [comment]
Triage:  @tombrunet took over this one for further investigation.

**Comment by shunguoy** [comment]
triage: it seems the issue was fixed as it cannot be reproduced. 
@ErickRenteria  please confirm this. If it's fixed, then close it, thanx.

**Comment by ErickRenteria** [comment]
Unable to reproduce
