### ISSUE TITLE
[BUG]: The help text for the hover for violation/need review and recommendations are not coming up 

### ISSUE THREAD

**Issue by ErickRenteria** [IBMa/equal-access#1420]
### Project

a11y checker extension

### Browser

Chrome

### Operating system

MacOS

### Description

When an user hovers over the violations check mark text and needs review and Recommendations; the help text is not coming up. Only if the checkmark is clicked is when the help comes up. 

### Steps to reproduce

Conduct a scan, 
over over the Violations, needs review and Recommendations. 
<img width="885" alt="Screenshot 2023-04-26 at 12 33 06 PM" src="https://user-images.githubusercontent.com/62436670/234656716-118d4446-0335-4f11-bb68-dd2f435e083c.png">

**Comment by shunguoy** [comment]
triage: it seems to happen in the previous version, and it also looks like a Carbon issue

**Comment by tombrunet** [comment]
The Carbon checkbox is absorbing the hover, so the tooltip is not aware of it. It's not the selected state that is causing it to show, but rather the focus state. When you click the checkbox, the focus gets set, which triggers the tooltip. Feels like a Carbon problem to me.

**Comment by MHoov** [comment]
@ErickRenteria or @drjoho please open the Carbon issue and put a link here.

**Comment by MHoov** [comment]
Resolved in last UI update
