### ISSUE TITLE
[BUG]: KCM does not start on a clean install 

### ISSUE THREAD

**Issue by ErickRenteria** [IBMa/equal-access#1425]
### Project

a11y checker extension

### Browser

Chrome

### Operating system

MacOS

### Description

When user install the checker then conducts a scan and enables KCM, KCM fails to start. This is happening on a clean install. You can get this going if you close the checker, refresh the page and relaunch the checker and then KCM. We should tried to fix this before releasing to improve the user experience. Please review attachments.  

### Steps to reproduce

Install the Checker
Conduct a scan
Select KCM 

Video located here https://ibm.ent.box.com/notes/1187035251354

**Comment by drjoho** [comment]
Download Action for 2023-ext-arch.
Quit chrome.
Start chrome.
Add extension using load-unpacked
get page ibm.com/able
try checker and KCM

**Comment by ErickRenteria** [comment]
Validated
