### ISSUE TITLE
[BUG]: When choose focused view the focus flips back to all

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1426]
### Project

a11y checker extension

### Browser

Chrome

### Operating system

MacOS

### Steps to reproduce

Say you have the following situation:
<img width="530" alt="Screenshot 2023-04-28 at 1 19 12 PM" src="https://user-images.githubusercontent.com/64442976/235224575-576202c3-c41d-4d3d-b1e0-d8a1864de203.png">

Now choose the focused view <div>
<img width="530" alt="Screenshot 2023-04-28 at 1 19 36 PM" src="https://user-images.githubusercontent.com/64442976/235224706-07b968d5-5e11-4e03-abcf-5216699ae2c0.png">

It will flip back to All in a couple of seconds
<img width="530" alt="Screenshot 2023-04-28 at 1 19 12 PM" src="https://user-images.githubusercontent.com/64442976/235224652-4c952fc1-0ab1-4e87-9118-258ea5f9d4fe.png">

**Comment by drjoho** [comment]
I assume somehow the focus view state is getting accidentally changed back

**Comment by ErickRenteria** [comment]
Validated
