### ISSUE TITLE
[BUG]: is autocomplete "one-time-code" supported?

### ISSUE THREAD

**Issue by Alb93** [IBMa/equal-access#1435]
### Project

a11y checker extension

### Browser

Chrome

### Operating system

MacOS

### Description

Is input's attribute autocomplete="one-time-code" not supported by the tool? It gives:

<img width="328" alt="image" src="https://user-images.githubusercontent.com/11390668/237046711-d446d5ab-7c44-4582-907f-2b3a061b6925.png">

being 
<img width="531" alt="Screenshot 2023-05-09 at 10 56 59" src="https://user-images.githubusercontent.com/11390668/237046768-498b2129-4256-4d88-8bbd-d3eff2980ef9.png">

### Steps to reproduce

Create a OTP input with autocomplete="one-time-code"

**Comment by shunguoy** [comment]
Assigned to Tom for review

**Comment by ErickRenteria** [comment]
Validated with test
