### ISSUE TITLE
Checker dark mode and user guide for implementation

### ISSUE THREAD

**Issue by MHoov** [IBMa/equal-access#1444]
Refer to internal issue Figma designs for dark mode [#5518](https://github.ibm.com/IBMa/E2E/issues/5518)

Per Jess
[checker dark mode](https://www.figma.com/file/intddqthciXilHQCLWppQ7/a11y-checker?type=design&node-id=0-1&t=9UBXg80RvjGfbjWu-0), [options page, and user guide](https://www.figma.com/file/dfM2ZrpfQ55Xi1INlqYkk4/documentation?type=design&node-id=0-1&t=aSH6baZgPY4GjV2f-0) designs on figma

![Screen Shot 2023-05-11 at 4.54.06 PM.png](https://zenhub.ibm.com/images/5d641f030c9aa55544dba60a/6434ae35-ed22-4be6-a689-69346386cd09)

*note for the quick guide, this visual will be different (the #2 circle has a dark outline instead of white outline)
![Screen Shot 2023-05-11 at 5.04.27 PM.png](https://zenhub.ibm.com/images/5d641f030c9aa55544dba60a/2583631d-0848-4c16-9f71-095c2202bc01)

**Comment by MHoov** [comment]
@tombrunet and @drjoho to review

**Comment by drjoho** [comment]
Basically the situation is this:

<img width="1089" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/acab5212-bfa1-4c01-a7aa-07bb13f08d54">

The Checker panel is the only panel that reflects dark mode. All other panels, popups, modals, etc do not present as dark mode. 

Hence, I will work through them.

**Comment by drjoho** [comment]
Progress:
<img width="1401" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/12123492-fdd8-4842-948d-88e4d6373943">

**Comment by drjoho** [comment]
<img width="1061" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/6f336d8f-7457-4bc9-afce-6515d6b1343c">

**Comment by drjoho** [comment]
<img width="1916" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/6f6d802d-b991-44ea-8ec6-70ec1698376f">

**Comment by drjoho** [comment]
<img width="1916" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/f1f43361-31aa-4f1e-92a8-b42f8891ddcd">

**Comment by drjoho** [comment]
Still work to do on the help:

<img width="1916" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/01854933-48b1-4cc1-a934-199d4f63bf1d">

**Comment by drjoho** [comment]
Here is the Quick Guide. Do we need to have Dark mode images that switch out based on light and dark mode?

**Comment by drjoho** [comment]
Here we have a problem that I have not been able to figure out. Below in the Carbon Overflow Menu when I use the dark mode theme the ability to move to different menu items with the keyboard does not work. Also there is an odd white line between the Overflow Menu button and the menu items.

<img width="1916" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/32ec6dc9-4a42-45a3-8942-57f94726ae31">

**Comment by drjoho** [comment]
Full user guide

<img width="1916" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/7b391ae1-12dc-4c0b-b376-e57336b266fc">

**Comment by drjoho** [comment]
Close on the options. There is a problem with pageapp-root that leaves the bottom white. 

<img width="1916" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/bf5fbe21-8158-44ac-9410-3e7f318c0a3a">

**Comment by drjoho** [comment]
As a reminder to myself I need to find all popups and anything else that needs to be dark mode and fix.

**Comment by drjoho** [comment]
View of stored scans
<img width="1916" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/e7bbece4-9d43-44ad-8afa-82e7a19d28a2">

**Comment by ErickRenteria** [comment]
Validated, merging
