### ISSUE TITLE
Overlay look and feel in the Elements panel

### ISSUE THREAD

**Issue by MHoov** [IBMa/equal-access#1455]
Re: design issue [[Ext-Design] Overlay look and feel in the Elements panel #5365](https://github.ibm.com/IBMa/E2E/issues/5365)

@thbrunet potential new designs for "learn more" in expanded view and in modal view (im showing the full modal, but i'm expecting it will be default height and made scrollable)

![Screen Shot 2023-03-22 at 12.23.10 PM.png](https://zenhub.ibm.com/images/5d641f030c9aa55544dba60a/a99ed0a4-287a-4f78-932e-6c44173b63f1)

**Comment by drjoho** [comment]
@tombrunet please review PR #1499. Should be a quick review.

**Comment by ErickRenteria** [comment]
<img width="1023" alt="Screen Shot 2023-06-28 at 12 52 42 PM" src="https://github.com/IBMa/equal-access/assets/62436670/6483f2ad-c21d-46b7-be5f-a0760bf67102">

**Comment by ErickRenteria** [comment]
Merged and validated
