### ISSUE TITLE
[BUG]: Cannot find module 'webpack-cli/package.json'

### ISSUE THREAD

**Issue by zwiastunsw** [IBMa/equal-access#1462]
### Project

a11y checker engine, a11y checker, rule-server

### Browser

_Chrome v. 113.0.5672.127, 64-bit 

### Operating system

Windows

### Description

when I try to start the server, the script stops working on the command: 
Installing 'webpack-cli' (running 'npm install -D webpack-cli')...
The command is executed and then an error occurs:
```
Error: Cannot find module 'webpack-cli/package.json'
Require stack:
- C:\Users\audyt\AppData\Local\npm-cache\_npx\89d6e678e21f2dae\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at runCli (C:\Users\audyt\AppData\Local\npm-cache\_npx\89d6e678e21f2dae\node_modules\webpack\bin\webpack.js:78:26)
    at C:\Users\audyt\AppData\Local\npm-cache\_npx\89d6e678e21f2dae\node_modules\webpack\bin\webpack.js:178:5
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\audyt\\AppData\\Local\\npm-cache\\_npx\\89d6e678e21f2dae\\node_modules\\webpack\\bin\\webpack.js'
    ```

### Steps to reproduce

cd ./rule server
npm run start

**Comment by tombrunet** [comment]
Please run `npm install` in the equal-access root directory that you have extracted. That will install all of the necessary dependencies for all of the various components. That said, the error stack you pasted doesn't seem to be anything related to our project, so you may have installed something globally that it's picking up if you didn't install all of the packages for all of the components.
