### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#1491]
Chrome 114 - Checker 3.1.50
Page: https://finance.yahoo.com/
click "Home" tab
The scan button will keep spinning, and a console error was thrown from the extension:

![Screenshot 2023-06-14 at 9.44.57 AM.png](https://images.zenhubusercontent.com/61d72f5790898928dfc7024b/6b166af3-7bba-4129-9e00-da270f987224)

Captured testcase (from the header element):
https://codesandbox.io/s/issue-1491-kfwqxf?file=/index.html

**Comment by tombrunet** [comment]
We should also see if we can catch this exception and not have the whole checker hang. We should be catching all rule exceptions, but maybe call stack exceptions aren't caught.

**Comment by tombrunet** [comment]
For reference: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-owns
> The aria-owns-owned element should be an element that belongs to a separate parent tree in the DOM but should be treated as a child of the current element.

**Comment by ErickRenteria** [comment]
Validated and merged
