### ISSUE TITLE
Update to warn against potential redundant role for S element

### ISSUE THREAD

**Issue by scottaohara** [IBMa/equal-access#1518]
[HTML AAM](https://github.com/w3c/html-aam/pull/442) has been updated to map the s element to role=deletion with Chromium and Gecko having implemented this change, and an issue against webkit has been filed for them to do so as well.

ARIA in HTML is being updated https://github.com/w3c/html-aria/issues/466 to reflect this change

Previously any role was allowed for the s element. That is still true but for the fact that like other elements with implicit roles it is now 'not recommended' for devs to use role=deletion on the element since it will already expose that.

The checker can surface this as a warning, as it does for other similar elements.

**Comment by ErickRenteria** [comment]
Validated
