### ISSUE TITLE
[BUG]: Low scans due to an error in invocation, scan button keep spinning.  

### ISSUE THREAD

**Issue by ErickRenteria** [IBMa/equal-access#1520]
### Project

a11y checker extension

### Browser

Chrome

### Operating system

MacOS

### Description

Tested with the lasted master action. When conduction a scan on https://www.ibm.com/able/toolkit/develop/overview 
The checker gets the following error and scan button keeps spinning. 

`background.js:2 {type: 'BG_requestScan', dest: {…}, content: 1357278005}content: 1357278005dest: tabId: -1type: "background"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()type: "BG_requestScan"[[Prototype]]: Object TypeError: Error in invocation of scripting.executeScript(scripting.ScriptInjection injection, optional function callback): Error at parameter 'injection': Error at property 'target': Missing required property 'tabId'.
    at g (background.js:2:2331956)
    at background.js:2:2332684
    at new Promise (<anonymous>)
    at background.js:2:2332663
    at Generator.next (<anonymous>)
    at background.js:2:1157876
    at new Promise (<anonymous>)
    at e (background.js:2:1157621)
    at y (background.js:2:2332616)
    at D.<anonymous> (background.js:2:2324430)`

![Screen Shot 2023-06-29 at 9 15 29 PM](https://github.com/IBMa/equal-access/assets/62436670/4b93ced2-4985-45e0-95fb-6e6190434bc7)
![Screen Shot 2023-06-29 at 9 13 00 PM](https://github.com/IBMa/equal-access/assets/62436670/01fcb440-7bf5-4ed2-ad8f-a342cdde7a9a)

### Steps to reproduce

Load the lates from master (Action). 
Scan https://www.ibm.com/able/toolkit/develop/overview
Open dev tools for checker.

**Comment by ErickRenteria** [comment]
@tombrunet @drjoho Please review

**Comment by shunguoy** [comment]
cannot duplicate with the current master or the latest release.

**Comment by marcjohlic** [comment]
@ErickRenteria please confirm whether you are still seeing this behavior as we are not able to reproduce it.

**Comment by ErickRenteria** [comment]
This has been resolved
