### ISSUE TITLE
[BUG]: ACEngineManager.js: visitor[(override || node.type)] is not a function

### ISSUE THREAD

**Issue by Jeremias-Bertoldi** [IBMa/equal-access#1555]
### Project

cypress accessibility checker

### Browser

Chrome

### Operating system

MacOS

### Description

Hi I've found this error trying to start accessibility testing, looks like the tool module-deps and cannot parse the ACEngineManager file.

Node version: v20.3.1
NPM version: 9.6.7
Cypress version: 12.0.2
cypress-accessibility-checker: 3.1.57
cypress-cucumber-preprocessor: 4.3.0

This is the **package.json** file.
`{
  "name": "cypress_auto",
  "version": "1.1.0",
  "description": "This version of Pandora cypress repo is used for accessibility testing node v16 required",
  "main": "index.js",
  "scripts": {
    "openOMSStage": "npx cypress open --env configFile=OMS,exec_Env=Staging",
    "openOMSQA": "npx cypress open --env configFile=OMS,exec_Env=QA",
    "openSFSCStage": "npx cypress open --env configFile=SFSC,exec_Env=Staging",
    "openSFSCQA": "npx cypress open --env configFile=SFSC,exec_Env=QA",
    "openOMNIStage": "npx cypress open --env configFile=OMNI,exec_Env=Staging",
    "openOMNIQA": "npx cypress open --env configFile=OMNI,exec_Env=QA",
    "openSFRAStage": "npx cypress open --env configFile=SFRA,exec_Env=Staging",
    "openSFRADev": "npx cypress open --env configFile=SFRA,exec_Env=Development",
    "report:allure": "allure generate cypress/allure-results --clean -o allure-report && allure open  allure-report",
    "lint": "eslint . --ext .ts --ext .js",
    "lint:fix": "eslint . --ext .ts --ext .js.jsx --fix",
    "cy:runOMS": "cypress run --env configFile=OMS,exec_Env=Staging,TAGS=@OMS_RT --record --key 05990b63-5e93-4355-96a4-288bd25f6d9d --spec 'cypress/e2e/Features/OMS/*/*/*.feature' --tag 'OMS-RT:Staging'",
    "cy:runINTS": "cypress run --env configFile=INTS,exec_Env=Staging,TAGS=@INTS_RT --record --key 05990b63-5e93-4355-96a4-288bd25f6d9d --spec 'cypress/e2e/Features/INTS/*/*/*.feature' --tag 'INTS-RT:Staging'",
    "cy:runSFSC": "cypress run --env configFile=SFSC,exec_Env=Staging,TAGS=@SFSC_RT --record --key 05990b63-5e93-4355-96a4-288bd25f6d9d --spec 'cypress/e2e/Features/SFSC/*/*/*.feature' --tag 'SFSC-RT:Staging'",
    "cy:runOMNI": "cypress run --env configFile=OMNI,exec_Env=Staging,TAGS=@OMNI_RT --record --key 05990b63-5e93-4355-96a4-288bd25f6d9d --spec 'cypress/e2e/Features/OMNI_RT/*/*/*/*.feature' --tag 'OMNI-RT:Staging'"
  },
  "author": "akksi",
  "license": "ISC",
  "dependencies": {
    "allure-commandline": "^2.17.2",
    "browserify": "^17.0.0",
    "cypress-mochawesome-reporter": "^3.1.0",
    "cypress-multi-reporters": "^1.6.3",
    "cypress-parallel": "^0.13.0",
    "cypress-zapi-js": "^1.0.9",
    "dayjs": "1.10.4",
    "har-validator": "5.1.5",
    "jsforce": "^1.11.1",
    "junit-report-merger": "^3.0.5",
    "mocha": "^10.0.0",
    "mocha-allure-reporter": "1.4.0",
    "mocha-junit-reporter": "^2.0.2",
    "mochawesome": "^7.1.3",
    "mochawesome-merge": "4.2.0",
    "path": "^0.12.7",
    "typescript": "4.2.4"
  },
  "devDependencies": {
    "@shelex/cypress-allure-plugin": "^2.23.0",
    "atlassian-jwt": "^1.0.2",
    "chai": "^4.2.0",
    "cucumber-html-reporter": "^5.4.0",
    "cypress": "12.0.2",
    "cypress-accessibility-checker": "^3.1.57",
    "cypress-cucumber-preprocessor": "^4.3.0",
    "cypress-iframe": "^1.0.1",
    "cypress-recurse": "^1.23.0",
    "cypress-terminal-report": "^3.2.2",
    "cypress-wait-until": "^1.7.1",
    "cypress-xpath": "^1.6.2",
    "eslint-plugin-chai-friendly": "^0.7.2",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-jsdoc": "^39.6.4",
    "fs-extra": "^9.1.0",
    "gmail-tester": "^1.3.2",
    "hashmap": "^2.4.0",
    "jquery": "^3.4.1",
    "json-web-token": "^3.2.0",
    "moment": "^2.29.4",
    "pandora-cypress-libs": "^1.2.6",
    "request": "^2.88.0"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "nonGlobalStepBaseDir": "cypress/e2e",
    "stepDefinitions": "cypress/e2e",
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/cucumberJson",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    }
  },
  "compilerOptions": {
    "types": [
      "cypress",
      "cypress-wait-until"
    ]
  }
}
`

This is **plugins/index.js** file.
`/// <reference types="cypress" />
const cucumber = require('cypress-cucumber-preprocessor').default

/**
 * @type {Cypress.PluginConfig}
 */
const fs = require('fs-extra')
const path = require('path')
const allureWriter = require('@shelex/cypress-allure-plugin/writer')
const aCheckerTasks = require('cypress-accessibility-checker/plugin')

const { beforeRunHook, afterRunHook } = require('cypress-mochawesome-reporter/lib');  
const exec = require('child_process').execSync;  

module.exports = (on) => {  
  on('before:run', async (details) => {  
    console.log('override before:run');  
    await beforeRunHook(details);  
    //If you are using other than Windows remove below two lines  
    await exec("IF EXIST cypress\\screenshots rmdir /Q /S cypress\\screenshots")  
    await exec("IF EXIST cypress\\reports rmdir /Q /S cypress\\reports")  
  });

  on('after:run', async () => {
    console.log('override after:run');  
    //if you are using other than Windows remove below line starts with await exec  
    await exec("npx jrm ./cypress/reports/junitreport.xml ./cypress/reports/junit/*.xml");  
    await afterRunHook();  
  });  
};

function getConfigurationByFile (file) {
  const pathToConfigFile = path.resolve('cypress', 'environments', `${file}.json`)
  if (!fs.existsSync(pathToConfigFile)) {
    return {}
  }

  return fs.readJson(pathToConfigFile)
}

module.exports = (on, config) => {
  const logOptions = {
    printLogsToConsole: "always"
  }
  require('cypress-terminal-report/src/installLogsPrinter')(on, logOptions)
  on('file:preprocessor', cucumber())
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  on('before:browser:launch', (browser, launchOptions) => {
    if (browser.name == "chrome" && browser.isHeadless)
    launchOptions.args.push('--suppress-message-center-popups')
  })
  const file = config.env.configFile
  
  on('before:browser:launch', (browser, launchOptions) => {
  if (browser.name === 'chrome' && browser.isHeadless) {
      launchOptions.args.push('--disable-gpu');
      return launchOptions
    }
  });

  on('task', {
    accessibilityChecker: aCheckerTasks
  });

  on("task", {
    getPackagePath() {
      return path.dirname(require.resolve("cypress-zapi-js/package.json"));
    },
  });

  on('task', {
    'gmail:get-messages': async args => {
      const cred = path.resolve(__dirname, 'credentials.json')
      gmail.refresh_access_token(cred, 'token.json')
      const messages = await gmail.get_messages(
        path.resolve(__dirname, 'credentials.json'),
        path.resolve(__dirname, 'token.json'),
        args.options
      )
      return messages
    }
  })

  on('task', {
    existsSync({path}) {
      return fs.existsSync(path);
    }
  });

  on('task', {
    readdir({path}) {
      return fs.readdir(path);
    }
  });

  on('task', {
    fixture (fixtures) {
      const result = require('./../fixtures/' + fixtures)
      return result;
    }
  })

  allureWriter(on, config)

  return getConfigurationByFile(file)
}`

### Steps to reproduce

**1.** create StepDefs file:
**IBMAccessibilityChecker_stepDefs.js**
`import { Given, When, Then, And, After } from "cypress-cucumber-preprocessor/steps";

const objData = require('../../../fixtures/Shop_Tribe/SFRA/Generic/GE_Data.json')
const objPOM = require('../../../fixtures/Shop_Tribe/SFRA/Generic/GE_POM.json')

let countryData
let countryPOM
let exec_Country

const env = Cypress.env('exec_Env').toUpperCase()
 
Then("I should see accessibilty issues on HomePage", () => {
    cy.getCompliance("A11yHomePage").assertCompliance()
})

Then("I should see accessibilty issues on PLP", () => {
    cy.getCompliance("A11y scan on PLP").assertCompliance()
})

Then("I should see accessibilty issues on PDP", () => {
    cy.getCompliance("A11y scan on PDP").assertCompliance()
})

Then("I should see accessibilty issues on Cart page", () => {
    cy.getCompliance("A11y scan on Cart page").assertCompliance()
})

Then("I should see accessibilty issues on Checkout Begin", () => {
    cy.getCompliance("A11y scan on Checkout Begin").assertCompliance()
})

Then("I should see accessibilty issues on Checkout Delivery", () => {
    cy.getCompliance("A11y scan on Checkout Delivery").assertCompliance()
})

Then("I should see accessibilty issues on Confirm purchase", () => {
    cy.getCompliance("A11y scan on Confirm purchase").assertCompliance()
})

Then("I should see accessibilty issues on Login Page", () => {
    cy.getCompliance("A11y scan on Login Page").assertCompliance()
})

Then("I should see accessibilty issues on Account page", () => {
    cy.getCompliance("A11y scan on Account page").assertCompliance()
})

Then("I should see accessibilty issues on My Sizes Page", () => {
    cy.getCompliance("A11y scan on My Sizes Page").assertCompliance()
})

Then("I should see accessibilty issues on Edit Profile Page", () => {
    cy.getCompliance("A11y scan on dit Profile Page").assertCompliance()
})

Then("I should see accessibilty issues on Address Book Page", () => {
    cy.getCompliance("A11y scan on Address Book Page").assertCompliance()
})`

**2.** create **.feature** file.
**IBMAccessibilityChecker.feature**
`Feature: IBMAccessibilityChecker

    Background: Launch Storefront
    Given I launch Storefront

    #***************************************************************
    # SFRAT-9910
    # Jeremias Bertoldi
    # Locales to exclude
    # Excluded envs
    # Non-Funcional
    # Accessibility
    @MBA @Smoke
    #***************************************************************

    Scenario: AccessibilityChecks: SFRAT-9877 A11y issues should be logged in Homepage
    Then Disable Captcha if needed
    Then I should see accessibilty issues on HomePage

    Scenario: AccessibilityChecks: SFRAT-9877 A11y issues should be logged in PLP
    Then Disable Captcha if needed
    When I go to a subcategory from main navigation
    Then I should be redirected to PLP and I should be able to see Product Title, Product Name, Product Price, Product Image and Product Badge if any
    Then I should see accessibilty issues on PLP

    Scenario: AccessibilityChecks: SFRAT-9877 A11y issues should be logged in PDP
    Then Disable Captcha if needed
    When I go to a subcategory from main navigation
    Then I should be redirected to PLP and I should be able to see Product Title, Product Name, Product Price, Product Image and Product Badge if any
    And When I click on product name I should be redirected to corresponding PDP
    Then I should see accessibilty issues on PDP

    Scenario: Checkout: SFRAT-9877 Performance should be logged in Cart page
    Then Disable Captcha if needed
    When I add 1 products to cart
    And Go to cart page
    Then I should see accessibilty issues on Cart page

    Scenario: Checkout: SFRAT-9877 Performance should be logged in Checkout Begin
    Then Disable Captcha if needed
    When I add 1 products to cart
    And Go to cart page
    Then Proceed to Checkout page as "guest" user
    Then I should see accessibilty issues on Checkout Begin

    Scenario: Checkout: SFRAT-9877 Performance should be logged in Checkout Delivery
    Then Disable Captcha if needed
    When I add 1 products to cart
    And Go to cart page
    Then Proceed to Checkout page as "guest" user
    And I give shipping information for "guest" user
    Then Submit delivery info
    Then I should see accessibilty issues on Checkout Delivery

    Scenario: Checkout: SFRAT-9877 Performance should be logged in Confirm purchase
    Then Disable Captcha if needed
    When I add 1 products to cart
    And Go to cart page
    Then Proceed to Checkout page as "guest" user
    And I give shipping information for "guest" user
    Then Submit delivery info
    And I give "Mastercard" credit card information
    Then Confirm purchase
    Then I should see accessibilty issues on Confirm purchase

    Scenario: AccessibilityChecks: SFRAT-9877 Performance should be logged in Login Page
    Then Disable Captcha if needed
    When I go to login page
    Then I should see accessibilty issues on Login Page

    Scenario: AccessibilityChecks: SFRAT-9877 Performance should be logged in Account page
    When I go to login page
    Then I should be able to Login with created account and password
    Then I should see accessibilty issues on Account page

    Scenario: AccessibilityChecks: SFRAT-9877 Performance should be logged in My Sizes Page
    When I go to login page
    Then I should be able to Login with created account and password
    Then I go to my sizes page
    Then I should see accessibilty issues on My Sizes Page

    Scenario: AccessibilityChecks: SFRAT-9877 Performance should be logged in Edit Profile Page
    When I go to login page
    Then I should be able to Login with created account and password
    Then I click on edit profile btn
    Then I should see accessibilty issues on Edit Profile Page

    Scenario: AccessibilityChecks: SFRAT-9877 Performance should be logged in Address Book Page
    When I go to login page
    Then I should be able to Login with created account and password
    Then I go to address book
    Then I should see accessibilty issues on Address Book Page`

**3.** Then run cypress with `npx cypress open`
**4.** Then select Chrome as browser and start E2E testing.
<img width="1440" alt="Captura de pantalla 2023-07-17 a la(s) 16 10 08" src="https://github.com/IBMa/equal-access/assets/100160945/809b287e-0c03-4df7-bcbc-a2087cbf2e2c">
**5.** Then select `IBMAccessibilityChecker.feature` to run test.

**Expected result**
The test should start

**Actual result**
The test doesn't start and an error message appears
<img width="1440" alt="Captura de pantalla 2023-07-17 a la(s) 16 14 51" src="https://github.com/IBMa/equal-access/assets/100160945/d2ac77ff-2bdb-4572-a407-860cbb7ae7fb">

CC: @shunguoy

**Comment by shunguoy** [comment]
@Jeremias-Bertoldi sorry for the delay. The latest code has been deployed, please see https://github.com/IBMa/equal-access/releases/tag/3.1.58    
   There are multiple updates on the dependencies.  Could you please try and let me know if your issue was fixed?  thanks.

**Comment by Jeremias-Bertoldi** [comment]
Hi @shunguoy, The error remains

**Comment by tombrunet** [comment]
@Jeremias-Bertoldi Sorry - I've been mostly out the last two weeks. For Cypress 12, we have a release candidate - [4.0.0-rc.1](https://www.npmjs.com/package/cypress-accessibility-checker/v/4.0.0-rc.1). The 3.x versions won't work with Cypress 12.

**Comment by tombrunet** [comment]
You might be okay with the 3.x versions and Cypress 12. I'm running into a different error. Works fine in our test environment, but not running with the package pulled from NPM, so I'm trying to figure out what's different before giving you more recommendations.

**Comment by Jeremias-Bertoldi** [comment]
Ok thank you so much @tombrunet !!

**Comment by tombrunet** [comment]
Just an update - I get a different error, and it seems that Cypress is processing files differently outside the node_modules folder. 

What I see when running the boilerplate with Cypress 12 is an "Unexpected token" due to use of the "static" keyword in ACEngineManager. If I copy the library outside of node_modules and use that instead, everything works fine. Trying to hunt down what the config problem is.

**Comment by tombrunet** [comment]
#1580 should resolve this in the next release. You'll be able to use the 3.x version with Cypress 12.

**Comment by Jeremias-Bertoldi** [comment]
Great @tombrunet, thanks a lot!!

**Comment by Jeremias-Bertoldi** [comment]
Hi @tombrunet do I need to use the library outside node_packages, right? would you help me to set it up?

**Comment by ErickRenteria** [comment]
Merged

**Comment by tombrunet** [comment]
@Jeremias-Bertoldi 3.1.59 was pushed today.
