### ISSUE TITLE
[BUG]: Label descriptions within details elements flagging rule

### ISSUE THREAD

**Issue by zJag** [IBMa/equal-access#1557]
### Project

a11y checker extension

### Browser

Chrome

### Operating system

MacOS

### Description
When using a `<details>` element that contains a label with a child element in it's content, the label description rule is flagged when the details is closed. When opened, the rule is not flagged.

### Expectation
If the label is accessible when the details element is expanded, it should be accessible when the element is collapsed.

### Steps to reproduce

- Create a details element with whatever summary
- In content add a label with `for` referencing an input element
- Within label content add `<p>label</p>`
- Run test once with the details section collapsed
- Run test again with the details section expanded

CodeSandbox: https://codesandbox.io/s/eloquent-hofstadter-mm8r9n

**Comment by shunguoy** [comment]
triage: when it's closed, it shouldn't require a label because the label and input are not visible.

**Comment by shunguoy** [comment]
see also #1008

**Comment by ErickRenteria** [comment]
Validated
