### ISSUE TITLE
[BUG] CSV report file name results.csv includes date since 3.1.51 so breaks automation

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1563]
From Guillaume Delory

Hi all, was there a breaking change in the CSV report name. It used to be results.csv, and I have the feeling that this commit from June 20th is changing it to have the iso date in it. Seems like the commit made it to 3.1.51 but I don't see anything in the release notes. That breaks our automation, which expects results.csv to be generated. Is there anyway to force the output filename ?

**Comment by ErickRenteria** [comment]
Merged
