### ISSUE TITLE
[Feature]: Need to cross reference to dev technique

### ISSUE THREAD

**Issue by mbgower** [IBMa/equal-access#1570]
### Project

able site

### Description

I was answering a direct question in a slack about generic links by doing a search against our content that gave me a link in the design area. However, I then realized that it did NOT link to the actual implementation details!

> Hi Michael. Can I ask your opinion on something? If I am reviewing content and the CTAs on a series of tiles are all the same, I'll change then so they are specific. Here's an example of copy I have been asked to review (this is before I have reviewed it btw).
![image](https://github.com/IBMa/equal-access/assets/14298245/c604cd44-9621-4408-be28-9497c2cd5824)
Does having a 6 tiles with 'Explore' on them as the CTA have an implication from an accessibility point of view?
Michael Gower: It can be tackled programmatically. Let me know if this helps https://www.ibm.com/able/toolkit/design/content/#link-text
Gemma Fisher: Yes, that does help. Thank you
Michael Gower:I realized we went and failed to the link to the dev technique to support this! https://www.ibm.com/able/toolkit/develop/text-and-non-text/#aria-labelling

Note that the dev topic already cross references the design topic. This raises a concern that other design page topic updates from a few years back may have similarly lost cross references to dev topics

Resolution: 
1. The topic https://www.ibm.com/able/toolkit/design/content/#link-text should cross reference the development topic https://www.ibm.com/able/toolkit/develop/text-and-non-text/#aria-labelling
2. Carry out assessment on some other design topics to confirm they cross-reference the dev topics. The easiest way to do this may be in reverse (look at dev topics, follow links to referenced design topics and confirm there is a pointer back to the dev topic)

**Comment by MHoov** [comment]
Opening on internal board.
