### ISSUE TITLE
[BUG] Review modals on the extension Options Page

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1590]
@tombrunet  commented that the modals on the Options page are not formatted correctly. E.g., the heading size and weight. Here is an example:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdndVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7cc9520af9abc63513f22a664541d7ddb8be5c17/image.png)

@agentcoco could you please review to determine if changes need to be made.

**Comment by drjoho** [comment]
I will use this as a template for the Options modals. WRT the title and the text.
<img width="721" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/7ddc03f5-b60a-4736-bdb6-3f4c761955bd">

**Comment by drjoho** [comment]
Ready for QA.

**Comment by drjoho** [comment]
<img width="1447" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/69028988-c156-4cdd-9f20-6874abf77c90">

**Comment by ErickRenteria** [comment]
@drjoho What is the expected action when user changes the guidelines? 
At this time the user can change the guidelines and the report will show all stored scans with the last guidelines selected. 
Example: User scan 1-3 scans with guidelines: IBM_Accessibility but if the y change the guidelines to scan 3 more pages the report will have a total of 6 scans with the newer guidelines selected. 

Suggestions: We should apply the delete reports if user changes the guiles similar to changing the rules dates.

**Comment by ErickRenteria** [comment]
@drjoho We need to clear report county cache after the user changes the rule date and stored scans are deleted. At this time we keep counting: 
<img width="1289" alt="Screenshot 2023-08-28 at 4 28 22 PM" src="https://github.com/IBMa/equal-access/assets/62436670/dc302037-7900-44bd-b16a-80a644ae81c7">

**Comment by ErickRenteria** [comment]
Not ready
