### ISSUE TITLE
Revisit: element_tabbable_visible - can we tighten scope?

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#1610]
This rule fires some "Needs review" items. Can we identify scenarios where this definitely passes so that we can tighten the scope and trigger fewer "Needs Review" items for this.

**Comment by shunguoy** [comment]
https://w3.ibm.com/#/apps/travel

**Comment by shunguoy** [comment]
requested @tombrunet for review.

**Comment by drjoho** [comment]
@Erick DONE
