### ISSUE TITLE
Revisit: list_markup_review - can we tighten scope?

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#1626]
This rule fires some "Needs review" items. Can we identify scenarios where this definitely passes so that we can tighten the scope and trigger fewer "Needs Review" items for this.

**Comment by shunguoy** [comment]
test case: https://www.ibm.com/us-en

**Comment by shunguoy** [comment]
requested @tombrunet  to review #1861

**Comment by ErickRenteria** [comment]
merged
