### ISSUE TITLE
Revisit: style_before_after_review - can we tighten scope?

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#1637]
This rule fires some "Needs review" items. Can we identify scenarios where this definitely passes so that we can tighten the scope and trigger fewer "Needs Review" items for this.

**Comment by shunguoy** [comment]
after discussion, the rule is turned off, and a new issue will be opened to follow up.  @marcjohlic  @mbgower

**Comment by shunguoy** [comment]
PR #1876  for @tombrunet to review

**Comment by ErickRenteria** [comment]
Validated
