### ISSUE TITLE
Revisit: text_sensory_misuse - can we tighten scope?

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#1641]
This rule fires some "Needs review" items. Can we identify scenarios where this definitely passes so that we can tighten the scope and trigger fewer "Needs Review" items for this.

**Comment by mbgower** [comment]
<img width="1017" alt="image" src="https://github.com/IBMa/equal-access/assets/14298245/798c3586-a3d1-4548-b9da-9bf044875851">

I think there is a possibility to tighten the rule based on the element it appears within. Text in a heading or link is VERY unlikely to be an instruction.
Here the heading/link text "The right thing for the wrong reason" is flagged.

Text in paragraphs: HIGH.
Text in input labels: MED (instructions are not supposed to be in labels, but it happens)
Text in buttons, headings, link: LOW

There are probably other use cases where we could suspect text in an element has lower likelihood for instructions.

**Comment by shunguoy** [comment]
test page: IBM travel expense (4): https://us2.concursolutions.com/home.asp
   ibm.com (1): https://www.ibm.com/us-en

**Comment by shunguoy** [comment]
requested @tombrunet  for review.

**Comment by ErickRenteria** [comment]
validated and merged
