### ISSUE TITLE
Revisit: widget_tabbable_exists - can we tighten scope?

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#1648]
This rule fires some "Needs review" items. Can we identify scenarios where this definitely passes so that we can tighten the scope and trigger fewer "Needs Review" items for this.

**Comment by tombrunet** [comment]
One bug we have on this one can be seen on cloud.ibm.com dealing with submenus.
```
<ul role="menu" tabindex="0">
    <li>
        <ul role="menu">
        ...
```
We are firing on the sub-menu even though it's within the keyboard scope of the parent menu.

**Comment by shunguoy** [comment]
This issue was not in the current release, but during the rule discussion, we found this is closely related to #1606, and we decided to fix them together.

**Comment by MHoov** [comment]
Thanks @shunguoy - @MHoov

**Comment by ErickRenteria** [comment]
Validated and merged
