### ISSUE TITLE
R5.4 Automation for testing

### ISSUE THREAD

**Issue by MHoov** [IBMa/equal-access#1656]
Refer to mural R5.4 _add link_

## Epic Details
- **User Story**: We will be able to catch any bugs before our ed user to provide the best user experience 
- **Playback Demonstration**: This is all backend we can do walk through of the code but we wont be able to show much.  
- **Metric**:  By the stories we add for testing under storybook
- **Comms**:N/A

## What project/section is the Epic for?

- [extension-checker](https://github.com/IBMa/equal-access/issues#workspaces/equal-access-61ae71f9f8b4ec001e136462/board?labels=extension-checker&releases=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvOTQ1MzM)

## Definition of Done

- [ ] Results are added to the Release Mural with a description of what was accomplished, KPIs, etc
- [ ] All content has been reviewed for grammar, spelling, style and technical accuracy
- [ ] All code committed to main branch
- [ ] All unit tests pass (including accessibility)
- [ ] Demo works in staging environment
- [ ] At least one performance metric / monitor constructed

**Comment by marcjohlic** [comment]
@ErickRenteria please update the "Epic Details" in the Description section.
