### ISSUE TITLE
[Feature]: Allow SCs to be mapped based on reason code

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#1663]
Currently, rule mappings to checkpoint are done at the rule level. However, sometimes this should be done at the reason level. For example, if a role is incorrect and the item is a UI component, then it would map it 4.1.2. If it's not a UI component, another SC would be more appropriate.

**Comment by tombrunet** [comment]
Basic mapping is in. Mapping done in ACT and extension (need to test). Need to find other references to the .checkpoints and ensure they still make sense (mostly likely more to do in the reports)

**Comment by tombrunet** [comment]
Things to test:
* [x] Extension requirements report
* [ ] Extension HTML requirements report
* [ ] Extension XLS requirements report
* [ ] Packages HTML requirements report
* [ ] Packages XLS requirements report
* [ ] Rule listing report

**Comment by ErickRenteria** [comment]
Validated
