### ISSUE TITLE
Update scoring panels and summary counts

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1665]
1. Duplicate the ability to show or hide each of the issue types with a checkbox within the respective card.
2. Provide the text boxes for the hidden issues total (at the top) and for each of the Cards when hidden issues are present.

<img width="671" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/d28a154b-6873-47df-8301-a61c947bc543">

**Comment by drjoho** [comment]
Here is the design doc:

<img width="624" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/4a3af7a3-345e-4cc8-9bc1-924cb6c5f096">

**Comment by drjoho** [comment]
Card checkboxes in and issue type icons placed appropriately. Need to work on making the checkboxes behave as the filter menu. Then need to get the show / hide pieces (hidden issues total, and hidden issues for each issue type).
<img width="829" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/70051c4a-d2bc-4d62-a4ee-14d17e1b168f">

**Comment by drjoho** [comment]
Filter checkboxes working
<img width="764" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/e7178bbb-570d-443c-a92d-cc350532b32a">

**Comment by drjoho** [comment]
Ok text content for show / hide on summary
<img width="764" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/b089eedd-fbc2-4646-862d-1516cc1679dd">

**Comment by drjoho** [comment]
Next get the real hidden numbers.

**Comment by ErickRenteria** [comment]
Validated
