### ISSUE TITLE
Enable hide / show checkboxes and wire to hide list

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1667]
Enable all the show / hide enhancements to work across components.
1. Counts in header with the counts in the filter menu
2. Also with counts on the summary page
3. Also checkboxes in the Issue List table

<img width="671" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/aacb8ac4-7c83-4ebd-8c62-0f06ec05e7bc">

1. Update the xls reports to include the View and Filter enhancements
2. Update the xls reports to include the show / hide enhancements

<img width="575" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/cfb3ddd7-6cd3-4b51-a51b-27cb3e36eee1">

**Comment by drjoho** [comment]
Should we break this issue into two issues one for the enhancement and one for updating the xls reports.

**Comment by drjoho** [comment]
We use ignored : https://github.com/IBMa/equal-access/blob/e12455607c1ff9893e4de9c9d1091f11a72879aa/common/module/src/engine/IReport.ts#L74
[IReport.ts](https://github.com/IBMa/equal-access/blob/e12455607c1ff9893e4de9c9d1091f11a72879aa/common/module/src/engine/IReport.ts)
    ignored: boolean
<https://github.com/[IBMa/equal-access](https://github.com/IBMa/equal-access)|IBMa/equal-access>IBMa/equal-access | Added by [GitHub](https://ibm-studios.slack.com/services/B02ABP4DS1G)


Tom Brunet
  [2:25 PM](https://ibm-studios.slack.com/archives/DNWDC0SC8/p1696533948524049)
The way we did this previously was that the extension managed a baseline per URL. So, show/hide would add/remove issues from that baseline. We had a feature (not in current designs) to be able to import/export baselines so that you could share them between the extension and the CI/CD tool.

**Comment by drjoho** [comment]
Types of checkboxes:
Header checkbox: by checking this checkbox all group and issue checkboxes shown in the report will be checked and thus will ignore all issue groups and individual issues that are displayed
Group checkbox: by checking this checkbox we will ignore issues that are descendants along the aria path of this group
Issue checkbox: by checking this checkbox the associated individual issue will be ignored.

**Comment by drjoho** [comment]
Progress - ignore checkboxes in place (next is make them do something)
<img width="784" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/f71f6388-7755-4104-b566-bb563ac6fe44">

**Comment by drjoho** [comment]
Note: need to fix the message wrapping indent...

**Comment by MHoov** [comment]
@ErickRenteria  Final designs in [Mural](https://app.mural.co/invitation/mural/ibm14/1684260151197?sender=alexandra0696&key=02074eb6-44e1-460f-905d-2a91126f9a49) and in [Figma](https://www.figma.com/file/intddqthciXilHQCLWppQ7/a11y-checker?type=design&node-id=428%3A78341&t=3q8PzjFDvf3FKOoj-1).

**Comment by drjoho** [comment]
<img width="1824" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/db102bbb-27a7-48cc-8a09-0cc715c30580">

**Comment by drjoho** [comment]
DONE. Checkboxes wired up.

NEXT: Wire up Filter Hidden, Add Batch toolbar, Add hidden icons
