### ISSUE TITLE
Check WCAG 2.2 Focus not obscured requirement

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#1676]
WCAG 2.2 requires a minimum size for a tabbable target, see details in  [Focus Not Obscured (Minimum) (AA) ](https://www.w3.org/TR/WCAG22/#focus-not-obscured-minimum) and [Understanding Focus Not Obscured (Minimum)](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html).
Also, refer to the team discussion notes.

See HELP in #1679

**Comment by shunguoy** [comment]
dev-1676.  https://ibm.ent.box.com/notes/1320122846312

**Comment by shunguoy** [comment]
PR #1705 for @tombrunet to review

**Comment by MHoov** [comment]
@ErickRenteria please also check that this new rule appears on [Checker Rule Sets](https://www.ibm.com/able/requirements/checker-rule-sets) under a new WCAG 2.2 (A, AA) subtab 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzFVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--622f0c5433f3bf1f10ca4ce75997a8f166cd9a34/image.png)

**Comment by ErickRenteria** [comment]
Under test
