### ISSUE TITLE
<Help content>Check WCAG 2.2 minimum target size

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#1678]
please refer to #1675

WCAG 2.2 requires a minimum size for a tabbable target, see details in [Dragging Movements (AA)](https://www.w3.org/TR/WCAG22/#dragging-movements) and [Understanding Dragging Movements](https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html).
Also, refer to the [team discussion notes](https://ibm.ent.box.com/notes/1304210878893).

**Comment by marcjohlic** [comment]
@philljenkins disregard - this one is a dupe - but do you have an update on #1677
