### ISSUE TITLE
[BUG]: Unable to use the checker in with branch https://github.com/IBMa/equal-access/pull/1594

### ISSUE THREAD

**Issue by ErickRenteria** [IBMa/equal-access#1684]
### Project

extension-checker

### Browser

Chrome

### Operating system

Windows

### Description

The checker seem to have a hard crash as soon as we loaded. This is with branch https://github.com/IBMa/equal-access/pull/1594 and using local build. This is happening under the windows env.  This is not the same behavior with the branch artifact action but unable to test the previews rules sets.  
Please review attachment 
![Screenshot (3)](https://github.com/IBMa/equal-access/assets/62436670/b279573c-1ecf-4d54-a69c-2ebc7ac2e96d)
hment: 

### Steps to reproduce

Build branch in Windows, 
Load checker in chrome 
Review the chrome://extension for error logs
User is unable to see the checker from dev tools

**Comment by shunguoy** [comment]
The error message indicates that the CSP does not allow the use of the eval() method/function in the extension code because 'unsafe-eval' is not allowed in the manifest.json (should be for security reasons).  Therefore, one possible fix is to remove the use of eval() in the extension code.

**Comment by ErickRenteria** [comment]
This issue is also in master:  

`},
	"devtools_page": "devtools.html",
	"background": {
		"service_worker": "background.js"`


```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*".

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*".
```

![Screenshot 2023-09-14 131140](https://github.com/IBMa/equal-access/assets/62436670/686387a3-f91f-4f76-b768-f5afe76aa558)

**Comment by ErickRenteria** [comment]
Additional logs, stack trace too larger to add in git. 
![Screenshot 2023-09-14 131847](https://github.com/IBMa/equal-access/assets/62436670/55aba896-2b0a-4eb9-8e4f-9ba6d3fa6b38)
![Screenshot 2023-09-14 131903](https://github.com/IBMa/equal-access/assets/62436670/b90ca11e-3a96-44aa-a75f-0d9404d0be3a)

**Comment by ErickRenteria** [comment]
This might be related to my local env. The actions are working in the Windows env and we're conduction validation. Closing issue.
