### ISSUE TITLE
Investigation for automation framework with code coverage in jest

### ISSUE THREAD

**Issue by ErickRenteria** [IBMa/equal-access#1697]
We need an automation test framework to test UI components from the checkers UI. The framework needs to be able to be part of our CI/CD and be able to execute with our actions.

**Comment by tombrunet** [comment]
https://github.com/IBMa/equal-access/pull/1715

**Comment by MHoov** [comment]
Last update was 12 days ago @ErickRenteria @tombrunet

**Comment by ErickRenteria** [comment]
Framework created and first test cases are working for HeaderSection
