### ISSUE TITLE
[Extension]: On first run, scan just spins

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#17]
Background console is showing a tabId of -1, causing the first scan to just spin. Adding a console log to startScan seems to make it stop, so there's some race condition involved.

Temporary dev work around - close devtools and re-open and the issue seems to clear itself.

**Comment by Etheryte** [comment]
Not sure if this has made it to the last release, the version in the Chrome webstore still seems to have either this issue or a similar one that manifests the same way: the first scan is simply stuck on spinning, closing and reopening devtools seems to solve the issue.

**Comment by tombrunet** [comment]
This particular issue was resolved and deployed, but will re-open while we investigate.

**Comment by tombrunet** [comment]
There was an issue with a particular rule that we deployed today that would cause a spin due to a rule exception. That has now been fixed. Please re-open this if you are still encountering this issue.
