### ISSUE TITLE
QA ticket testing summary for sprint: 3 release 5.4

### ISSUE THREAD

**Issue by ErickRenteria** [IBMa/equal-access#1708]
The following is summary of the tickets tested  for this release/sprint. 
This also provides a level of testing: 

automated test:
manual test:
SR test:
verified in production:
new automated test created, if applicable
Log building the releases and pushing those to production (browser stores, etc)

* [1681 <help content> Update SC 4.1.1 requirements and references in the rule help](https://github.com/IBMa/equal-access/issues/1681) - automated test, manual test LB, Code review, Code modification, this will be going to prod. 

* [1680 Remapping SC 4.1.1 in the engine rules](https://github.com/IBMa/equal-access/issues/1680) - automated test, manual test LB, Code review, Code modification, this will be going to prod. 

* [1600 BUG Update Cypress README's for Cypress 12](https://github.com/IBMa/equal-access/issues/1600) - Code review, Code modification, this will be going to prod. 

* [Remove 4.1.1 Parsing from the existing ACS Checklist templates ](https://github.ibm.com/IBMa/E2E/issues/5926) -automated test, manual test LB, Code review,  this is in prod. 

* [ACS ACR - Updates to 4.1.1 Parsing to always indicate supports](https://github.ibm.com/IBMa/E2E/issues/5925) automated test, manual test LB, Code review,  this is in prod. 

* [Remove Watson Health BU from ACS dashboards](https://github.ibm.com/IBMa/E2E/issues/5893) automated test, manual test, Code review,  tested in multiple env, in production.

* [New metric for ACS Dashboard - BU view](https://github.ibm.com/IBMa/E2E/issues/5719) -  automated test, manual test, Code review,  tested in multiple env, in production.

* [Confirm toolkit checklist spreadsheets match ACS](https://github.ibm.com/IBMa/E2E/issues/5823) - automated test, manual test, Code review,  tested in multiple env, in production.

* [Updating master with lates for production](https://github.ibm.com/IBMa/ibm.com-able-v2/pull/886) - automated test, manual test

* [Able production update ](https://github.ibm.com/IBMa/ibm.com-able-v2/pull/891) automated test, manual test

* [ACS production update ](https://github.ibm.com/IBMa/acs-checklist/pull/58) - automated test, manual test

* [ ACS Reporting productions update ](https://github.ibm.com/IBMa/acs-reporting/pull/80) - manual test, multiple env testing 

* [Tools page: Apply new layout for dev portion of Tools page](https://github.ibm.com/IBMa/E2E/issues/5855) - automated test, manual test, Code review,  tested in multiple env, in production.

*  Security training 
*  [Catalyze Our Leaders program](https://w3.ibm.com/w3publisher/software-zone/people/catalyze-our-leaders)

**Comment by MHoov** [comment]
Looks great @ErickRenteria !
