### ISSUE TITLE
Add archive (show/hide) section to Reports: Data 

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1709]
_(Need design, [Internal issue 5950](https://github.ibm.com/IBMa/E2E/issues/5950) still in our backlog)_

**Comment by drjoho** [comment]
Design showing the archive section in the HTML Report
<img width="1311" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/737583ac-d36c-4392-bb3d-e6ee1a874c44">

**Comment by drjoho** [comment]
@agentcoco There is not a design for the spreadsheet report that includes the archives.

**Comment by MHoov** [comment]
Created design issue on internal board ([5950](https://github.ibm.com/IBMa/E2E/issues/5950))

**Comment by MHoov** [comment]
@drjoho chatting with @tombrunet regarding the Excel report. He doesn't think a design is needed.  Let me know if the description below is sufficient. Thanks

> just need to change the column that says "Violation" to "Hidden violation" and pop it at the bottom.

**Comment by marcjohlic** [comment]
@drjoho Here are the updated designs for adding "Hidden" to the Excel spreadsheet reports.  

Note: this is not currently in Figma, but Jess reviewed and gave a thumbs up


## Updated designs for the Excel report:

#### Overview worksheet
- [ ] "Hidden" summary column added after "Recommendations" (Column E)
- [ ] "Accessibility Scan Report" and "Summary" rows (rows 1 and 11) have their purple background extend to include column E

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNURnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5045dcb3cb27cf7d43375695c1854f52b46dd74/image.png)

#### Scan summary worksheet
- [ ] Insert a "Hidden" column after "Recommendations" and before "% elements without violations".  Should become Column H

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1RnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae77e095e2847714500eb7affa785efde4a57508/image.png)


#### Issue summary worksheet
- [ ] Add "Hidden" section/rows after "Recommendation" section/rows for each Level

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzdnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--816abb6807fadcc5a89ac4a38668f36625eb6c4c/image.png)


#### Issues worksheet
- [ ] Issue types of:  "Hidden Violation", "Hidden Needs Review", and "Hidden Recommendation" should show in Column E - Issue Type
Note:  That we're prepending "Hidden" to the issue types for this worksheet

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC9nQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5255f372524f2c2548e1d80ebcc44cffd22c0f00/image.png)


#### Definition of fields worksheet
- [ ] Add "Hidden" and definition after "Recommendations" (Row 11)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVhnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e032161eff280b16f913017ee08261ada47f4999/image.png)

**Comment by drjoho** [comment]
chatting with Tom regarding the Excel report. He doesn't think a design is needed. The description of what to do is below:

just need to change the column that says "Violation" to "Hidden violation" and pop it at the bottom.

**Comment by drjoho** [comment]
Yes these are in the issue.

From: Marc Johlic ***@***.***>
Date: Thursday, November 16, 2023 at 10:50 AM
To: IBMa/equal-access ***@***.***>
Cc: Josiah Hoskins ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [IBMa/equal-access] Add archive (show/hide) section to Reports (Issue #1709)
@drjoho Here are the updated designs for adding "Hidden" to the Excel spreadsheet reports. Note: this is not currently in Figma, but Jess reviewed and gave a thumbs up Updated designs for the Excel report: Overview worksheet "Hidden" summary
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
    Report Suspicious  <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2U-u7PHVaVMyko-QWytv5Ns1j-XBWaWFrmp0vfAMmPwjU53Axf5zzXkjSPvvVKy3wflZeW076zx3EY-1IIKXw3mKtb-AEadvsfC4q0Kx2A$>   ‌
ZjQcmQRYFpfptBannerEnd

@drjoho<https://github.com/drjoho> Here are the updated designs for adding "Hidden" to the Excel spreadsheet reports.

Note: this is not currently in Figma, but Jess reviewed and gave a thumbs up

Updated designs for the Excel report:
Overview worksheet

  *   "Hidden" summary column added after "Recommendations" (Column E)
  *   "Accessibility Scan Report" and "Summary" rows (rows 1 and 11) have their purple background extend to include column E

Private Zenhub Image<https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNURnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5045dcb3cb27cf7d43375695c1854f52b46dd74/image.png>

Scan summary worksheet

  *   Insert a "Hidden" column after "Recommendations" and before "% elements without violations". Should become Column H

Private Zenhub Image<https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1RnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae77e095e2847714500eb7affa785efde4a57508/image.png>

Issue summary worksheet

  *   Add "Hidden" section/rows after "Recommendation" section/rows for each Level

Private Zenhub Image<https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzdnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--816abb6807fadcc5a89ac4a38668f36625eb6c4c/image.png>

Issues worksheet

  *   Issue types of: "Hidden Violation", "Hidden Needs Review", and "Hidden Recommendation" should show in Column E - Issue Type
Note: That we're prepending "Hidden" to the issue types for this worksheet

Private Zenhub Image<https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC9nQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5255f372524f2c2548e1d80ebcc44cffd22c0f00/image.png>

Definition of fields worksheet

  *   Add "Hidden" and definition after "Recommendations" (Row 11)

Private Zenhub Image<https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVhnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e032161eff280b16f913017ee08261ada47f4999/image.png>

**Comment by drjoho** [comment]
Waiting on Test to clear all show / hide branch to build off of...

**Comment by drjoho** [comment]
Progress: Hidden issue data for each row now stored with the other stored scan data.

**Comment by drjoho** [comment]
Progress: Overview Sheet

<img width="1311" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/07670c88-3034-4971-b308-fc5f8e51b119">

**Comment by drjoho** [comment]
Progress: Scan Summary Sheet

<img width="1311" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/412ab09d-998a-4da8-9251-1567f830ff13">
