### ISSUE TITLE
[BUG]: Confirm that contrast rule properly handles non-latin fonts

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#1735]
### Project

accessibility-checker-engine

### Browser

Chrome

### Operating system

MacOS

### Description

See https://github.com/act-rules/act-rules.github.io/pull/2121/files

### Steps to reproduce

See above

**Comment by tombrunet** [comment]
See https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html (search for "CJK" in notes)

**Comment by shunguoy** [comment]
requested @tombrunet for review.

**Comment by ErickRenteria** [comment]
Validated 
<img width="1421" alt="Screenshot 2024-04-08 at 8 34 46 PM" src="https://github.com/IBMa/equal-access/assets/62436670/09296967-333d-4321-83bb-d0d4d81947c3">
