### ISSUE TITLE
[BUG]: Error parsing markdown

### ISSUE THREAD

**Issue by zwiastunsw** [IBMa/equal-access#1754]
### Project

accessibility-checker-engine

### Browser

Chrome, Firefox

### Operating system

Windows

### Description

In the detailed error report window, pieces of content are not formatted correctly. Applies to:
- code fragments 
- list elements
![equalaccess](https://github.com/IBMa/equal-access/assets/29527200/9bbd7954-b2fe-495f-9151-fecca5d5add7)
(screnshot: fused from 2 parts)

### Steps to reproduce

Perform any test
View a specific error report

**Comment by zwiastunsw** [comment]
After 4 days (I experienced the problem on Saturday, 17 November), today everything is back to normal. It is OK. I am pleased, although I do not understand. The issues can be closed.

**Comment by shunguoy** [comment]
triage: after reloading, the issue was resolved. Thanks.
