### ISSUE TITLE
Correct Counts with the addition of Show/Hide count, Small UI corrections

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1756]
For the counts below:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzRNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf3584f87dcf2af7793af4b98bdcd924620e0112/image.png)

When there are hide counts they need to be subtracted from the correlated V, NR, R counts.

**Comment by ErickRenteria** [comment]
Validated
