### ISSUE TITLE
[BUG]: input_autocomplete_valid fails for ACT pass testcase

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#1757]
### Project

accessibility-checker-engine

### Description

Per ACT, this testcase should not trigger `input_autocomplete_valid`
https://www.w3.org/WAI/content-assets/wcag-act-rules/testcases/73f2c2/efcd5df49b39506dac34a310f4b8bc0df71716d3.html

### Steps to reproduce

See description

**Comment by shunguoy** [comment]
PR #1879 for review by @tombrunet

**Comment by ErickRenteria** [comment]
@shunguoy the testcase provide by Tom is working correctly : https://www.w3.org/WAI/content-assets/wcag-act-rules/testcases/73f2c2/efcd5df49b39506dac34a310f4b8bc0df71716d3.html This url does not trigger the autocomplete but the testcase you provide I see no fix. test/v2/checker/accessibility/rules/input_autocomplete_valid_ruleunit/act-pass.html. 
I'm pushing this to master but you might want to check your testcase.
