### ISSUE TITLE
[BUG]: Unable to filter hidden items, no hidden items are showing 

### ISSUE THREAD

**Issue by ErickRenteria** [IBMa/equal-access#1767]
### Project

extension-checker

### Browser

Chrome

### Operating system

MacOS

### Description

When we hide items and them filter by hidden items, nothing is showing up. 
<img width="974" alt="Screenshot 2023-11-30 at 12 30 59 PM" src="https://github.com/IBMa/equal-access/assets/62436670/0f53fb4d-685e-4271-aca9-8f598bc75b20">

### Steps to reproduce

Conduct a scan 
Select several items from the list and mark them as hide. 
Select the filter options and only select hidden 
#

**Comment by drjoho** [comment]
So the idea is that Hidden just controls hidden issues. So if Hidden is checked the hidden will show irrespective of the state of the Violations, Needs Review, or Recommendation.

**Comment by drjoho** [comment]
Have gotten all Marc's behavior in. There is one small issue with coming back from the Show action. Will attend to that and a couple of dark mode issues today.

**Comment by drjoho** [comment]
All issues except have been done. Ready for review.

**Comment by ErickRenteria** [comment]
Tested on Chrome, FF, and Edge browser in the macOS. No major issue found 
Tested on Chrome and FF in the windows env and it looks good. Feature ready to go. 
Validated
