### ISSUE TITLE
[FEATURE]: Show / hide for Keyboard mode

### ISSUE THREAD

**Issue by ErickRenteria** [IBMa/equal-access#1768]
### Project

extension-checker

### Browser

Chrome

### Operating system

MacOS

### Description

When we have no hidden items and select the hidden filter, we get two urls within this message that have not action: 
No issues detected for the chosen filter criteria. To see all issues, _turn off focus view,_ _select all issue types_, and do not filter hidden issues.
<img width="1518" alt="Screenshot 2023-11-30 at 12 34 33 PM" src="https://github.com/IBMa/equal-access/assets/62436670/db646778-858d-4d12-b511-c6db3a2b1f9d">

<img width="622" alt="Screenshot 2023-11-30 at 1 46 27 PM" src="https://github.com/IBMa/equal-access/assets/62436670/f8dfa328-a4e5-49f0-9e2f-8179cddd4d1a">

### Steps to reproduce

Select the hidden filter: 
#

**Comment by MHoov** [comment]
Also in dark mode the 'eye' icon is not appearing above the table NOR in the filter list<img width="268" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzBzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55e4f7bbaf54ec0fd3c31151d3b8d94d0ebfc537/image.png" alt="image.png" />

**Comment by drjoho** [comment]
@marcjohlic @tombrunet @ErickRenteria @agentcoco There was no UI or UX changes to the Keyboard mode. 
If I get the drift here the show / hide functionality should work in keyboard mode and so I need to see what the UX is for this functionality.
From a UI perspective the appropriate toolbars need to be in place.

**Comment by drjoho** [comment]
Show / Hide will not be in Keyboard mode for the first release

**Comment by ErickRenteria** [comment]
Done
