### ISSUE TITLE
[BUG]: Filter is not behaving correctly after using it for some time - under investigation

### ISSUE THREAD

**Issue by ErickRenteria** [IBMa/equal-access#1779]
### Project

extension-checker

### Browser

Chrome

### Operating system

MacOS

### Description

After using the new filtering feature the fictionality stops working correctly. I encounter this several time but still trying to find the trigger. Please review video 

https://ibm.box.com/s/qugpbf2h7jpep3sbhg3mkp9w4omadb48

### Steps to reproduce

Under investigation

**Comment by drjoho** [comment]
The filtering / show / hide is working correctly wrt the reported numbers:
1. When filtering the number for V, NR, and R do not change nor does the total.
2. When using show / hide the numbers for V, NR, R, H and total change to reflect the hidden issues.
So this was the way it was designed and the way it works.

**Comment by ErickRenteria** [comment]
As design.
