### ISSUE TITLE
[BUG]: KPIs data is missing from the summary report view 

### ISSUE THREAD

**Issue by ErickRenteria** [IBMa/equal-access#1780]
### Project

extension-checker

### Browser

Chrome

### Operating system

MacOS

### Description

Some data is missing from the summary report 

### Steps to reproduce

Open the summary report after a scan and select and item from the list: 
<img width="984" alt="Screenshot 2024-01-04 at 9 03 20 PM" src="https://github.com/IBMa/equal-access/assets/62436670/33b75283-cd06-4176-b0b4-6f174ee34ea5">

**Comment by drjoho** [comment]
Fixed
<img width="1383" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/3b74fe15-6843-4ab8-8947-59940d84c02b">

**Comment by ErickRenteria** [comment]
Validated
