### ISSUE TITLE
[BUG]: New. hide feature a11y tab navigation issues

### ISSUE THREAD

**Issue by ErickRenteria** [IBMa/equal-access#1781]
### Project

extension-checker

### Browser

Chrome

### Operating system

MacOS

### Description

The new hide feature has several issues with keyboard navigations: 
1. Unable to select from the summary total from the UI
2. Unable to select Lean more under the results list 

### Steps to reproduce

Conduct a scan
Navigate the UI with keyboard 
<img width="997" alt="Screenshot 2024-01-08 at 12 55 30 PM" src="https://github.com/IBMa/equal-access/assets/62436670/0d884d6f-54a4-49f4-9082-49a06887ecfb">

**Comment by drjoho** [comment]
@ErickRenteria have reproduced issue. Will check out what the problem is...

**Comment by ErickRenteria** [comment]
Validated with https://github.com/IBMa/equal-access/pull/1783
