### ISSUE TITLE
[BUG]: Filter bar not shown after going to summary page and exercising filter checkboxes and then closing

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1800]
### Project

extension-checker

### Browser

Chrome, Safari, Firefox

### Operating system

MacOS

### Description

Filter bar not shown after going to summary page and exercising filter checkboxes and then closing

### Steps to reproduce

Filter bar not shown after going to summary page and exercising filter checkboxes and then closing

**Comment by ErickRenteria** [comment]
<img width="914" alt="Screenshot 2024-01-16 at 12 49 07 PM" src="https://github.com/IBMa/equal-access/assets/62436670/faf8017d-9e8f-4474-9e93-b1475a3bc7e6">

**Comment by drjoho** [comment]
The bug was found by Eric and shown to me at 12:30pm today in a reproducible form. After working with what Eric gave me I was able to determine the one action that causes the bug. I will demonstrate:

Here is the checker with some issues checked:
<img width="1682" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/72ffbe9e-f87a-446b-83cb-d745f864df4e">

Now change the checkbox in the Needs Review Tile:
<img width="1682" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/82d7d8bb-15e9-4d33-8e9c-679bb7523dc4">

The checked issues are unchecked and the Filter Toolbar is not visible. What happened is that the checked issues are unchecked and yet neither Hide or Cancel were pressed by the user. So the Blue Toolbar is confused and disappears (moves up 2 rem) without setting the onFilterShown state to true so the Filter Toolbar is not available. I have been working for hours to try to determine how the Needs review Tile is unchecking the issues to hide. I will keep at it and hopefully will have something in the morning.

**Comment by drjoho** [comment]
Ok, have figured it out. When the filters are activated they remove the issues from reportIssues variable in reportTreeGrid. So for example if you check the "Needs review" checkbox in either the Filter menu or the Summary Tile checkboxes the issues with the issue.value resolving to "Needs review" are removed from reportIssues. So if you have checked any of the "Needs review" rows they are gone from the rows that are checked. The same with the other LevelFilters. If you have checked both Needs Review and Violations and filter Needs review you are ok as there are Violations left checked. It is easier to see with a demo. So from a design perspective there are two solutions that I see. One would be to disable the Summary Tile checkboxes if there are checked rows. Or when you check a summary tile checkbox check to see if any of that Level have checked rows and if so set the filterShown state in reportSection. We can decide in the morning which is less confusing to the user.

**Comment by MHoov** [comment]
@drjoho thanks for figuring that out. Please schedule a call for us to see a demo and discuss. Would like to have both designers attend and Tom. Thanks!

**Comment by drjoho** [comment]
The text I was given by design is:
Select or deselect checkboxes to filter issues in the Checker view
<img width="831" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/b256684b-7273-4d65-8c3a-cda191c9cd55">

**Comment by drjoho** [comment]
Missing Filter Toolbar fixed with an assist from Tom. Branch is joho-FilterBarDisappears-1800 will make PR

**Comment by ErickRenteria** [comment]
Validated
