### ISSUE TITLE
[BUG]: KCM is not starting up with the master branch 

### ISSUE THREAD

**Issue by ErickRenteria** [IBMa/equal-access#1807]
### Project

cypress-accessibility-checker

### Browser

Chrome

### Operating system

MacOS

### Description

When ever we select the KCM button, the kcm is not coming up. 

### Steps to reproduce

Conduct a scan 
select the KCM button

**Comment by drjoho** [comment]
OK Keyboard mode working fine locally

<img width="959" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/f34acb51-ca0c-4a18-9089-97935258846f">

**Comment by drjoho** [comment]
Now going to check Action

**Comment by drjoho** [comment]
Ok here is the result from the latest master action:

<img width="959" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/93ae67d4-a753-404e-ac4b-184bdd3fea02">

**Comment by drjoho** [comment]
@ErickRenteria cannot reproduce.

**Comment by ErickRenteria** [comment]
Unable to reproduce this AM. Closing issue.
