### ISSUE TITLE
R6.1 Case Studies to Support promoting Checker to IBM Stack

### ISSUE THREAD

**Issue by MHoov** [IBMa/equal-access#1809]
## Epic Details
- **Hill**: We will perform case studies to explore the usefulness of the Checker (both the Chrome extension and the Automated Checker) to provide IBM products the accessibility capabilities to excel in the marketplace.
- **Playback Demonstration**:  Three case studies supporting the Checker being promoted to the IBM Stack
- **Metric**:  Cost savings and adoption
- **Comms**:  We will report to IBM Leadership.

## What project/section is the Epic for?

- [checker](https://github.ibm.com/IBMa/E2E/issues#workspaces/end-to-end-overview-5c90ee20e000f050ae43c45e/board?labels=checker%20-%20internal%20only)

## Definition of Done

- [ ] Results are added to the Release Mural with a description of what was accomplished, KPIs, etc
- [ ] All content has been reviewed for grammar, spelling, style and technical accuracy
- [ ] All code committed to main branch
- [ ] All unit tests pass (including accessibility)
- [ ] Demo works in staging environment
- [ ] At least one performance metric / monitor constructed

**Comment by drjoho** [comment]
Moved to internal board.
