### ISSUE TITLE
Passing Rule is missing from the json and HTML report.

### ISSUE THREAD

**Issue by yogesh-arya** [IBMa/equal-access#1812]
### Discussed in https://github.com/IBMa/equal-access/discussions/1811

<div type='discussions-op-text'>

<sup>Originally posted by **yogesh-arya** January 23, 2024</sup>
I am generating a report for an url.
Where I checked some rules manually which are passing according to descriptions. 
But they are missing in report. 
For example 
                  Rule ID 1.2.1  -   Audio-only and Video-only (Prerecorded) (A)

If a rule is completely passed will it not visible in json report also .
Because in my json if rule level is 'pass' thant it containing "violation" with "pass" also in value.

</div>

**Comment by tombrunet** [comment]
It seems you're confusing the concept of rule and checkpoint. 1.2.1 is a checkpoint and not a rule. Our tools run rules that test specific aspects of a checkpoint, but they do not tell you if you pass an entire checkpoint. A violation of a rule would tell you that you fail an aspect of a checkpoint, but a pass just tells you that you pass that aspect of it, not the checkpoint as a whole. For a list of rules that we execute for each checkpoint, see https://www.ibm.com/able/requirements/checker-rule-sets. The larger verification process is described  at https://www.ibm.com/able/toolkit/verify/overview. Automated tools are just the first step.

For full information regarding 1.2.1 and the related considerations, see https://www.ibm.com/able/requirements/requirements/?version=v7_2#1_2_1
