### ISSUE TITLE
RE: IBM CLOUD PREP APP Study Guide Quizzes & Certigication question[A11y_Bug]: 

### ISSUE THREAD

**Issue by Tgmertens** [IBMa/equal-access#1815]
### Project

other

### Automated testing tool and ruleset

https://ibm-cloud-prep.yourlearning.ibm.com/savedList

### Assistive technology

NO

### Description

RE: IBM CLOUD PREP APP Study Guide Quizzes & Certification questions, in order to delete previously studied questions, only 1 can be deleted at a time, we can add a box place a checkmark as to the one to delete push a submit button and the chosen will be deleted saving time.

### Steps to reproduce

https://ibm-cloud-prep.yourlearning.ibm.com/savedList
click a starred item to delete
however only 1 can be deleted at a time

**Comment by Tgmertens** [comment]
All browsers

**Comment by tombrunet** [comment]
@Tgmertens This repo is for the IBM Accessibility Equal Access tools, and the related toolkit at https://www.ibm.com/able/. You might try https://www.ibm.com/mysupport/s/?language=en_US
