### ISSUE TITLE
[BUG]: When the checker window gets narrow, the text/icons overlap 

### ISSUE THREAD

**Issue by ErickRenteria** [IBMa/equal-access#1830]
### Project

extension-checker

### Browser

Chrome

### Operating system

MacOS

### Description

* Toolbar does not reflow
* When ever we narrow the checker window, the text and icons for the counts overlap each other.  

### Steps to reproduce

Open the checker. 
Narrow the window 
review the UI. 
<img width="453" alt="Screenshot 2024-02-06 at 12 00 20 PM" src="https://github.com/IBMa/equal-access/assets/62436670/e9ec9c82-d709-4a3f-ab39-7ae42fc0f2e8">
<img width="1628" alt="Screenshot 2024-02-06 at 12 02 48 PM" src="https://github.com/IBMa/equal-access/assets/62436670/90416f99-2997-45c2-95ee-20f1bd1e0eb6">

**Comment by marcjohlic** [comment]
Will be worked in conjunction with #1819

**Comment by drjoho** [comment]
Definitions sheet redone:
<img width="1302" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/077d58de-be3c-4e19-b733-c33ed16899d6">

**Comment by drjoho** [comment]
New scan section reflow:
<img width="682" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/e0c5a9be-bf07-49cb-9134-df4258c354d8">

**Comment by drjoho** [comment]
And here is ultra narrow:
<img width="682" alt="image" src="https://github.com/IBMa/equal-access/assets/64442976/f0d66d82-acd3-494d-8f78-765994f4795e">

**Comment by drjoho** [comment]
@ErickRenteria Conflicts fixed.
