### ISSUE TITLE
npm- Unable to Generate xlsx file (and csv). Able to generate html, json

### ISSUE THREAD

**Issue by Adr0it** [IBMa/equal-access#1837]
### Discussed in https://github.com/IBMa/equal-access/discussions/1836

<div type='discussions-op-text'>

<sup>Originally posted by **Adr0it** February 10, 2024</sup>
Hello, I'm not the best programmer, so I may be making obvious mistake somewhere, but I'm trying to generate an excel report with your npm package. Unfortunately, no xlsx is being generated. The same goes for csv. The only thing that generates is the corresponding html and json. Here are pictures.
![image](https://github.com/IBMa/equal-access/assets/46908309/2923cc32-c506-4cf2-a63c-8387b37b9019)
![image](https://github.com/IBMa/equal-access/assets/46908309/83ced61d-4fea-4667-b42a-7e345264934b)
![image](https://github.com/IBMa/equal-access/assets/46908309/72fe6062-40ec-4bcd-ac2f-f3a96732dd9a)
![image](https://github.com/IBMa/equal-access/assets/46908309/92d4ed8f-d9d2-463d-8702-f260f5e0b352)

I'm trying to generate the Excel file that is generated by the Chrome extension, except programmatically.</div>

**Comment by shunguoy** [comment]
@Adr0it  if you click "Export XLS" from the Chrome extension,  you should get an HTML file for the report and an Excel file for the details in your local machine (default is in the Download folder). Can you try again and let us know the result?  thanks.
![Screenshot 2024-02-12 at 11 01 09 AM](https://github.com/IBMa/equal-access/assets/18539498/ba9d37ea-4a2e-4a73-900d-ad3292131305)

**Comment by tombrunet** [comment]
@Adr0it Just for clarity, you're running in plain Node and not within a test framework like jest, mocha, cucumber, ....?

**Comment by Adr0it** [comment]
> @Adr0it Just for clarity, you're running in plain Node and not within a test framework like jest, mocha, cucumber, ....?

Yes, regular NodeJS in VS Code.

**Comment by isaly2** [comment]
Ok, I see the issue. When I passed a "Page" object into the method using Puppeteer, it did generate an Excel file. However, I was using axios package to just get html content as a string or something, and it wasn't working, and I didn't know why.

**Comment by Adr0it** [comment]
Ok, I see the issue. When I passed a "Page" object into the method using Puppeteer, it did generate an Excel file. However, I was using axios package to just get html content as a string or something, and it wasn't working, and I didn't know why.

**Comment by shunguoy** [comment]
requested @tombrunet for review.
