### ISSUE TITLE
[BUG]: Small Changes to Reports

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#1853]
1. Overview Sheet - Total Issues -> Issues
2. Summary Sheet - Number of Issues -> Issues
3. Summary Sheet - Drop Total from Row 3 header
4. Stored Scan Menu - Remove first entry
5. Change Download to Export
6. Report button - Export XLS to Export scan

**Comment by drjoho** [comment]
@ErickRenteria ready for test. This is a very simple issue: changes in text and remove one menu item.

**Comment by ErickRenteria** [comment]
Validated
