### ISSUE TITLE
[BUG]: Missing `datetime-local` for label_ref_valid

### ISSUE THREAD

**Issue by nmerget** [IBMa/equal-access#1910]
### Project

accessibility-checker for Node

### Browser

Chrome

### Operating system

Windows

### Description

The [`label_ref_valid.ts`](https://github.com/IBMa/equal-access/blob/f048e794d71246220789e6f76fbcc20135f79179/accessibility-checker-engine/src/v4/rules/label_ref_valid.ts#L76) not checking for type [`datetime-local`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local).

Should be solved easily by adding `type == "datetime-local" ||`

### Steps to reproduce

[label_issue.zip](https://github.com/IBMa/equal-access/files/15335331/label_issue.zip)

This is the index.html created by playwright. It's a little bit too much, but reflects the output of the the description.

For an easy test this would work as well I guess:

````
<label for="test">Test</label><input id="test" type="datetime-local"/>
````

**Comment by shunguoy** [comment]
This is a quick-fix item, so place it on the current release.
