### ISSUE TITLE
chore(engine): Create archive build script that has a pull master to ensure builds are updated

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#1937]
When building archives, this is done with the local code. If the local doesn't have the latest pull, then the archive can be built with old code. We should be doing this as part of the automated build process.

**Comment by Dixusza** [comment]
Sadly demise of OWNER

**Comment by Dixusza** [comment]
D.Y. Patil

**Comment by Dixusza** [comment]
![20240416_023855](https://github.com/IBMa/equal-access/assets/171574078/77749253-d175-4ba8-a20e-b29943f3b3c8)
Kadamwadi Road.

**Comment by Dixusza** [comment]
![20240415_233841](https://github.com/IBMa/equal-access/assets/171574078/a4d4844f-fd85-42b0-84bd-461061ce12fa)
Ramabhai Ambedkar Road.
