### ISSUE TITLE
[Question]: Bounds with negative values

### ISSUE THREAD

**Issue by EvilKarter** [IBMa/equal-access#1940]
### Project

accessibility-checker for Node

### Description

I have received negative values in bounds, which I find very surprising
`"bounds":{"left":0,"top":-26250,"height":0,"width":0}`
I know there is an [example of an response to find in the docs ](https://github.com/IBMa/equal-access/blob/master/accessibility-checker/src/README.md). But there is not explained which range the values can have.
Is it intentional that negative values are returned for the bounds? if so, what is the background here?

**Comment by shunguoy** [comment]
@EvilKarter  can you please provide a test case or an example page for the issue?  Thanks.

**Comment by EvilKarter** [comment]
my config yml
```
ruleArchive: versioned
policies:
    - IBM_Accessibility
failLevels:
    - violation
    - potentialviolation
reportLevels:
    - violation
    - potentialviolation
    - recommendation
    - potentialrecommendation
    - manual
    - pass
outputFormat: json
outputFolder: /path/to/my/output/folder/
outputFilenameTimestamp: false
``` 
I scanned the [mars demo page ](https://dequeuniversity.com/demo/mars/) from the [Deque University](https://dequeuniversity.com/) 

and my response contains something like this
```
      {
         "ruleId":"blink_css_review",
         "value":[
            "VIOLATION",
            "PASS"
         ],
         "path":{
            "dom":"/html[1]/body[1]/div[3]/div[1]",
            "aria":"/document[1]"
         },
         "ruleTime":0,
         "reasonId":"Pass_0",
         "message":"Rule Passed",
         "messageArgs":[],
         "apiArgs":[],
         "bounds":{
            "left":0,
            "top":-10000,
            "height":0,
            "width":0
         },
         "snippet":"<div style=\"position: absolute; top: -10000px; height: 0px; width: 0px;\">",
         "category":"Accessibility",
         "ignored":false,
         "level":"pass",
         "help":"https://able.ibm.com/rules/archives/2024.06.17/doc/en-US/blink_css_review.html#%7B%22message%22%3A%22Rule%20Passed%22%2C%22snippet%22%3A%22%3Cdiv%20style%3D%5C%22position%3A%20absolute%3B%20top%3A%20-10000px%3B%20height%3A%200px%3B%20width%3A%200px%3B%5C%22%3E%22%2C%22value%22%3A%5B%22VIOLATION%22%2C%22PASS%22%5D%2C%22reasonId%22%3A%22Pass_0%22%2C%22ruleId%22%3A%22blink_css_review%22%2C%22msgArgs%22%3A%5B%5D%7D"
      },
``` 
@shunguoy is this enough or do you need more details?

**Comment by shunguoy** [comment]
@EvilKarter  The bounds define the left(x), top(y), width, and height of an element in pixels. The left and top are from the element style specified by the developers or by default, and the width and height are calculated from [getBoundingClientRect](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) adjusted with device pixel ratio. 
  The negative value (top) in the bounds is from the element's style:
`<div style=\"position: absolute; top: -10000px; height: 0px; width: 0px;\">`

Hopefully, this addresses your concern.  If yes, please go ahead to close the issue.
