### ISSUE TITLE
[BUG]: In Firefox, selecting "learn more" only opens an elements first issue. 

### ISSUE THREAD

**Issue by YoshiJL** [IBMa/equal-access#2002]
### Project

accessibility-checker-engine, extension-checker

### Browser

Firefox

### Operating system

Windows

### Description

When an element has multiple issues, selecting "Learn more" will only open the first issue, even if the issue you selected isn't the first one in the list. 

### Steps to reproduce

1. Complete a scan.
2. Find an element that has multiple issues. 
3. Go to an element's second issue. 
4. Select "Learn more".
5. The panel that appears shows information for the first issue.

**Comment by tombrunet** [comment]
Confirmed in Firefox. Note that this works fine on Chrome, so it's only failing on Firefox.

**Comment by drjoho** [comment]
@nam-singh Note that if you click the issue if you have enough room on the screen the Help / Learn more will show up correctly on any issue. The problem only occurs when you actually click the Learn more link.

One file to check is reportTreeGrid.tsx the onClick for the Learn more is as follows:
onClick={() => {
       this.onRow(group, thisIssue);
       ReportTreeGrid.devtoolsAppController.setSecondaryView("help");
       ReportTreeGrid.devtoolsAppController.openSecondary(`#${rowId} a`);
}}
