### ISSUE TITLE
HTML Report Card Changes, and View and Filter menu changes

### ISSUE THREAD

**Issue by nam-singh** [IBMa/equal-access#2024]
Items on this ticket: 

- Worked on the summary cards css and formatting making it similar to extension with checkboxes

- Worked on icons colors, size and position 

- Replaced Requirement and rules tab with filters and added additional filter for element role
- Added filter for Need Review, Recommendations and Violations

<img width="1056" alt="image" src="https://github.com/user-attachments/assets/72f8c25a-c0ea-4b4a-901e-d6743cb1fcf6">

**Comment by nam-singh** [comment]
- Worked on the summary cards css and formatting

- Worked on icons

- Fixed bug in ACReporterHTML file so that changes made in react-report is reflected in generated report

- Worked on group filter of roles,requirement,rules

**Comment by MHoov** [comment]
@nam-singh re-opening and putting in Ready for QA until the PR is closed. Thanks !

**Comment by ErickRenteria** [comment]
Under test

**Comment by ErickRenteria** [comment]
@nam-singh Nice job is looking good. @MHoov this might be a question for design but on the report, should we also have the number after the icon? 
<img width="1698" alt="Screenshot 2024-09-09 at 3 32 01 PM" src="https://github.com/user-attachments/assets/607da231-6a96-4a95-abfb-bd7b6c2a296d">

**Comment by MHoov** [comment]
@ErickRenteria , yes, that is how we currently have it implemented in the extension- the number should follow the icon.
