### ISSUE TITLE
Accessibility Checker producing warnings for icon/image buttons?

### ISSUE THREAD

**Issue by dakahn** [IBMa/equal-access#204]
## What tool(s) are you using?

- [ ] `accessibility-checker-engine`
- [x] `accessibility-checker`
- [ ] `karma-accessibility-checker`
- [ ] `rule-server`
- [ ] `boilerplates`

## Summary
[We're getting potential false positives or warnings](https://github.com/carbon-design-system/carbon/issues/6693) for icon buttons/image buttons and just want some clarity on the rules of the road as far as Accessibility Checker and the IBM Accessibility Checklist guidance on labeless icon buttons. Will these always produce warnings? Thanks for any help.

**Comment by tombrunet** [comment]
Added a note to https://github.com/carbon-design-system/carbon/issues/6693 referencing this bug. Change to fix: https://github.com/IBMa/equal-access/pull/205

**Comment by tombrunet** [comment]
This should be fixed in the `preview` archive. Will also be included in the next release.
