### ISSUE TITLE
[BUG: Extension]: When clicking in the DOM while in 'focus mode', focus mode is jumping to last selected issue

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#2069]
### Project

extension-checker

### Browser

Chrome

### Operating system

MacOS

### Description

When in focus mode, if I click on an element to 'focus', focus immediately jumps to a child element, forcing focus to jump narrower than what I actually clicked on.

### Steps to reproduce

* Go to https://altoromutual.12mc9fdq8fib.us-south.codeengine.appdomain.cloud/
* Scan with the extension
* Click an issue
* Change to 'focus mode'
* Click on some parent of that previous issue (e.g., `body` element)

Note: This only happens if you have selected an issue previously, and the selected element is a parent of that previously selected issue. Once you click on an element that does not contain that previously selected issue, then it works okay until you select another issue.

![image](https://github.com/user-attachments/assets/dd53cabb-c5a3-404c-9120-6fe2f98fb9f0)

**Comment by drjoho** [comment]
Looking at the bug it appears that if an issue is selected and in focus mode that if another element is selected in the DOM view the problem is that the previously selected issue with is also associated with focus mode is not cleared. I think that if the previously selected issue is cleared all will behave just fine.

**Comment by drjoho** [comment]
Here is a link to the meeting with Tom, Phill and I.

https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZjIxZWZjMDUtYWNkNi00ODYzLTg1MTctNjQxYjgxNDk2ZWFk%40thread.v2/0?context=%7b%22Tid%22%3a%22fcf67057-50c9-4ad4-98f3-ffca64add9e9%22%2c%22Oid%22%3a%221662b31e-91b7-4647-b36c-d043bbef6af0%22%7d

**Comment by MHoov** [comment]
@nam-singh for after you complete ACS work - thanks!
