### ISSUE TITLE
[BUG] Mac OS Fails to Build

### ISSUE THREAD

**Issue by r4d** [IBMa/equal-access#219]
## What tool(s) are you using?

- [ ] `accessibility-checker-engine`
- [ ] `accessibility-checker`
- [x] `karma-accessibility-checker`
- [ ] `rule-server`
- [ ] `boilerplates`
- [ ] `other`

## Detailed description

> Node version:
> Platform: 

> Describe in detail the issue you're having.

## Steps to reproduce the issue

1. Setup aChecker for CI/CD in angular application
2. Build application using karma accessibility plugin (aChecker)
3. Error shown on Mac OS build saying directory can't be created

`
Ryan Ford  10:24 AM
{ Error: ENOENT: no such file or directory, mkdir 'results/src/app'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.writeObjectToFileAsJSON (/Users/ryan.v.ford@ibm.com/Documents/repos/cb-suite-ui/node_modules/karma-accessibility-checker/lib/reporters/ACReporterJSON.js:95:16)
    at Object.savePageResults (/Users/ryan.v.ford@ibm.com/Documents/repos/cb-suite-ui/node_modules/karma-accessibility-checker/lib/reporters/ACReporterJSON.js:69:24)
    at Server.<anonymous> (/Users/ryan.v.ford@ibm.com/Documents/repos/cb-suite-ui/node_modules/karma-accessibility-checker/lib/reporters/ACReporter.js:173:28)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at Browser.onInfo (/Users/ryan.v.ford@ibm.com/Documents/repos/cb-suite-ui/node_modules/karma/lib/browser.js:68:20)
    at Socket.socket.on (/Users/ryan.v.ford@ibm.com/Documents/repos/cb-suite-ui/node_modules/karma/lib/browser.js:209:38)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at /Users/ryan.v.ford@ibm.com/Documents/repos/cb-suite-ui/node_modules/socket.io/lib/socket.js:528:12
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'results/src/app' }`

## Additional information

- Screenshots or code
![image](https://user-images.githubusercontent.com/4708520/92779979-23bda180-f368-11ea-9b8d-7adc6c8dc043.png)

- Notes
1. Tried this on multiple Angular applications and the builds all fail with the same issue on MacOS
2. Directory generated in MacOS is set to System only for read/write
3. Workaround involves taking ownership of the "results" directory and then deleting results followed by creating each of the directories that the karma accessibility tool attempts to create manually

**Comment by tombrunet** [comment]
We have not encountered this problem on MacOS. It looks like either the output directory that you specified doesn't exist, or you have specified permissions for that directory that prevent the tool from creating output. If you're not running as root and the directory has root-only permissions, you umask may have been changed. What do you see in the terminal when you run `umask` from that directory?

**Comment by r4d** [comment]
@tombrunet , the tool is attempting to create the output directory as well as the sub-directories.  The output directory is 1st deleted.  Once the tool creates the root directory, it has problems creating the sub-directories and throws the above error.  Only when the user creates the directory does the karma plugin stop creating the above error.  This is happening for multiple users on mac OS using multiple repos (not just one).  There is a common build system used, and perhaps there's a setting that needs to be made to prevent this issue.

Issue is that the permissions issue seems to be associated with the tool, not the user.  There's no way to delete the output directory until you take ownership in macOS.

https://stackoverflow.com/questions/28498296/enoent-no-such-file-or-directory-on-fs-mkdirsync

**Comment by r4d** [comment]
![image](https://user-images.githubusercontent.com/4708520/92954973-fafde080-f429-11ea-9437-deaeb90d1732.png)

**Comment by tombrunet** [comment]
I'm unable to reproduce this on my Mac. I still believe you have something in your directory permissions / umask that is non-default. The tool will run as whichever user you run it as, and is bound to the system permissions that you grant in that OS environment.

Unlike your command-line example, we pass in the recursive option:
```
fs.mkdirSync(parentDir, { recursive: true});
```

For sanity, I ran this on my machine using our [basic boilerplate](https://github.com/IBMa/equal-access/tree/master/karma-accessibility-checker/boilerplates/basic).

I changed achecker.js to use:
```
  outputFolder: "some/path/that/does/not/exist/a11y/results",
```

Then:
```
Toms-MacBook-Pro:basic thbrunet$ ls some
ls: some: No such file or directory
Toms-MacBook-Pro:basic thbrunet$ npm test

> karma-ibma-examples@0.0.1 test /Users/thbrunet/Tom/Git/equal-access/karma-accessibility-checker/boilerplates/basic
> karma start

16 09 2020 14:36:43.412:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
16 09 2020 14:36:43.414:INFO [launcher]: Launching browsers ChromeCustom with concurrency unlimited
16 09 2020 14:36:43.418:INFO [launcher]: Starting browser ChromeHeadless
16 09 2020 14:36:43.757:INFO [HeadlessChrome 85.0.4183 (Mac OS X 10.15.6)]: Connected on socket NGymORo-h2PTUdRzAAAA with id 88932255
16 09 2020 14:36:43.808:WARN [web-server]: 404: /somfile.png
HeadlessChrome 85.0.4183 (Mac OS X 10.15.6): Executed 1 of 1 SUCCESS (0.034 secs / 0.035 secs)
TOTAL: 1 SUCCESS
Toms-MacBook-Pro:basic thbrunet$ ls some/path/that/does/not/exist/a11y/results/summary_2020-09-16-14-36-43GMT.json 
some/path/that/does/not/exist/a11y/results/summary_2020-09-16-14-36-43GMT.json
Toms-MacBook-Pro:basic thbrunet$ ls some/path/that/does/not/exist/a11y/results/src/HelloWorld.html.json 
some/path/that/does/not/exist/a11y/results/src/HelloWorld.html.json
```

Beforehand, my output directory does not exist and my file directory is nested off of that output directory. The tool creates all of those directories and writes the files without error.

**Comment by r4d** [comment]
@tombrunet , this isn't just my machine... it's multiple users.  It's happening on my windows box as well.  Though when i use the command directly with recursive set, it doesn't seem to error out (as you pointed out).
I'll respond to this thread by tomorrow with an update on re-running this locally and attempt to get you some further and reproducible details.

**Comment by r4d** [comment]
@tombrunet , i think this is node.js related.  Node 10+ supports the mkdirSync and from what i can determine, machines running node.js pre-10 are having this issue.  I'm good with closing this issue as node version related.  Once i updated to node.js v12, the issue is no longer showing.

**Comment by tombrunet** [comment]
That makes more sense. Thank you for figuring that out!
