### ISSUE TITLE
[BUG] grid with SVG: spurious error about interactive element not having an accessible name

### ISSUE THREAD

**Issue by wkeese** [IBMa/equal-access#238]
## What tool(s) are you using?

EAAC in Chrome.

## Detailed description

EAAC throws an error about the HTML below. 

```
<div role="grid" aria-label="This is a table sample showing row actions">
	<div role="row">
		<div role="gridcell">
			<button aria-label="Actions" title="Actions">
				<svg focusable="false" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg"
					 width="16" height="16" viewBox="0 0 32 32" aria-hidden="true">
					<circle cx="16" cy="8" r="2"></circle>
					<circle cx="16" cy="16" r="2"></circle>
					<circle cx="16" cy="24" r="2"></circle>
				</svg>
			</button>
		</div>
	</div>
</div>
```

It gives an error about the `<div role="gridcell">` that

> An interactive element/widget does not have an accessible name.

If I replace the `<button>` block with:

```
<button aria-label="Actions" title="Actions">
	hello world
</button>
```

Then it works fine.

**Comment by tombrunet** [comment]
Addressed in https://github.com/IBMa/equal-access/pull/240

**Comment by tombrunet** [comment]
Will be in the `preview` ruleset when this job completes: https://github.com/IBMa/equal-access/actions/runs/284813662
