### ISSUE TITLE
Command-line: Windows attempts to execute achecker.js config file rather than achecker command.

### ISSUE THREAD

**Issue by michaelbowler** [IBMa/equal-access#251]
-->

## What tool(s) are you using?

- [ ] `accessibility-checker-engine`
- [ X] `accessibility-checker`
- [ ] `karma-accessibility-checker`
- [ ] `rule-server`
- [ ] `boilerplates`

## Relevant information

Just installed [NPM accessibility-checker](https://www.npmjs.com/package/accessibility-checker)
Created my achecker.js, URLs.txt etc, etc, 

When I run npx achecker myurls.txt, I get:

![image](https://user-images.githubusercontent.com/5979512/95446986-fe1cbb80-0958-11eb-9771-6b4c6aa83a43.png)
<!--

**Comment by tombrunet** [comment]
working for me on windows. can you include your achecker.js and check-runbook.txt files?

**Comment by michaelbowler** [comment]
Git won't let me attach files so..

check-runbook.txt
https://pages.github.ibm.com/wh-curamspm-devops/spm-kubernetes/
https://pages.github.ibm.com/wh-curamspm-devops/spm-kubernetes/architecture/kubernetes/spm-on-kubernetes-101
https://pages.github.ibm.com/wh-curamspm-devops/spm-kubernetes/architecture/kubernetes/what-is-containerization
https://pages.github.ibm.com/wh-curamspm-devops/spm-kubernetes/architecture/kubernetes/what-is-helm
https://pages.github.ibm.com/wh-curamspm-devops/spm-kubernetes/architecture/kubernetes/what-is-kubernetes
https://pages.github.ibm.com/wh-curamspm-devops/spm-kubernetes/architecture/kubernetes/what-is-openshift
https://pages.github.ibm.com/wh-curamspm-devops/spm-kubernetes/architecture/arch-overview/architecture-overview
https://pages.github.ibm.com/wh-curamspm-devops/spm-kubernetes/architecture/arch-overview/spm-iks-reference-architecture
https://pages.github.ibm.com/wh-curamspm-devops/spm-kubernetes/architecture/arch-overview/dev-workstation
https://pages.github.ibm.com/wh-curamspm-devops/spm-kubernetes/architecture/arch-overview/static-content

achecker.js
module.exports = {
    ruleArchive: "latest",
    policies: ["IBM_Accessibility"],
    failLevels: ["violation", "potentialviolation"],
    reportLevels: [
        "violation",
        "potentialviolation",
        "recommendation",
        "potentialrecommendation",
        "manual",
        "pass",
    ],
    outputFormat: ["csv"],
    label: [process.env.TRAVIS_BRANCH],
    outputFolder: "results",
    baselineFolder: "test/baselines",
};

**Comment by michaelbowler** [comment]
No doubt I'm doing something dumb...

**Comment by tombrunet** [comment]
After morning meetings, I'll try again with that. What version of node (`node -v`)?

**Comment by michaelbowler** [comment]
v12.18.2

Thanks for your efforts

**Comment by tombrunet** [comment]
Apparently, on Windows, when you type `achecker` it thinks you're trying to execute `achecker.js` in your current directory (the config file) rather than run the `achecker` command. It then tries to run the config file against the Windows JScript interpreter. For an immediate fix, move the achecker.js file into a .config folder (`.config/achecker.js`) and then run again. I'm going to leave this issue open since we may need to rename the config file.

**Comment by michaelbowler** [comment]
Thanks Tom, that worked nicely.

Another niggle though, is that I specify "outputFormat: ["csv"]," - but achecker still gives me JSON output.

Rgds

**Comment by tombrunet** [comment]
https://github.com/IBMa/equal-access/pull/388

**Comment by tombrunet** [comment]
`aceconfig.js` will be supported as a config filename in the next release.

**Comment by destrex271** [comment]
npx achecker is taking a very long time to execute some urls
is there any workaround for it?
