### ISSUE TITLE
Engine: Engine supports reasonCode specific help, help switcher does not

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#257]
In the gulpFiles (extension and report-react), the generator of the helpSwitcher keys off of the rule id and doesn't use the help mapping defined by the engine.

**Comment by marcjohlic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Equal-Access-61ae71f9f8b4ec001e136462/issues/IBMa/equal-access/257?planning-poker) with ZenHub @aliunwala @mbgower @shunguoy @tombrunet @philljenkins @drjoho

**Comment by marcjohlic** [comment]
Tom said the new rule architecture (PR #712) will resolve this issue - closing
