### ISSUE TITLE
Cannot have 2 components with main role on the same screen (helper tet say othewise)

### ISSUE THREAD

**Issue by alon24** [IBMa/equal-access#259]
While the help text for having 2 components with main on screen it is actually an issue and is not allowed
As per conversation in channel, I am opening this defect to track.

![image](https://user-images.githubusercontent.com/5415443/97194883-5524ec00-17b3-11eb-9129-b8748f45f3b1.png)

**Comment by tombrunet** [comment]
Addressed by https://github.com/IBMa/equal-access/pull/389

**Comment by tombrunet** [comment]
Available in the 'preview' archive.
