### ISSUE TITLE
Accessibility Checker: Desperately need more screen real estate

### ISSUE THREAD

**Issue by carmacleod** [IBMa/equal-access#262]
At home, I only have one monitor. 😢 

The checker uses a lot of whitespace (I understand that design wants it that way... but design isn't trying to use this tool...)

I usually have DevTools docked on the bottom, and sometimes on the right, depending on the page. (Not a fan of separate window on one monitor - I like to see everything at once).

Here is a screenshot of my current window. I have just done a scan, and now I want to look at the tree of violations.
My first instinct is to move the mouse to the area with the red arrows and use the scroll wheel to scroll away all the stuff I don't need at the moment. I still do this even though it doesn't work, because apparently my brain and my hand think it should work. :)

![image](https://user-images.githubusercontent.com/3331913/97306825-5a2a7f80-1835-11eb-880c-d1b2b0cbbc47.png)

Please make the whole thing scroll. I've done the scan, I don't need to see the controls at the moment, and I know I can always scroll back up to get them. In fact (just tested in the violations tree), I know I can use the Home key to get there immediately.

Space is always at a premium in DevTools. If you look at other DevTools panels, most of them scroll the entire area (and/or they use less vertical whitespace between lines). The Computed Styles panel scrolls away the box diagram. Event Listeners scrolls away the controls. Styles keeps the controls at the top, but it's usually only one line (plus, they have way less whitespace between the lines of css).

Here's a snap of the exact same window as above, running a Lighthouse Accessibility Audit (Chrome DevTools uses aXe under the covers). They have a completely separate screen for the controls:

![image](https://user-images.githubusercontent.com/3331913/97308967-da51e480-1837-11eb-92b9-a62e0e36f980.png)

When the results show up, they completely replace the control screen:

![image](https://user-images.githubusercontent.com/3331913/97309466-6fed7400-1838-11eb-9cbb-9f9f78fdab57.png)

Just as with Accessibility Checker, I can't see the violations so I scroll down... and the whole panel scrolls to maximize the available space (their treeitems have a lot of whitespace, too 😄, but I think that comes from aXe, and not Chrome):

![image](https://user-images.githubusercontent.com/3331913/97329429-66bad200-184d-11eb-9b95-3834ecf463f0.png)

**Comment by carmacleod** [comment]
This is really a problem for me. I don't like docking devtools on the side just to accommodate the AC, and even when I do, it _still_ wants a huge amount of vertical space before the meat of the panel - i.e. the tree of violations - is reasonably visible.

Here's another screen shot:
![image](https://user-images.githubusercontent.com/3331913/103419772-7d89e780-4b62-11eb-92d9-d614f53d780e.png)

**Comment by drjoho** [comment]
here is a preview of our next release using right side vertical mode to get more real estate for the check and the page you are checking:
![image](https://user-images.githubusercontent.com/64442976/115589592-a232d800-a295-11eb-956b-7a454f297ceb.png)

**Comment by carmacleod** [comment]
Ooooh, that looks a lot better! Looking forward to trying it out! :)

**Comment by carmacleod** [comment]
Of course, the Element roles, Checkpoints, Rules tablist is still missing...

**Comment by drjoho** [comment]
good catch more work on layout!!!

**Comment by MHoov** [comment]
@carmacleod we have that issue on our internal board - for Element roles, Checkpoints, Rules tablist is still missing

**Comment by drjoho** [comment]
maybe this is better:

![image](https://user-images.githubusercontent.com/64442976/115627968-7a5b6880-a2c5-11eb-958e-b275df0154cf.png)

**Comment by drjoho** [comment]
or the same page:
![image](https://user-images.githubusercontent.com/64442976/115629502-14bcab80-a2c8-11eb-8497-6c33b32cd3bd.png)

**Comment by carmacleod** [comment]
Looks good! Thanks!

**Comment by marcjohlic** [comment]
@drjoho I believe this one is completed and can be closed.  Please confirm, and close if so.

**Comment by aliunwala** [comment]
In Triage meeting: 

Looks like we resolved most of this. @carmacleod If you have any additional comments let us know. But for now we are going to close this issue.
