### ISSUE TITLE
[BUG]#276

### ISSUE THREAD

**Issue by Destop-Trang1801** [IBMa/equal-access#276]
## What tool(s) are you using?

- [x] `accessibility-checker-engine`
- [x] `accessibility-checker`
- [x] `karma-accessibility-checker`
- [x] `rule-server`
- [x] `boilerplates`
- [ ] `other`

## Detailed description

> Node version:
> Platform: 

> Describe in detail the issue you're having.

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by tombrunet** [comment]
No bug information provided. Closing.
