### ISSUE TITLE
Can we add a subfolder for `outputResults` ?

### ISSUE THREAD

**Issue by nsharma1989** [IBMa/equal-access#277]
## What tool(s) are you using?

- [ ] `accessibility-checker-engine`
- [x] `accessibility-checker`
- [ ] `karma-accessibility-checker`
- [ ] `rule-server`
- [ ] `boilerplates`

## Summary
Hi, is it possible to use `outputResults: "results/" + date()` for categorizing results?

## Relevant information

I am using `outputFolder: "results/1.2",` but the results are still getting stored in results

**Comment by tombrunet** [comment]
If you want to use variables in your configuration, you need to use the .js form of the configuration included in the documentation. For example:
```
module.exports = {
    ruleArchive: "latest",
    policies: ["IBM_Accessibility"],
    failLevels: ["violation", "potentialviolation"],
    reportLevels: [
        "violation",
        "potentialviolation",
        "recommendation",
        "potentialrecommendation",
        "manual",
        "pass",
    ],
    outputFormat: ["json"],
    label: [process.env.TRAVIS_BRANCH],
    outputFolder: `results/${new Date().toISOString()}`,
    baselineFolder: "test/baselines",
};
```

**Comment by tombrunet** [comment]
Closing since there is no response after the proposed js file solution.
