### ISSUE TITLE
[BUG] Scanned page information did not update accordingly when reset Accessibility Checker.

### ISSUE THREAD

**Issue by ATT1003** [IBMa/equal-access#300]
## What tool(s) are you using?

- [ ] `accessibility-checker-engine`
- [x] `accessibility-checker`
- [ ] `karma-accessibility-checker`
- [ ] `rule-server`
- [ ] `boilerplates`
- [ ] `other`

## Detailed description

> Version: Version 3.1.0
> Platform: 84.0.2 (64-bit)

> When re-scan or reset Accessibility Checker, in scan summary, the scanned page information did not update accordingly. The information would only update when refreshing the page.

## Steps to reproduce the issue

1. Run Accessibility Checker on one page
2. Press reset

## Additional information

- Screenshots or code
- Notes

![Screen Shot 2021-01-21 at 2 17 46 PM](https://user-images.githubusercontent.com/21376760/105661182-c5a0ed80-5f07-11eb-9c68-94003c30808f.png)

**Comment by drjoho** [comment]
I have not been able to reproduce the above error. Here are the steps I am doing. I go to a url (URL1). Then I scan URL1 and see the scan summary (SS1). Then with the same URL1 I do either a reset or rescan and I see a different scan summary (SS2). Then if I do a refresh I see a new URL2 with scan summary (SS2) that matches the page correctly. Are these the correct steps?

**Comment by ATT1003** [comment]
Steps to reproduce the issue:
1. Scan URL1 and get scan summary (SS1)
2. In the same tab, go to URL2, and scan it. All information in SS2 are refreshed except URL2.

The only way to get URL2 information is to do a refresh.

**Comment by drjoho** [comment]
We are in the process of deploying a new release that does not have the issue you report.

**Comment by eirckr** [comment]
Version 3.1.2 was released yesterday, can you please test this again.

**Comment by ATT1003** [comment]
@eirckr This issue seem not fixed yet. Testing on https://www.ibm.com/able/toolkit:

1. Scan page: https://www.ibm.com/able/toolkit/verify/automated
![Screen Shot 2021-02-17 at 9 12 41 AM](https://user-images.githubusercontent.com/21376760/108142488-d6a4df00-7100-11eb-81d7-22a849cd3311.png)

2. Move to page https://www.ibm.com/able/toolkit/verify/manual and scan it
![Screen Shot 2021-02-17 at 9 12 56 AM](https://user-images.githubusercontent.com/21376760/108142525-e9b7af00-7100-11eb-899f-787f8ee9e70b.png)


The scanned page information did not update accordingly.

**Comment by tombrunet** [comment]
@ATT1003 On the [options page](chrome-extension://lkcagbfjnkomcinoddgooolagloogehp/options.html) are you seeing 3.1.2? When I navigate to the second page, the whole bottom section blanks out and resets. When I press "Scan" again, I see then new URL. I am unable to get it to keep the old URL.

**Comment by ATT1003** [comment]
@tombrunet  yes I see Version 3.1.2 and my Firefox version is 86.0 (64-bit). I scanned the page https://www.ibm.com/able/toolkit. If I scanned on 1st page, and then in the same tab navigate to 2nd page, the bottom section did not reset unless I reset or re-scan it. However, the scanned page information not.
![image](https://user-images.githubusercontent.com/21376760/109596889-1385c280-7b52-11eb-8a56-dcf149a173ae.png)

**Comment by ATT1003** [comment]
Tested on Chrome, the behavior will be as @tombrunet described above. Please help to check if it is a browser related issue? Thanks a lot.

**Comment by drjoho** [comment]
What I find with Firefox is that if you are url1 and move to url2 you must refresh the page (which will reset the checker) and then scan. Then the results will be the same as in Chrome. So the issue as best as I can tell is Firefox only but can easily worked around by refreshing the page before scanning.

**Comment by ATT1003** [comment]
Yes, this is why I submitted this issue-- the reset did not really work as it's supposed be..;

**Comment by drjoho** [comment]
This is fixed for Firefox in Version 3.3.12
