### ISSUE TITLE
Display the code line number in the "Element location" tab

### ISSUE THREAD

**Issue by icks1313** [IBMa/equal-access#304]
### Summary

It would be nice if IBM Accessibility Checker could align with other checkers and display the number of the line where the problem is detected.

### Justification

Not everyone is a developer. Someone it's simply a UX researcher and accessing the DOM => Elements ctrl+f => "copy the wrong line or portion of it" does not bring result, nor "right click + view page source" does not bring any results. 
Other tools, provide the line number or the visualize the item on the page or open a dedicated console showing where the problem is located (ie WAVE)

### "Must have" functionality

Usability and accessibility

ty!

**Comment by tombrunet** [comment]
This request has come up over the years, but in our experience, the concept of the line number is non-sensical in this context. A web page or web application that loads from an HTML file and injects zero dynamical content is almost non-existent today. Therefore, a line number in the DOM does not actually map back to any file.

However, given what you're asking for, which panel of the Accessibility Checker are you using? If you use the Elements subpanel (see screenshot below), when you select an issue, it highlights the issue in the DOM and Chrome highlights that element in the browser - so you can see the content in context of the DOM and the visual browser...

In the case of this screenshot, the table is shown in the DOM Elements view and also shows that it's a table at the top of the page.
![image](https://user-images.githubusercontent.com/19577713/106952115-4923c100-66f6-11eb-9ed7-0b858b470fa9.png)

**Comment by icks1313** [comment]
Basically I just cancelled the whole message I was writing because suddenly has started to work like in the screenshot you have provided. 
Previously, by selecting the issue like you did, nothing was was selected in the DOM. Once you have replied to this message I tried and the only thing that was selected, no matter what was the problem, it was the <body> line. 
Now it works:) 
best!

**Comment by tombrunet** [comment]
Fantastic. Thanks!

**Comment by icks1313** [comment]
Hi Tom, 
sorry to re-open it, but now it doesn't work anymore. I click on errors, in the checkpoint tab or in the elements tabs of the plugin, but nothing is highlighted in the code of the site displayed in the DOM/element. For example in this case, why it does not highlight <h3 class="paneltitle"> in the DOM? What am I missing? ty

![image](https://user-images.githubusercontent.com/78564788/106972299-e14e9400-6750-11eb-8eb2-e80e2a711f41.png)
