### ISSUE TITLE
Resolve inconsistencies in Windows paths of reports

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#319]
Related to Node accessibility-checker. Report paths for different file types seem odd / inconsistent. See comment: https://github.com/IBMa/equal-access/issues/241#issuecomment-706854970

> FYI, I also found inconsistencies in the subdirectory structure and
naming conventions used when the output format was html vs json vs csv
-- beyond differences in extensions of output files. For example, the 
html output was a file inside a subdirectory named after the web domain
tested, with a file name of just ".html" -- unusual for the name of a
file on Windows and for a file that is not meant to be hidden by
default.  The json output, on the other hand seemed to be in a file
named "results.json" (a good name, IMHO) at a higher directory level.

**Comment by tombrunet** [comment]
Usually the filename would be the label. This might happen when using the batch checked, and I would expect the html, json, etc to have the same name. However, I agree that `.html` is a weird filename. Should it be `index.html`? `_.html`? Other name?

**Comment by aliunwala** [comment]
From Triage Meeting:
We are closing this as it is not possible to create a file name where the page does not provide one. This is a problem because we can get filename conflicts if we were to "make up" our own filename.
