### ISSUE TITLE
Toolkit > Requirements : add link to individual checkpoint

### ISSUE THREAD

**Issue by francesco-mariani** [IBMa/equal-access#322]
### Summary

Add an anchor/link to each checkpoint, in the Requirements section

### Justification

A very common use case is sharing the link to a specific checkpoint. This is not possible anymore.
Moreover, as a side, it is not possible to select the checkpoint name to then paste it somewhere, e.g. when sharing information.

### "Must have" functionality

Link to the individual checkpoint

**Comment by tombrunet** [comment]
I think you found what you were looking for elsewhere, but leaving this open until we get a design to help with self discovery. For the record, these checkpoints can be linked with a pattern similar to https://www.ibm.com/able/requirements/requirements/#1_2_1 as an example link into 1.2.1.

**Comment by marcjohlic** [comment]
[3851](https://github.ibm.com/IBMa/E2E/issues/3851) opened in Internal backlog to track this issues for Designers

**Comment by aliunwala** [comment]
Triage meeting:

This issue is being tracked internally (in the above link) by the design teams and we are going to close this issue.
