### ISSUE TITLE
[BUG] Possible false positive on the 1.4.3 Contrast (Minimum)

### ISSUE THREAD

**Issue by TalesAbdo** [IBMa/equal-access#323]
When my team runs the Accessibility checker in our tool, it returns an error saying some texts are with the same color as the page background. But what happens is that in reality the texts are in a right panel.

## What tool(s) are you using?

- [ ] `accessibility-checker-engine`
- [x] `accessibility-checker`
- [ ] `karma-accessibility-checker`
- [ ] `rule-server`
- [ ] `boilerplates`
- [ ] `other`

## Detailed description

> Node version:
> Platform: 

Reproduced in macOS Big Sur 11.2.1 using Firefox 85.0.2.

> Describe in detail the issue you're having.

Running the accessibility checker in our application, it returns an error saying some texts are with the same color as the page background. But what happens is that in reality the texts are in a right panel. We are using Carbon elements, and we run the checker with these pages opened. Some images will be attached.

## Steps to reproduce the issue

1. Open the application
2. Expand the right panel
3. Run the Accessibility Checker 

## Additional information

This is the of the dropdown that is appointing the error. The second 'li' element is the one with 'error'.
```
<ul>
    <li class="navbar__user-menu-li"><button class="navbar__user-menu-btn" type="button"
            data-autoid="dds--privacy-cp__link">Cookie preferences</button></li>
    <li class="navbar__user-menu-li"><a class="navbar__user-menu-btn" target="_blank" rel="noopener noreferrer"
            href="https://w3.ibm.com/w3publisher/w3-privacy-notice/">IBM privacy policy</a></li>
    <li class="navbar__user-menu-li"><a class="navbar__user-menu-btn" target="_blank" rel="noopener noreferrer"
            href="https://www.ibm.com/legal">Terms of use</a></li>
    <li class="navbar__user-menu-li"><a class="navbar__user-menu-btn" href="/languages">Preferences</a></li>
</ul>
```

Styles of the element:
```
text-rendering: optimizeLegibility;
-webkit-font-smoothing: antialiased;
list-style: none;
box-sizing: border-box;
margin: 0;
vertical-align: baseline;
background: none;
border: none;
font: inherit;
cursor: pointer;
outline: inherit;
padding: 10px 1.2rem;
width: 100%;
font-size: .875rem;
font-weight: 600;
line-height: 1.29;
letter-spacing: .16px;
display: flex;
-webkit-box-pack: justify;
justify-content: space-between;
text-decoration: none;
color: #f4f4f4;
border-radius: 0;
-webkit-box-flex: 1;
flex: 1;
```

Image showing the background color (gray-10) and the text that is 'violating' inside the black dropdown.
![image (1)](https://user-images.githubusercontent.com/18212875/109162375-e5ba0b80-7756-11eb-8dd2-0987fd2db545.png)

**Comment by tombrunet** [comment]
Is this on a page that I can see somehow? Historically, the only errors we've had in this space are due to sites doing strange things with absolute positioning - situations where the DOM thing the text is somewhere other than where it renders visually.

**Comment by tombrunet** [comment]
@TalesAbdo Is this the issue that was resolved when the DAP extension was disable? Can we close this?

**Comment by MHoov** [comment]
As of June 1
- [x] general rule description (SME & Dev)
- [ ] testcases written (Dev)
- [ ] rule bug (Dev)
- [x] message written (SME)
- [x] help written (SME)

**Comment by tombrunet** [comment]
Going to close this since there was no response regarding the potential fix.
