### ISSUE TITLE
How to batch scan all the local html files in a folder

### ISSUE THREAD

**Issue by jeniffer007** [IBMa/equal-access#326]
After downloading all the html files to a local folder, I want to scan the accessibility issues for all the local html files in one go with IBM Equal Access Accessibility Checker. Are there any detailed steps about how to achieve this goal? Thanks.

**Comment by tombrunet** [comment]
See the quick start section of the checker:
https://www.npmjs.com/package/accessibility-checker
> Quick Start
> Grab a boilerplate
> 
> Install accessibility-checker:
> 
> $ npm install --save-dev accessibility-checker
> Use the command-line version:
> 
> Install globally
> $ npm install -g accessibility-checker
> Run command-line tool after globally installed
> $ achecker

You can run the command-line tool and point at the directory:
```
achecker ./directory
```

**Comment by jeniffer007** [comment]
Thanks for your suggestions. After I run the command 
C:\23_accessibility\SSFC4F_2.3.0\admin>achecker C:\23_accessibility\SSFC4F_2.3.0\admin .
Passed: C:\23_accessibility\SSFC4F_2.3.0\admin\add_prom_mcm.html
Passed: C:\23_accessibility\SSFC4F_2.3.0\admin\intro.html
Passed: C:\23_accessibility\SSFC4F_2.3.0\admin\man_config_mc_meter.html
Passed: C:\23_accessibility\SSFC4F_2.3.0\admin\metering_service_mcm.html
Passed: C:\23_accessibility\SSFC4F_2.3.0\admin\upgrade_ocp.html

5 of 5 passed.

I see only a JSON-format result file in the results folder. 

Is it possible to generate a  result CSV file that includes the path to and file names, descriptions of the errors, and the path to where they are IN THE TRANSFORMED HTML.? How? 

Thanks.

**Comment by tombrunet** [comment]
Try creating a `.achecker.yml` file in the directory where you run the command with the following:
```
# optional - Specify the rule archive
# Default: latest
# Run `npx achecker archives` for a list of valid ruleArchive ids and policy ids
ruleArchive: latest

# optional - Specify one or many policies to scan.
# i.e. For one policy use policies: IBM_Accessibility
# i.e. Multiple policies: IBM_Accessibility,IBM_Accessibility_BETA
# Run `npx achecker archives` for a list of valid ruleArchive ids and policy ids
policies:
    - IBM_Accessibility

# optional - Specify one or many violation levels on which to fail the test
#            i.e. If specified violation then the testcase will only fail if
#                 a violation is found during the scan.
# i.e. failLevels: violation
# i.e. failLevels: violation,potential violation or refer to below as a list
# Default: violation, potentialviolation
failLevels:
    - violation
    - potentialviolation

# optional - Specify one or many violation levels which should be reported
#            i.e. If specified violation then in the report it would only contain
#                 results which are level of violation.
# i.e. reportLevels: violation
# Valid values: violation, potentialviolation, recommendation, potentialrecommendation, manual
# Default: violation, potentialviolation
reportLevels:
    - violation
    - potentialviolation
    - recommendation
    - potentialrecommendation
    - manual

# Optional - In which fornats should the results be output
# Valid values: json, csv, html
# Default: json
outputFormat:
    - csv

# optional - Where the scan results should be saved.
# Default: results
outputFolder: results

# optional - Where the baseline results should be loaded from
# Default: baselines
baselineFolder: baselines
```

**Comment by tombrunet** [comment]
I think you got this working? Is this issue now resolved?

**Comment by GiovanaNp1** [comment]
hello, I did the test with this screen but gave the following error:

![image](https://user-images.githubusercontent.com/34607779/110134898-a752cb00-7dac-11eb-8bb7-396f7f27a604.png)

**Comment by tombrunet** [comment]
@GiovanaNp1 I apparently didn't get notification of your comment. This looks like a yml syntax error. Did you get it resolved?

**Comment by tombrunet** [comment]
Closing due to no response. Reopen if you need more help.
