### ISSUE TITLE
allowed roles on figure have been updated

### ISSUE THREAD

**Issue by carmacleod** [IBMa/equal-access#335]
[ARIA in HTML - figure](https://w3c.github.io/html-aria/#el-figure)

Steps:
- Run AC on each of the following 2 test locations:
1. If the [figure has no figcaption](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/figurenofigcaption-test.html) descendant: Any role is allowed

2. If the [figure has a figcaption](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/figurewithfigcaption-test.html) descendant: No role is allowed

**Comment by MHoov** [comment]
As of June 1
- [x] general rule description (SME & Dev)
- [ ] testcases written (Dev)
- [ ] rule bug (Dev)
- [x] message written (SME)
- [x] help written (SME)

**Comment by tombrunet** [comment]
Matches tests now
