### ISSUE TITLE
hgroup elements are allowed to have any role

### ISSUE THREAD

**Issue by carmacleod** [IBMa/equal-access#336]
Steps:
- Go to: https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/hgroup-test.html
- Run Accessibility Checker
- Note that roles on hgroup elements are all flagged as violations, but they are allowed.

![image](https://user-images.githubusercontent.com/3331913/110384257-5ef51080-802b-11eb-9194-d0c6c61c6467.png)

**Comment by MHoov** [comment]
As of June 1
- [ ] general rule description (SME & Dev)
- [ ] testcases written (Dev)
- [ ] rule bug (Dev)
- [ ] message written (SME)
- [ ] help written (SME)

**Comment by tombrunet** [comment]
Fixed
