### ISSUE TITLE
Error message in Assessment panel for input type=hidden is incorrect

### ISSUE THREAD

**Issue by carmacleod** [IBMa/equal-access#338]
Steps:
- Go to: https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/input-Hidden-test.html
- Run Accessibility Checker in the Checker panel and in the Assessment panel, and compare error messages

Checker panel says "The WAI-ARIA role or attribute 'button, aria-label' is not valid for the element `<input>`"
(PS: While technically correct, it would be nice if the error message included the input type - the current message is too generic, and might be mistakenly interpreted as "you can't put button role or aria-label attribute on any input", which isn't true... but it could mislead an inexperienced developer).

Assessment panel says "The role defined on the element is not valid per WAI-ARIA specification"... but "button" is certainly a valid role (but not on `<input type="hidden">`). Is there a reason that the Checker panel and Assessment panel have different error messages for the same violation?
![image](https://user-images.githubusercontent.com/3331913/110394084-cd40cf80-8039-11eb-8ae3-a56b83b012eb.png)

**Comment by MHoov** [comment]
As of June 1
- [x] general rule description (SME & Dev)
- [x] testcases written (Dev)
- [x] rule developed (Dev)
- [ ] message written (SME)
- [x] help written (SME)

**Comment by tombrunet** [comment]
Related to #355

**Comment by tombrunet** [comment]
@carmacleod Looking back at this, I think you may have mixed up issues. The hidden stuff isn't checked because it's not visible. The span at the bottom with an invalid role is all that triggers...

**Comment by tombrunet** [comment]
To show the invalid role in the message, see PR https://github.com/IBMa/equal-access/pull/586

**Comment by carmacleod** [comment]
Wow, you are right that I must have mixed up issues somehow. I have _no idea_ where that Checker result came from, and of course I didn't include a screenshot for it, so I can't even guess. Thanks for PR #586 - that will be helpful. I'll edit the first comment in #586 so that this issue (338) will be closed automatically when 586 is merged.

**Comment by tombrunet** [comment]
Merged. Pushing to the preview archive.
