### ISSUE TITLE
Several roles are valid for the menu element

### ISSUE THREAD

**Issue by carmacleod** [IBMa/equal-access#339]
The following 11 roles are allowed on HTML `<menu>`: 
directory, group, listbox, menu, menubar, none, presentation, radiogroup, tablist, toolbar or tree

Accessibility Checker says, eg. for the 'none' role: "The WAI-ARIA role or attribute 'none' is not valid for the element `<menu>`"

![image](https://user-images.githubusercontent.com/3331913/110395349-f8c4b980-803b-11eb-896d-71cd1d082b7d.png)

**Comment by tombrunet** [comment]
https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/menu-test.html
@carmacleod 'list' is not triggering, should it?
Otherwise, everything else matches.

**Comment by MHoov** [comment]
As of June 1
- [ ] general rule description (SME & Dev)
- [ ] testcases written (Dev)
- [ ] bug (Dev)
- [ ] message written (SME)
- [ ] help written (SME)

**Comment by tombrunet** [comment]
Implicit role of menu is list. We're allowing role for implicit role.
