### ISSUE TITLE
menu, menubar, tablist are allowed roles on nav

### ISSUE THREAD

**Issue by carmacleod** [IBMa/equal-access#342]
Steps:
- go to https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/nav-test.html
- run accessibility checker
- note that menu, menubar, tablist roles are listed as violations, but these roles are allowed on nav

Screen snapshot showing menubar role as invalid on nav:

![image](https://user-images.githubusercontent.com/3331913/110548702-fb3c1780-80fe-11eb-92a1-569ec6966121.png)

**Comment by tombrunet** [comment]
Appears to now work with the latest preview ruleset
