### ISSUE TITLE
option element doesn't allow any roles

### ISSUE THREAD

**Issue by carmacleod** [IBMa/equal-access#343]
Steps:
- go to https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/option-test.html
- run accessibility checker
- note that menuitem, menuitemradio, option, and separator are not flagged as invalid roles on option, but they should be.

Screen snapshot of menuitemradio role not showing invalid role on option element:

![image](https://user-images.githubusercontent.com/3331913/110549308-deecaa80-80ff-11eb-9fa9-331317f3b641.png)

**Comment by tombrunet** [comment]
option has an implicit role of option, so, why is that not allowed? I think it will cause problems if we can't say that an element can have a role that it implicitly has...

**Comment by MHoov** [comment]
As of June 1
- [ ] general rule description (SME & Dev)
- [ ] testcases written (Dev)
- [ ] rule bug (Dev)
- [ ] message written (SME)
- [ ] help written (SME)

**Comment by tombrunet** [comment]
Confirmed with Carolyn. We're going to allow role equal to implicit role.
