### ISSUE TITLE
SVG element can have any role

### ISSUE THREAD

**Issue by carmacleod** [IBMa/equal-access#346]
New: Allow any role on SVG https://github.com/w3c/html-aria/pull/264

Spec: https://w3c.github.io/html-aria/#el-svg

Test cases: https://w3c.github.io/html-aria/tests/svg-test.html

**Comment by MHoov** [comment]
As of June 1
- [ ] general rule description (SME & Dev)
- [ ] testcases written (Dev)
- [ ] rule developed / bug (Dev)
- [ ] message written (SME)
- [ ] help written (SME)

**Comment by tombrunet** [comment]
@carmacleod I believe this is fixed... when I look at the rules triggering when I focus on the testcase element:
![image](https://user-images.githubusercontent.com/19577713/144481656-9e4e7ea4-f1e0-45a7-a928-bf636f96b4d5.png)
These are errors about missing required attributes and nesting, but it seems to allow all of the roles to me. If you agree, please close.

**Comment by carmacleod** [comment]
Agreed that this is fixed. The fix is here: https://github.com/IBMa/equal-access/blob/master/accessibility-checker-engine/src/v2/aria/ARIADefinitions.ts#L1990

There's a weird problem I noticed, though - Checker doesn't select the svg elements in the Elements panel when I click on a violation. Not sure what's up with that. I can open a new issue, so that you can close this one.

**Comment by tombrunet** [comment]
Thank you!
