### ISSUE TITLE
flag errors for aria-hidden on input type=hidden, noscript, script, slot, template

### ISSUE THREAD

**Issue by carmacleod** [IBMa/equal-access#349]
Steps:
- go to https://w3c.github.io/html-aria/tests/aria-hidden-invalid-element-test.html
- run accessibility checker
- note that "The WAI-ARIA role or attribute 'aria-hidden' is not valid for the element [...]" errors are flagged for most of the elements in Test 1, but errors need to be flagged for hidden, noscript, script, slot, and template as well.

**Comment by MHoov** [comment]
As of June 1
- [x] general rule description (SME & Dev)
- [x] testcases written (Dev)
- [ ] rule developed  (Dev)
- [ ] message written (SME)
- [ ] help written (SME)

**Comment by shunguoy** [comment]
picture element should be removed from the list per https://w3c.github.io/html-aria/#el-picture
close as fixed per #800

**Comment by eirckr** [comment]
Validated 
<img width="1389" alt="Screen Shot 2022-05-03 at 11 47 13 AM" src="https://user-images.githubusercontent.com/62436670/166500805-150d43f9-649f-447b-84fd-6140e1cf339d.png">
