### ISSUE TITLE
[Rule] error/warning for use of aria-colspan with colspan (and aria-rowspan with rowspan)

### ISSUE THREAD

**Issue by carmacleod** [IBMa/equal-access#354]
Steps:
- go to https://w3c.github.io/html-aria/tests/colspan-test.html
- run accessibility checker
- should warn that aria-colspan and colspan shouldn't be used together, and if they conflict, should throw error that they conflict

From the spec: https://w3c.github.io/html-aria/#att-colspan
> Authors SHOULD NOT use the aria-colspan attribute on any element which also has a colspan attribute.
> Authors MUST NOT use aria-colspan on any element which also has a colspan attribute, and the values of each attribute do not match.

**Comment by carmacleod** [comment]
Same goes for rowspan/aria-rowspan:
Test cases: https://w3c.github.io/html-aria/tests/rowspan-test.html
Spec: https://w3c.github.io/html-aria/#att-rowspan

**Comment by MHoov** [comment]
As of June 1
- [x] general rule description (SME & Dev)
- [x] testcases written (Dev)
- [ ] rule developed  (Dev)
- [ ] message written (SME)
- [ ] help written (SME)

**Comment by aliunwala** [comment]
From triage:
We might want to make a new rule that is a general rule that flags redundant roles.

The message should be similar to:
"You should not override the native element role with an aria-role as it is redundant. "

**Comment by shunguoy** [comment]
close as fixed per #800

**Comment by eirckr** [comment]
validated
