### ISSUE TITLE
Checker should flag aria-valuemax on number/range inputs and progress elements

### ISSUE THREAD

**Issue by carmacleod** [IBMa/equal-access#359]
Steps:
- go to https://w3c.github.io/html-aria/tests/max-test.html
- run Checker

input type=number, input type=range and progress should all report violations for:
"The WAI-ARIA role or attribute 'aria-valuemax' is not valid for the element ____"

**Comment by MHoov** [comment]
As of June 1
- [x] general rule description (SME & Dev)
- [ ] testcases written (Dev)
- [ ] rule bug (Dev)
- [x] message written (SME)
- [x] help written (SME)

**Comment by shunguoy** [comment]
fixed as #800

**Comment by eirckr** [comment]
Validated 
<img width="1444" alt="Screen Shot 2022-05-03 at 11 56 28 AM" src="https://user-images.githubusercontent.com/62436670/166512340-53e9ef83-6de3-42ba-aca6-c02d86c5fee3.png">
