### ISSUE TITLE
aria-required updates needed

### ISSUE THREAD

**Issue by carmacleod** [IBMa/equal-access#361]
Steps:

- go to https://w3c.github.io/html-aria/tests/required-test.html
- run Checker

test 1 - input type=checkbox, radio, file, date, month, time and week allow aria-required, so checker should not flag these
test 2 - checker should flag aria-required and required used on the same element

**Comment by carmacleod** [comment]
@scottaohara

For test1, radio role doesn't support aria-required - it's only supported on radiogroup in ARIA.
https://github.com/w3c/aria/issues/1442

So, since `<input type="radio">` has implicit `role="radio"`, should we flag `aria-required` on radio inputs... or not?

**Comment by MHoov** [comment]
As of June 1
- [x] general rule description (SME & Dev)
- [x] testcases written (Dev)
- [ ] rule developed  (Dev)
- [ ] message written (SME)
- [ ] help written (SME)

**Comment by tombrunet** [comment]
@philljenkins

**Comment by aliunwala** [comment]
Triage:
@philljenkins Can you take a look at this one.

**Comment by marcjohlic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Equal-Access-61ae71f9f8b4ec001e136462/issues/IBMa/equal-access/361?planning-poker) with ZenHub @aliunwala @drjoho @mbgower @philljenkins @shunguoy @tombrunet

**Comment by shunguoy** [comment]
close as fixed per #800

**Comment by eirckr** [comment]
Validated
