### ISSUE TITLE
treatment of dpub roles with checker

### ISSUE THREAD

**Issue by scottaohara** [IBMa/equal-access#371]
running, for example, [this test case (`a` with `href`](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/ahref-test.html) - the checker returns 36 instances of "Elements must have a valid 'role' per WAI-ARIA specification"

35 of these are all the dpub roles used in the test case (one of them being a placeholder role for a control test).

while it is not expected for authors to use dpub roles on the web, they are valid roles, and in regards to this particular test case, [4 of them are valid for use](https://w3c.github.io/html-aria/#el-a).

I would request that dpub roles are not reported as completely invalid, but as a dpub role which may not be respected on the web (exposed by browsers, or recognized by AT).

ideally, the checker would report valid dpub roles and invalid dpub roles per element as well.  

Where if an element is allowed "any role" then any dpub role would also be "valid" (but a warning that it is for dpub and not necessarily the web).
Otherwise, only the indicated allowed dpub roles on that element would be "valid"
Otherwise, no dpub roles allowed if "no role" is declared, or neither of the above are true.

Thanks!

**Comment by tombrunet** [comment]
@scottaohara Can you take another look at this one? I'm confused. The testcase says they're all invalid. We say they're invalid for `<a>`. I think there may be a few we don't report...? I'm not sure if this was already fixed, or the testcase changed, or....?

**Comment by scottaohara** [comment]
sorry @tombrunet.  I think something happened to the test case?   unfortunately these are hosted on tpg's github and I don't have direct access to them anymore from when I originally filed this back in March.

the allowed dpub roles are specifically 
```
<a href=# role=doc-backlink>...</a>
<a href=# role=doc-biblioref>...</a>
<a href=# role=doc-glossref>...</a>
<a href=# role=doc-noteref>...</a>
```

**Comment by ErickRenteria** [comment]
Merged
