### ISSUE TITLE
update td, th, tr allowances when within a table/grid/treegrid

### ISSUE THREAD

**Issue by scottaohara** [IBMa/equal-access#372]
Per [ARIA in HTML](https://w3c.github.io/html-aria/#el-td) when used within a `role=table, grid, treegrid` the `td`, `tr`, and `th` elements should not be allowed any explicitly set role, as that would break the a11y mappings of the table, grid or treegrid.  
[td in role=table](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/td-table-test.html)
[td in role=grid](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/td-grid-test.html)
[td in role=treegrid](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/td-treegrid-test.html)

[tr in role=table](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/tr-table-test.html)
[tr in role=grid](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/tr-grid-test.html)
[tr in role=treegrid](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/tr-treegrid-test.html)

[th in role=table](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/th-table-test.html)
[th in role=grid](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/th-grid-test.html)
[th in role=treegrid](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/th-treegrid-test.html)

expectations:
*  if a `<td>`'s ancestor table element has role=table, grid or treegrid - then no allowed role.
*  if a `<th>`'s ancestor table element has role=table, grid or treegrid - then no allowed role.
*  if a `<tr>`'s ancestor table element has role=table, grid or treegrid - then no allowed role.
* if any use of `cell`, `gridcell`, `row`, `rowheader`, `columnheader` are found on these elements - then those should  produce warnings as being unnecessary

if a td, tr, or th are used within a table with no set role, thus it should be an implicit role=table (regardless of what browser heuristics may do) - then no allowed role
[td within a table testcase](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/td-test.html)
[th within a table testcase](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/th-test.html)
[tr within a table testcase](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/tr-test.html)

If td, tr, or th are used within a table where it's role is overwritten by a role not mentioned above (e.g., role=none, article, etc), then these elements can continue to allow any role.  **the checker already meets this expectation**

**Comment by MHoov** [comment]
As of June 1
- [x] general rule description (SME & Dev)
- [x] testcases written (Dev)
- [ ] rule developed  (Dev)
- [ ] message written (SME)
- [ ] help written (SME)

**Comment by tombrunet** [comment]
@carmacleod @philljenkins We created a new rule for this one, but then we updated the allowed ARIA roles, so we end up with two errors. Which error do you think we should remove? 
![image](https://user-images.githubusercontent.com/19577713/146449217-f1c5cc9b-8428-4cb7-af70-dc8750d30303.png)

Note that the first one even triggers when the role is redundant (e.g., cell on a td) whereas the second will not trigger when redundant. The second seems more consistent with the note that this case should be a warning.

**Comment by scottaohara** [comment]
As an FYI, we have received some feedback that allowing explicit declaring of implicit roles on tables and their children should be reduced to a warning, or not reported.  e.g., table role=grid > tr > td role=gridcell   this is specifically due to some browsers still dropping table semantics due to CSS styling. 

I don't know if this helps or hinders the decision here, but as this popped up in my github notifications, I wanted to let you know that we were going to clarify this in an upcoming update to these rules.

**Comment by carmacleod** [comment]
@tombrunet I think we should remove the first rule and keep the 2nd. We don't want to trigger on explicit declaring of implicit roles, although we should discuss whether those should be "needs review".

**Comment by aliunwala** [comment]
Triage:
This is as simple as removing a rule from the ruleset. We will have SME's take a look at this to confirm which we want to deprecate and pass it to dev.

**Comment by shunguoy** [comment]
#721 covers updated ARIA attributes but doesn't cover users explicitly specifying a role that is implicitly available.   The second case needs to be considered in a different rule.

**Comment by shunguoy** [comment]
close as fixed per #789

**Comment by eirckr** [comment]
Validated
