### ISSUE TITLE
[BUG] List of Accessibility Requirements accordion is broken

### ISSUE THREAD

**Issue by carmacleod** [IBMa/equal-access#384]
Windows 10
Chrome Version 89.0.4389.114 (Official Build) (64-bit)
Edge Version 89.0.774.68 (Official build) (64-bit)
Firefox Version 88.0b8 (64-bit) << not a problem in Firefox

The accordion sections on https://www.ibm.com/able/requirements/requirements/ aren't expanding for me in either Chrome or Edge. I cannot click on them, or focus them and type enter or space, or click on the expand all button.

The accordion works ok in Firefox.

**Comment by maryjom** [comment]
@carmacleod Another glitch today when we updated the site. Should be fixed now.

**Comment by carmacleod** [comment]
@maryjom Yep! Works now. I'll close this. Thanks!
