### ISSUE TITLE
Can't navigate to error node in shadow DOM

### ISSUE THREAD

**Issue by wkeese** [IBMa/equal-access#385]
## What tool(s) are you using?

- `accessibility-checker`

## Detailed description

See the test case in #363.   The preview version now correctly detects an error inside the shadow DOM:

<img width="543" alt="Screen Shot 2021-04-12 at 8 56 54" src="https://user-images.githubusercontent.com/69599/114325908-5da88d80-9b6d-11eb-83a0-18dfac2c9759.png">

However, there are two (related?) issues with the report panel:

(1) The path is wrong, it says /document[1]/main[1]/textbox[2] but it should be something like  

* /document[1]/main[1]/div[1]/#document-fragment[1]/input[1]
* /document[1]/main[1]/div[1]/shadow()/textbox[1]
* /document[1]/main[1]/div[1]/textbox[1]

(2) More importantly clicking the message part doesn't navigate to the node with the problem.   (Of course, I'm talking about when running from Chrome, not command line.)

I'm also (possibly relatedly) getting an exception in the console:

/html[1]/body[1]/main[1]/div[1]/#document-fragment[1]/input[1] TypeError: Cannot read property 'getElementsByTagName' of null

PS: I'm not sure how you write an XPath for shadow-dom, but I did find https://medium.com/@mangolik931/xdompath-vs-xpath-or-new-query-language-which-can-handle-shadowdom-7c7589800bb4.

**Comment by tombrunet** [comment]
There were some changes to the extension that haven't been deployed yet. If you're adventurous and want to try the latest, you can download it an install it in developer mode detached from the store: https://github.com/IBMa/equal-access/actions/runs/723699033 (but won't auto update). We'll double check to see how this is behaving on that build though.

**Comment by tombrunet** [comment]
We discovered that our xpath selection logic doesn't work within the document fragments used by shadow doms. This is fixed by https://github.com/IBMa/equal-access/pull/400. Will be fixed in the next release, which should be coming soon.

**Comment by wkeese** [comment]
Cool, this is working for me now, thanks!

It just lists the xpath as `/document[1]/main[1]/textbox[2]` with no indication of the a shadow-dom root (or whatever you call it), but I guess that's OK.

**Comment by tombrunet** [comment]
Correct - it's not an xpath, but rather a hierarchy of ARIA roles that a screen reader would be aware of. A screen reader would not be aware of the shadow DOM, so it's not included.
