### ISSUE TITLE
[Rules] Revised ARIA in HTML rules for img alt=""

### ISSUE THREAD

**Issue by scottaohara** [IBMa/equal-access#391]
for an [`img alt=""`](https://thepaciellogroup.github.io/aria-test-builder/dist/testcases/img-emptyalt-noARIA-test.html) ARIA in HTML was updated to indicate `role=none` and `role=presentation` are redundant to the implicit ARIA role.  These roles should be marked as invalid, or at least flagged as a warning to authors for their redundancy

**Comment by MHoov** [comment]
As of June 1
- [x] general rule description (SME & Dev)
- [ ] testcases written (Dev)
- [ ] rule bug (Dev)
- [x] message written (SME)
- [x] help written (SME)

**Comment by tombrunet** [comment]
If I understand this, it's asking to flag this because the role is redundant:
```html
<img alt="" role="none" />
```

Redundancy doesn't cause failures since it will show up the same in the accessibility hierarchy. It's not a 'bug' to not flag it. Changing this to an 'enhancement' to consider how to warn, or if that will cause developers too much noise.

**Comment by mbgower** [comment]
As a side conversation, I'd like to discuss the impact this has on the ability of screen readers to provide personalizations to end users.

**Comment by marcjohlic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Equal-Access-61ae71f9f8b4ec001e136462/issues/IBMa/equal-access/391?planning-poker) with ZenHub @aliunwala @drjoho @mbgower @philljenkins @shunguoy @tombrunet

**Comment by shunguoy** [comment]
close as fixed per #800

**Comment by eirckr** [comment]
Validated
