### ISSUE TITLE
Request for Node 14 support

### ISSUE THREAD

**Issue by jeffchew** [IBMa/equal-access#393]
### Summary

Our team is looking into upgrading to Node 14. However, it looks like `karma-accessibility-checker` is only supported for Node 10 and 12. Are there plans to add support for Node 14? Node 14 went into LTS not too long ago.

This is a development request.

### Justification

Our team, as well as any newer IBM application teams, may opt to use the latest LTS version of Node, which would prevent them from using `karma-accessibility-checker`.

### "Must have" functionality

Allowed `engines` in `package.json` to include Node 14

**Comment by tombrunet** [comment]
Will be tracked in https://github.com/IBMa/equal-access/pull/408

**Comment by tombrunet** [comment]
See 3.1.6
