### ISSUE TITLE
[Java Checker] Enhancement: Create a port for Java / Selenium

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#398]
### Summary

There have been one or two requests to port over for a Java/JUnit/Selenium environment. This issue will cover the basic porting of code. Other issues will be created with the [Java Checker] prefix to cover deployment, test, etc.

**Comment by tombrunet** [comment]
Will use branch `java`

**Comment by MHoov** [comment]
Received another [slack request for a Java tool on 7/27/24](https://ibm-studios.slack.com/archives/C036P1CTN/p1721853217638529?thread_ts=1721851011.702689&cid=C036P1CTN
)
