### ISSUE TITLE
[BUG][Rules] Potential false positive reported for "unlabeled" menu items

### ISSUE THREAD

**Issue by dakahn** [IBMa/equal-access#413]
Details, steps to recreate etc in this issue on the Carbon repo
https://github.com/carbon-design-system/carbon/issues/8553

Testcase: https://react.carbondesignsystem.com/iframe.html?id=experimental-unstable-menu-contextmenu--context-menu

Note: Open the context menu (right click in the test case) and then scan.

**Comment by tombrunet** [comment]
Yes, looks like a false positive. https://www.w3.org/TR/wai-aria-1.2/#menuitemcheckbox allows name from contents. I suspect the rule may have missed that case.

**Comment by MHoov** [comment]
As of June 1
- [ ] general rule description (SME & Dev)
- [ ] testcases written (Dev)
- [ ] rule developed / bug (Dev)
- [ ] message written (SME)
- [ ] help written (SME)

**Comment by shunguoy** [comment]
https://github.com/IBMa/equal-access/pull/656

**Comment by eirckr** [comment]
Not ready for QA per dev.

**Comment by shunguoy** [comment]
@eirckr  ready for QA

**Comment by eirckr** [comment]
@shunguoy Test case under carbon ticket is no longer available https://react.carbondesignsystem.com/?path=/story/experimental-unstable-contextmenu--context-menu

Please provide a test case for validation.

**Comment by shunguoy** [comment]
@eirckr   our test cases include some unit test cases

**Comment by shunguoy** [comment]
during cleaning up my old branches, I accidentally hit a merge. There were commits from other members, looks like there is no safe way to undo the merge. @eirckr  can you test the master branch?  If you find something wrong, I make a new branch to fix it. thanks

**Comment by eirckr** [comment]
Validated
