### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Nerea90** [IBMa/equal-access#429]
## What tool(s) are you using?

- [ ] `accessibility-checker-engine`
- [ ] `accessibility-checker`
- [ ] `karma-accessibility-checker`
- [ ] `rule-server`
- [ ] `boilerplates`
- [ ] `other`

## Detailed description

> Node version:
> Platform: 

> Describe in detail the issue you're having.

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by tombrunet** [comment]
No information provided
