### ISSUE TITLE
[BUG] Punctuation inconsistencies with the website

### ISSUE THREAD

**Issue by Kyle-Alvares** [IBMa/equal-access#437]
## Title line template: Minor Style Inconsistencies: Lists punctuation, ellipses.

1. Go to https://www.ibm.com/able/toolkit/verify/manual/ 

2. Navigate to: Confirm page interaction -> Maintaining Users Point

<img width="824" alt="Screen Shot 2021-06-01 at 12 49 11 PM" src="https://user-images.githubusercontent.com/55460977/120486440-0a8bd380-c383-11eb-8c7e-34a500c45499.png">

This is the only point with a period.

3. Colons should be used in lieu of ellipses (this applies for each topic).

<img width="697" alt="Screen Shot 2021-06-02 at 9 16 50 AM" src="https://user-images.githubusercontent.com/55460977/120486814-62c2d580-c383-11eb-8b0e-d736ea8ca996.png">

Reference: https://ibmdocs-test.mybluemix.net/docs/en/ibm-style?topic=format-lists

**Comment by marcjohlic** [comment]
Internal issue created for tracking  https://github.ibm.com/IBMa/E2E/issues/3852

**Comment by marcjohlic** [comment]
Will be tracking this via the internal repo linked above.  Closing this external issue.
