### ISSUE TITLE
Does the extension collect data on the user or website or other

### ISSUE THREAD

**Issue by DusanMilko** [IBMa/equal-access#440]
Hello, does the extension collect any data on the user, website/application being used on, or any other data?

The privacy practice on chrome says data isn't collected:
https://chrome.google.com/webstore/detail/ibm-equal-access-accessib/lkcagbfjnkomcinoddgooolagloogehp

But the privacy policy from the page says there may be data collected:
https://www.ibm.com/privacy

What is the official status on what data if any the extension collects?

**Comment by tombrunet** [comment]
We ping back information about performance so that we can determine if new rules are running too slowly. For example:
> t=ac-extension&tag=Chrome%2F91.0.4472.77%20Safari%2F537.36&a=&pol=IBM_Accessibility&st=39

This tells us that a scan with the browser extension on Chrome with the IBM_Accessibility policy took 39 milliseconds to run. No personal/user/site/app data included.
