### ISSUE TITLE
FEATURES.md

### ISSUE THREAD

**Issue by devashish-gaikwad** [IBMa/equal-access#454]
Use this template if you want to request a new feature, or a change to an
existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

The Repository should have a FEATURES.md or at least a features section in the README.md, so that the users can know all the features available.

This is a Documentation request.

### Justification

It is hard to know the exact features provided by the repo, which leads to a disadvantage when comparing with other accessibility solutions available.

### "Must have" functionality

Documentation of the features of the project and sub-projects.

**Comment by tombrunet** [comment]
Can you provide some examples of this in other repositories? Many of the repos that I looked at do not have this file, and the few that do are describing feature flags that can turn on and off features. Googling "FEATURES.md" has almost no hits for this file, so it does not appear to be a standard file to provide.

**Comment by devashish-gaikwad** [comment]
Hi,
It is true that there are no examples,

What I want to convey that we should have a features section in the README.md or FEATURES.md file ;)

My bad, I should have framed it better !

**Comment by MHoov** [comment]
Features list added to Accessibility-Checker ReadMe.md
