### ISSUE TITLE
[BUG] AVT reported "Form control element <select> has no associated label" for angular components 

### ISSUE THREAD

**Issue by ttliang** [IBMa/equal-access#469]
- [ ] `accessibility-checker-engine`
- [x] `accessibility-checker`
- [ ] `karma-accessibility-checker`
- [ ] `rule-server`
- [ ] `boilerplates`
- [ ] `other`

## Detailed description

 > Platform: MacOS V11.4, FF 90.0.2 (64bit), IBM Accessibility Equal Access Accessibility Checker  Version 3.1.9

## Additional information
 Mis-report violations for form elements controllers about angular components (ibm-search, ibm-checkbox, ibm-radio)
- Screenshots or code

Elements that report "Form control element <input> has no associated label" although they have.
Screencuts :
![Screencut-AVT-Select element has no label-1](https://user-images.githubusercontent.com/12162531/128163773-a6b9ba08-53c5-4c42-95af-677c070a2201.png)
![Screencut-AVT-Select element has no label-2](https://user-images.githubusercontent.com/12162531/128166274-6c30c7b2-7ad9-4642-926b-ef904ce2ffc7.png)

- Code
```
<ibm-pagination _ngcontent-uvl-c0="">
  <div>
    <div>
      <label for="pagination-select-items-per-page-13"> Items per page: </label>
      <div>
        <select id="pagination-select-items-per-page-13">
          <option value="10"> 10 </option>
          ...
        </select>
      </div>
      <span> 1-10 of 12 items </span>
    </div>
    <div>
      <div><label for="pagination-select-current-page-13">Items per page:</label>
        <select id="pagination-select-current-page-13">
          <option value="1">1</option>
        ...
        </select>
      </div>
      <div>
        <button aria-label="Backward" disabled=""></button>
        <button aria-label="Forward"></button>
      </div>
    </div>
  </div>
</ibm-pagination> 
```

**Comment by tombrunet** [comment]
Similar to #468 the violation you mention doesn't trigger for the DOM you provided. Need more information.

**Comment by dbrandl28** [comment]
Hi Tom. We are using Firefox. We are using IBM Equal Access
Accessibility Checker
Version 3.1.9
Currently active: Latest Deployment
Currently active: IBM Accessibility

This is the same system you are using to debug another issue with Shari: https://pev173.pok.ibm.com/zosmf/
These violations show up when scanning the first Software Update page with the tab "View Updates in Progress" selected.

**Comment by tombrunet** [comment]
Opened #471 since these are all related, but the error is not as described. Essentially, there's a bug in our code for clearing some cache data between scans inside of the frames.

**Comment by tombrunet** [comment]
This is now fixed in the `preview` rule set. You should be able to find it at the bottom of the rule set list in the extension options.
