### ISSUE TITLE
[BUG] Level filters aren't followed on rescan

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#470]
## What tool(s) are you using?
* Chrome extension

## Steps to reproduce the issue

1. Scan a page
2. Uncheck the "Needs Review" and "Recommendation" checkboxes
3. Scan the page again
Needs Review and Recommendations show up again, but the checkboxes aren't checked. You have to check the box and uncheck it to remove them again.

![image](https://user-images.githubusercontent.com/19577713/128881586-f7391391-0ab8-40cd-9d97-d59d663694d5.png)

**Comment by drjoho** [comment]
I have reproduced the issue and will investigate.

**Comment by tombrunet** [comment]
Fixed
