### ISSUE TITLE
[BUG] Engine not clearing cache within frames

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#471]
See example https://codesandbox.io/s/issue-471-s00e5

On subsequent scans, false positives are flagged. Looks like the cache isn't properly being cleared inside the frame. Suspect `clearCaches` isn't walking inside the frame, but need to check. Also need to ensure all frame `document` object caches are cleared.

**Comment by tombrunet** [comment]
This is now fixed in the `preview` rule set. You should be able to find it at the bottom of the rule set list in the extension options.

**Comment by dbrandl28** [comment]
Much better!  Thank you for fixing this so quickly!
