### ISSUE TITLE
[BUG] AVT Extension mis-report violation "Form control element <input> has no associated label"

### ISSUE THREAD

**Issue by ttliang** [IBMa/equal-access#474]
- [ ] `accessibility-checker-engine`
- [x] `accessibility-checker`
- [ ] `karma-accessibility-checker`
- [ ] `rule-server`
- [ ] `boilerplates`
- [ ] `other`

> Node version:
> Platform: MacOS 11.4, Firefox: 90.0.2(64bit)

> Describe in detail the issue you're having.

## Additional information

- Screenshots or code
![image](https://user-images.githubusercontent.com/12162531/129133832-77bc9d2b-0895-4d44-87b6-d20f33948180.png)
![image](https://user-images.githubusercontent.com/12162531/129133849-aae9aa28-0e69-46cb-9dc7-3896c57c0777.png)

```
<ibm-radio _ngcontent-uvl-c0="" class="dashboardZones bx--radio-button-wrapper" name="zoneRadio" aria-label="TGT">
  <!----><input class="bx--radio-button" type="radio" name="zoneRadio" id="radio-163" value="[object Object]" aria-labelledby="label-radio-163">
  <!----><label class="bx--radio-button__label" aria-label="" for="radio-163" id="label-radio-163">
                <span class="bx--radio-button__appearance"></span> 
             TGT </label>
</ibm-radio>
```

- Notes

**Comment by tombrunet** [comment]
Are you running with the preview ruleset? The other issues you reported were similar and were all related to the same bug fixed in the preview ruleset.

**Comment by tombrunet** [comment]
I ran this code with the preview ruleset and it does not trigger. Closing.

**Comment by dbrandl28** [comment]
@tombrunet I'm running the scan with the preview rule set and it does trigger for me.  I see it on both Firefox 78.13.0esr and Chrome Version 92.0.4515.131

**Comment by dbrandl28** [comment]
@tombrunet Thank you Tom.  I'll have the developer look into it.
