### ISSUE TITLE
[Rules] Update allowances for the area element without href

### ISSUE THREAD

**Issue by scottaohara** [IBMa/equal-access#515]
The *`area` element without `href`* presently does not allow any role to be specified by authors.  The [ARIA in HTML specification is updating this restriction](https://github.com/w3c/html-aria/pull/360) to allow authors to specify a `button` or `link` role. 
```html
<map name=...>
  <area shape=rect coords=... alt=accName role=button> <!-- pass -->
  <area shape=rect coords=... alt=accName role=link> <!-- pass -->
</map>
```

All other roles would continue to not be allowed on the the `area` element if it lacks an `href`.

As without the `href` the `area` would no longer be keyboard focusable, conformance checkers may surface a warning stating this.  However, this will not be a requirement from ARIA in HTML.

**Comment by tombrunet** [comment]
Testcase: https://codesandbox.io/s/issue-515-jrkn2
