### ISSUE TITLE
[Extension] Means of scanning content that disappears when it blurs

### ISSUE THREAD

**Issue by Paul-Grogan** [IBMa/equal-access#519]
### Summary

Pop-ups (e.g. flyout menus, tooltips, dropdowns) typically close when they loose focus, such as activating the EAAC's Scan button. Providing an option to set a delay on starting the scan would allow for these popups to be opened after the scan button has been pressed. Resulting in them being included in the scan.

A variable delay may be useful for complex setups, but at a minimum even a short fixed delay would be useful.

Clarify if you are asking for design, development, or both design and
development. - Development

### Justification

It is difficult to use the EAAC tool to check the accessibility of our application's popups, tooltips, dropdowns, flyouts, etc. because clicking the Scan button will close the element that we want to test resulting in the scan missing it.

### "Must have" functionality

A new scan button (adjacent to the existing one) that activates the scan after a short fixed delay.

**Comment by aliunwala** [comment]
Thoughts during the Triage meeting: 
1) Thoughts around maybe adding a shortcut key to trigger scan
2) Time delayed scan (as above)

Adding this ticket to backlog to be looked at a later date.

**Comment by marcjohlic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Equal-Access-61ae71f9f8b4ec001e136462/issues/IBMa/equal-access/519?planning-poker) with ZenHub @aliunwala @drjoho @mbgower @philljenkins @shunguoy @tombrunet

**Comment by tombrunet** [comment]
Added a solution to this into the refresh PR: https://github.com/IBMa/equal-access/pull/1371. Next release should support this. We'll discuss if the key makes sense, but at the moment it is ctrl+alt+s on Windows or ctrl+option+s on Mac. Pressing the key combination will trigger a scan without moving focus to the extension panel.
