### ISSUE TITLE
Update role allowances for section element to include group

### ISSUE THREAD

**Issue by scottaohara** [IBMa/equal-access#528]
ARIA in HTML is updating the `<section>` element to allow authors to specify `role=group`.

https://github.com/w3c/html-aria/pull/367

**Comment by tombrunet** [comment]
Referenced issue is still open. Sandbox testcase for when it's ready: https://codesandbox.io/s/issue-528-ktuyg

**Comment by scottaohara** [comment]
@tombrunet the referenced issue / PR is opened as we are pushing changes based on implementation commitment.  If you were to indicate commitment, then we would have 2 implementations needed to merge.

**Comment by tombrunet** [comment]
https://github.com/IBMa/equal-access/pull/561

**Comment by scottaohara** [comment]
Thank you much!

**Comment by tombrunet** [comment]
Deploying to preview. Should be there in about 30 mins
