### ISSUE TITLE
[Rules] Remove ARIA role allowances for iframe, object, embed

### ISSUE THREAD

**Issue by scottaohara** [IBMa/equal-access#542]
ARIA in HTML is updating the `iframe`, `object` and `embed` elements to no longer allow any explicit ARIA roles, as specifying these roles have been found to cause unexpected issue with AT/browsers - https://github.com/w3c/html-aria/pull/370

**Comment by tombrunet** [comment]
It looks like the referenced issue is still under discussion. Going to leave this one alone until that gets settled.

**Comment by mbgower** [comment]
Use of role="presentation" is a common means of dealing with these.

**Comment by tombrunet** [comment]
Left a comment in https://github.com/w3c/html-aria/pull/370 . I'm not convinced that this spec should be enforcing something that seems to be a disagreement between ARIA and the browser vendors.

**Comment by tombrunet** [comment]
@scottaohara Any progress on this? It seems that the proposal is not well supported.

**Comment by scottaohara** [comment]
the proposal is going to change. Just have not had any free cycles to work on the effort to update the spec text and finish all the test results.

I will close the original PR in ARIA in HTML and will likely create new separate PRs and issues for each of the different elements. 

Thanks for the reminder
