### ISSUE TITLE
[BUG]Cannot use Accessibilty checker on Chrome or firefox

### ISSUE THREAD

**Issue by panlei080988** [IBMa/equal-access#552]
## What tool(s) are you using?

- [ ] `accessibility-checker-engine`
- [x] `accessibility-checker`
- [ ] `karma-accessibility-checker`
- [ ] `rule-server`
- [ ] `boilerplates`
- [ ] `other`

## Detailed description

> Node version:3.1.12
> Platform: Chrome & Firefox

> Describe in detail the issue you're having.
I try to scan a page with it, but there is no result displayed. And when I try to open the option page for the tool, an error is occured(See below screenshot).

## Steps to reproduce the issue

1. Open "https://www.ibm.com/sg-en"
2. Scan page with the accessibiltiy checker tool

## Additional information

- Screenshots or code
![image](https://user-images.githubusercontent.com/18432988/143828367-015695f5-b981-4d89-9108-7efd5bd84238.png)
![image](https://user-images.githubusercontent.com/18432988/143829061-38feb9b0-a035-423f-9e89-9e4dec2f3279.png)

- Notes

**Comment by tombrunet** [comment]
The certificate on the rule server expired. I submitted for it to be updated a few weeks back - trying to figure out who to escalate to.

**Comment by tombrunet** [comment]
Fixed now. Please confirm.
