### ISSUE TITLE
[Rules] Remove aria-* allowances from datalist element

### ISSUE THREAD

**Issue by scottaohara** [IBMa/equal-access#563]
[ARIA in HTML](https://github.com/w3c/html-aria/pull/383) is updating the `datalist` element to no longer allow any `aria-*` attributes.  

In reality specifying global `aria-*` attributes, or attributes which can be used with the implicit `listbox` role have no actual impact on the element or its child options. Due to this, while there appears to be no negative impact for users to specify ARIA attributes on the element, allowing authors to do so also serves no benefit, and this should be called out to them.

[test case](https://w3c.github.io/html-aria/tests/datalist-aria-attrs.html)

**Comment by eirckr** [comment]
Thanks for the ticket @scottaohara, we will review and get back to you.

**Comment by mbgower** [comment]
Investigating internally in https://github.ibm.com/IBMa/E2E/issues/3894

**Comment by shunguoy** [comment]
@scottaohara this seems not in the current ARIA in HTML yet.  https://w3c.github.io/html-aria/#el-datalist.  If this is the case, I will close the issue.

**Comment by scottaohara** [comment]
@shunguoy in the OP of this issue is a link to the PR of ARIA in HTML. The PR contains the link to the preview that has the change to the spec.  You can see that here - https://pr-preview.s3.amazonaws.com/w3c/html-aria/pull/383.html#el-datalist.  

The spec is adhering to a 'living standard' type model, where we merge changes once we get two implementation commitments from checkers.  Right now we have a single implementation of this rule, and indicators from 3 that they have acknowledged the rule change, but have yet to get a stated commitment.  If you respond that Equal Access will commit to implementing this rule, then I can merge in the rule.

**Comment by scottaohara** [comment]
@shunguoy letting you know that this change was merged into the spec

**Comment by shunguoy** [comment]
@scottaohara thanks.

**Comment by shunguoy** [comment]
this is to (1) update the engine aria-definition, and (2) update the existing test cases to correct the expected results and add new test cases for additional tests.

**Comment by shunguoy** [comment]
The current rule RPT_ARIA_ValidPropty needs to be updated to report all the violating ARIA attributes (current only report one). For example, none of the aria attributes is valid: 
`<datalist id="f" aria-activedescendant="ex" aria-atomic="false" aria-busy="false" aria-controls="ex" aria-current="true" aria-describedby="ex" aria-details="ex" aria-disabled="true" aria-dropeffect="move" aria-flowto="ex" aria-grabbed="false" aria-hidden="true" aria-keystrokes="f" aria-label="tester" aria-labelledby="ex" aria-live="off" aria-orientation="vertical" aria-owns="ex" aria-relevant="text" aria-roledescription="broken" aria-errormessage="ex" aria-expanded="false" aria-invalid="true" aria-multiselectable="false" aria-readonly="true" aria-required="false">`

**Comment by shunguoy** [comment]
There are potentially two rules related need to discuss and modified, see the box note: https://ibm.ent.box.com/notes/994215482156

**Comment by shunguoy** [comment]
This needs to be expanded to cover the elements that have an implicit role but disallow some or all attributes allowed for that role.

**Comment by shunguoy** [comment]
working on modifying the aria definition in the engine.   To add a list of elements that have an implicit role but disallow some or all attributes allowed for that role.

**Comment by shunguoy** [comment]
this will be merged together with #1034 to the master

**Comment by eirckr** [comment]
@shunguoy same results as we talked before using local build: 
<img width="1557" alt="Screen Shot 2022-09-07 at 6 02 43 PM" src="https://user-images.githubusercontent.com/62436670/188998248-0f200526-fc55-4b18-9db7-83facbf6cf5d.png">

**Comment by eirckr** [comment]
Per dev: 

The result is correct:  the aria_attribute_allowed depends on “Rpt_Aria_ValidProperties” rule.  It means if the “Rpt_Aria_ValidProperties” rule fails (which is the case), then the  aria_attribute_allowed rule won’t be triggered.   So you have to use the test case in the github to see the message.

The message “The attribute(s) ‘aria-keystrokes’ referenced by the element <DATALIST> is not a valid ARIA state or property”. is from the “Rpt_Aria_ValidProperties” rule.

**Comment by shunguoy** [comment]
The attribute ‘aria-keystrokes’ is not a valid aria attribute.

**Comment by eirckr** [comment]
Validated
