### ISSUE TITLE
A11y Assessment scan button should include the same features in the dropdown as the A11y Checker

### ISSUE THREAD

**Issue by snidersd** [IBMa/equal-access#582]
### Summary
A11y Assessment scan button should include the same features in the dropdown as the A11y Checker. This is both a both design and development change.

### Justification
User reported that they expected to see the drop down, but they didn't realize they were in the audit view.

### "Must have" functionality
Below is a screen shot of the A11y Checker view scan button with the drop down in Firefox.
<img width="1104" alt="Screen Shot 2021-12-16 at 10 10 33 AM" src="https://user-images.githubusercontent.com/21676914/146412178-c62b9be0-1f08-45d0-8d08-54439c7d46ca.png">
and this is the A11y Assessment view scan button without the drop down in Firefox.
<img width="1110" alt="FF-audit" src="https://user-images.githubusercontent.com/21676914/146412303-8d51314d-da59-4851-81dc-d3e8bef45a93.png">

**Comment by tombrunet** [comment]
@drjoho Was this intentionally not in both views? If it was supposed to be in both views, please tag as `bug` (remove `enhancement`) and move to `backlog`. If anything, multi-scan feels more important in the 'auditor' view.

**Comment by aliunwala** [comment]
@drjoho Please take a look at this one

**Comment by drjoho** [comment]
At the time this was implemented the multi-scan reports we decided to not be needed for the Assessment View. If fact there were discussions of removing the Assessment View. So it would not be difficult to add if the team feels that it is needed.

**Comment by aliunwala** [comment]
Comments during Triage meeting: This view is important for auditor users to allow for multiple scans. So we should probably add this.

**Comment by marcjohlic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Equal-Access-61ae71f9f8b4ec001e136462/issues/IBMa/equal-access/582?planning-poker) with ZenHub @aliunwala @drjoho @mbgower @philljenkins @shunguoy @tombrunet

**Comment by MHoov** [comment]
@tombrunet @drjoho has this been addressed with the tree grid work? thanks

**Comment by drjoho** [comment]
@MHoov DONE
![image](https://user-images.githubusercontent.com/64442976/228344431-cfa8f323-69be-40fd-99da-924e75b3d111.png)
