### ISSUE TITLE
[Extension]: Need some means of figuring out the rule id of a triggered rule

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#595]
### Describe what needs to be accomplished
Difficult to know which rule is associated to the Help displayed.  End user has to look at list of issues in report view to find the RuleID, and then try to find that issue in the Checker list, and then find the rule help.  

Note: Ideally this issue should be a 1 day task.
* [ ] Propose some options of where to show RuleID on the Help page (bottom right, with Copy icon, etc. (Design)
* [ ] Add RuleID per design to the 160+ /help/....mdx files (SME)

### Why does this need to be accomplished
* Enables users and SMEs when opening issues against a specific rule to know its RuleID.
* Enable developers to associate the rule help with the rule logic.
* Helps us identify rule id for development changes

### Related issues or references
* From https://github.ibm.com/IBMa/E2E/issues/3471

### Supporting notes and details
* simple design task of deciding where to place the RuleID text string and how to display its font style and size

**Comment by tombrunet** [comment]
Let's have the extension inject the ruleid (and maybe reason code) at the bottom of the help.

**Comment by aliunwala** [comment]
Connecting this PR:
https://github.com/IBMa/equal-access/pull/706

**Comment by aliunwala** [comment]
Most up to date screenshots are in the PR
