### ISSUE TITLE
ARIA required context role should be restricted to direct parent-child relation for rule Rpt_Aria_RequiredChildren_Native_Host_Sematics - 279

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#600]
Issue opened by Shunguo:

refer to https://ibm.ent.box.com/notes/853811645784 and https://act-rules.github.io/rules/ff89c9 

The current implementation checks the context root in parent-descendant, rather than direct parent-child relation.   

- [ x] general rule description (SME & Dev)
- [x]  testcases written (Dev)
- [x]  rule bug (Dev)
- [x ]  message written (SME)
- [x]  help written (SME)

Link to original issue:
https://github.ibm.com/IBMa/accessibility-web-engine/issues/279

Image of original issue:
![image.png](https://images.zenhubusercontent.com/61bb8e6b2e4f8534832597ac/e884e3c2-c95e-47a5-b3e8-f0abd937f481)

**Comment by aliunwala** [comment]
We need a test case for this one. So this can be reproduced.

The ACT test case is not valid so a new one is needed.

**Comment by tombrunet** [comment]
https://codesandbox.io/s/issue-600-gfh33e

I think the trick here is that an element with a role of none/presentation (implicit or explicit) gets a generic role if it is using global aria attributes?

**Comment by shunguoy** [comment]
my question: should a div with an aria attribute always have a semantic, and require a role?

**Comment by shunguoy** [comment]
we need to support a generic role if an element has a global aria attribute.

**Comment by shunguoy** [comment]
1. box note: https://ibm.ent.box.com/notes/988392667400
2. may need SME for updating messages and help content.

**Comment by shunguoy** [comment]
noticed some issues with the rule messages which might confuse end users. a second rule meeting with Tom and Phil to update the rule messages, see https://ibm.ent.box.com/notes/988392667400.  Both rule logic and the test cases need to be updated with the updated messages.

**Comment by shunguoy** [comment]
change the logic based on the 2th rule discussion result, and revisit test cases (about 40) one by one.

**Comment by shunguoy** [comment]
change the logic based on the 2th rule discussion result, and revisit test cases (about 40) one by one.

**Comment by shunguoy** [comment]
rule implementation and test cases completed, pending for help content

**Comment by shunguoy** [comment]
need to do the baseline tests and changes if needed.

**Comment by shunguoy** [comment]
Added a new case for presentational tables with role="none | presentation" where the parent-child relationship may not be required.
