### ISSUE TITLE
Investigate ACT copyright requirements and usage - 3683

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#603]
Issue created by Mike:
During Help content creation for a new rule, [Phill asked](https://github.ibm.com/IBMa/E2E/issues/3646#issuecomment-36743613) about any requirements for using the ACT samples.

Shunguo cited the [copyright requirements](https://act-rules.github.io/rules/a25f45#test-cases) for ACT material. This issue is to investigate when and how we should ensure we meet this requirement.

Link to original issue:
https://github.ibm.com/IBMa/E2E/issues/3683

Image of original issue:
![image.png](https://images.zenhubusercontent.com/61bb8e6b2e4f8534832597ac/63f3a27e-e780-4c25-a28a-f58c7454d0f4)

**Comment by aliunwala** [comment]
Comment from Phil:
Help style guide also asks us to provide attribution where possible:
> Try to avoid copying W3C examples.  If you do, include a Copyright acknowledgment.

**Comment by aliunwala** [comment]
Comment from Marc:
It sounds like this is the answer:

> Try to avoid copying W3C examples. If you do, include a Copyright acknowledgment.

Rather than "investigate", I think we use this issue to now check for recent Help that was created and add the W3C attribution to the bottom of the Help.

**Comment by aliunwala** [comment]
During triage meeting:
This initial investigation should not take too much time.

**Comment by aliunwala** [comment]
https://github.com/act-rules/act-rules.github.io/blob/develop/LICENSE.md

**Comment by mbgower** [comment]
I'd suspect adding the Copyright ack to w3c would be faster?

**Comment by mbgower** [comment]
@shunguoy previously said 
> Though a good thing, I don't think we need an acknowledgment & copyright to all new ACT copied test cases simply because they are from a community effort and not copyrighted. As with any standard, its purpose is to encourage people to use it, the more, the better. Also, the way we are using them is to copy over certain or all code snippets and stack them into our own frame. Instead, I suggest we remove the IBM copyright statement from all the test cases so people can freely copy and use them.

**Comment by mbgower** [comment]
Suggested wording:
> This software or document includes material copied from or derived from [ACT-Rules Community](https://act-rules.github.io/pages/about). Copyright © 2022 W3C® (MIT, ERCIM, Keio, Beihang).

**Comment by mbgower** [comment]
@philljenkins do we have a quick way of determining when we've drawn code examples or tests directly from ACT-Rules?

**Comment by mbgower** [comment]
Investigate if we can embed in the code one time, instead of in the help files where it is used.
Then close.

**Comment by mbgower** [comment]
Rereading the [licence](https://act-rules.github.io/pages/license/), it appears to be adequate if we included this information once, say as a readme.
I have scheduled a brief call to discuss.

**Comment by mbgower** [comment]
@tombrunet I wanted to make sure that you got the wording @philljenkins and I worked out 
> This software includes material copied from or derived from the open [ACT-Rules Community](https://act-rules.github.io/pages/license/). Copyright © 2022 W3C® (MIT, ERCIM, Keio, Beihang).
