### ISSUE TITLE
Indicate that role=directory will be deprecated (aria 1.2)

### ISSUE THREAD

**Issue by scottaohara** [IBMa/equal-access#608]
[ARIA 1.2 is deprecating the `directory` role](https://www.w3.org/TR/wai-aria-1.2/#directory), as in reality it had no practical difference between a `role=list`.  

ARIA in HTML is being updated to call out that authors should not use this role, and request that conformance checkers warn authors to instead use a HTML list element, or `role=list` instead.

[`role=directory` test case](https://w3c.github.io/html-aria/tests/deprecated-directory.html)

**Comment by tombrunet** [comment]
Need to discuss with team what level deprecated features should be reported at. My gut feels like it should be a recommendation.

**Comment by scottaohara** [comment]
Makes sense.  FYI, I updated the test case to mention additional issues i've found with `role=directory`'s implementation.  Essentially, not only does using `role=directory` on a `ul`, `ol`, or `menu` do nothing to change its exposed mapping, it actually breaks the mapping of the nested `li` elements in Chromium specifically.  So if used, authors need to also specify `role=listitem` on all `li` elements to mitigate this behavior.

**Comment by tombrunet** [comment]
Note: Create a rule where the role is tokenized (Maybe look for a deprecated attribute in the ARIA spec file)

**Comment by aliunwala** [comment]
Agreement in triage into make this into a **Recommendation**

Also a helpful link:
https://www.w3.org/TR/wai-aria-1.2/#deprecated

**Comment by shunguoy** [comment]
close this and reopen for the next sprint per team process: https://github.com/IBMa/equal-access/issues/680

**Comment by shunguoy** [comment]
some deprecated aria attributes/roles were added to the engine, but no test cases were written.
