### ISSUE TITLE
Indicate that aria-grabbed and aria-dropeffect are deprecated

### ISSUE THREAD

**Issue by scottaohara** [IBMa/equal-access#609]
ARIA 1.1 deprecated [`aria-grabbed`](https://www.w3.org/TR/wai-aria-1.1/#aria-grabbed) and [`aria-dropeffect`](https://www.w3.org/TR/wai-aria-1.1/#aria-dropeffect).  While no feature yet exists to replace these attributes, their current support is not particularly great, and since they are deprecated, it is highly unlikely their support will improve.

ARIA in HTML is being updated to call out that authors should not rely on these features, and request that conformance checkers warn authors about the attributes' deprecated status.

[`aria-grabbed` and `aria-dropeffect` test case](https://w3c.github.io/html-aria/tests/deprecated-attrs.html)

**Comment by tombrunet** [comment]
Need to discuss with team what level deprecated features should be reported at. My gut feels like it should be a recommendation.

**Comment by aliunwala** [comment]
Agreement in triage into make this into a **Recommendation**

Also a helpful link:
https://www.w3.org/TR/wai-aria-1.2/#deprecated

**Comment by tombrunet** [comment]
Note: Create a rule where the attribute is tokenized with a list of deprecated attributes (Maybe look for a deprecated attribute in the ARIA spec file)
