### ISSUE TITLE
[Rule Impl] Part 1 style_hover_display_review Test Cases

### ISSUE THREAD

**Issue by mbgower** [IBMa/equal-access#614]
Follow on to #590

Write a rule based on detection of the :hover CSS pseudo class. To start, we will look at where :hover triggers another element to display and ensure the displayed element is the next element in the DOM from the triggering element.

- [x] Review result from Rule Research
- [x] Meet with SMEs to clear up any issues especially regarding scope, failure cases, rule name, level, rule messages
- [x] Investigate similar rules if available and how to determine the context
- [ ] test cases written (Dev) Part 2
- [ ] rule developed (Dev) this will be done in Part 2 or more if needed

Documentation at https://ibm.ent.box.com/file/521562780202

**Comment by drjoho** [comment]
Rule Failures from MG:
0: "the passive message does here"
Pass_0: "the :hover pseudoclass is not used to display content "
Pass_1: "content displayed via the :hover pseudoclass is a direct child of the trigger element"
Fail_0: "the 1stfailmessage goes here,can contain tokens, but not backticks"
Fail_1: "the 2nd fail message goes here, must also harmonize with title messages in help file"
Potential_0:"content displayed via hover may fail 1.4.13 Content on Hover of Focus"

There are three triggers specified:
Fail_0, Fail_1 and Potential_0

However, MG said that only the **Potential_0** trigger needs to be implemented.

**Comment by drjoho** [comment]
Here is a demonstration of failure Potential_0

```
<!DOCTYPE html>
<html>
<head>
    <style>
        div {background-color: yellow;padding: 20px;display: none;}span:hover div {display: block;} 
    </style>
</head>
<body>
    <span>Hover over me2!<div>I will show on hover</div></span>
</body>
</html>```

So

**Comment by drjoho** [comment]
Note: display has 23 possible values need to ascertain what effect these values have when actuated by hover.

**Comment by drjoho** [comment]
<img width="1141" alt="Untitled" src="https://user-images.githubusercontent.com/64442976/150029755-adeda770-7b3c-468d-8432-d7c918868497.png">

**Comment by drjoho** [comment]
<img width="1141" alt="Untitled" src="https://user-images.githubusercontent.com/64442976/150029921-87d5b2fb-188c-4e25-a1f9-e5dbe37a1125.png">

**Comment by drjoho** [comment]
<img width="1141" alt="Untitled" src="https://user-images.githubusercontent.com/64442976/150030089-ce6f062b-3980-4481-b806-acd8ccc940e3.png">

**Comment by drjoho** [comment]
<img width="1141" alt="Untitled" src="https://user-images.githubusercontent.com/64442976/150030761-1f93720e-5842-4764-b59c-66673c30131c.png">

**Comment by drjoho** [comment]
<img width="1141" alt="Untitled" src="https://user-images.githubusercontent.com/64442976/150031710-a4d1f09d-3fa9-45c9-89d0-c242b777e603.png">

**Comment by drjoho** [comment]
<img width="1141" alt="Untitled" src="https://user-images.githubusercontent.com/64442976/150031873-3114b194-85cc-4eaf-b0fb-791758b10fc3.png">

**Comment by drjoho** [comment]
<img width="1141" alt="Untitled" src="https://user-images.githubusercontent.com/64442976/150032109-2ae3a176-dfac-412d-aa1c-4cc54170b930.png">

**Comment by drjoho** [comment]
<img width="1141" alt="Untitled" src="https://user-images.githubusercontent.com/64442976/150032365-bffca150-909c-43e4-8da1-88720a816994.png">

**Comment by drjoho** [comment]
Part 1 is complete I am closing this issue and will open one for Implementation Part 2.

**Comment by mbgower** [comment]
@drjoho I updated the rule name, so updated the name of this issue to match. You may need to update any filenames to style_hover_persistent

**Comment by mbgower** [comment]
See Implementation issues #623 for additional failure cases and code examples.
