### ISSUE TITLE
Allow role=combobox for button and input type=button

### ISSUE THREAD

**Issue by scottaohara** [IBMa/equal-access#618]
[ARIA in HTML](https://github.com/w3c/html-aria/pull/396) is planning to allow `role=combobox` on a `button` and `input type=button` element.  

[`button role=combobox` test case](https://w3c.github.io/html-aria/tests/button-combobox.html)

Additionally, the ARIA in HTML PR adds `role=checkbox` as an allowed role for `input type=button` to match the `button` element allowances.  This was an oversight in the spec which this PR will help correct.

**Comment by aliunwala** [comment]
Thank you Scott for the the issue as well as a nice test case. I will have the team look at this during our weekly prioritization meeting.

**Comment by aliunwala** [comment]
Looks like we will have SME's on our team investigate this issue.

**Comment by marcjohlic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Equal-Access-61ae71f9f8b4ec001e136462/issues/IBMa/equal-access/618?planning-poker) with ZenHub @aliunwala @drjoho @mbgower @philljenkins @shunguoy @tombrunet
