### ISSUE TITLE
[BUG] "Copy link" paperclip icon is cut off

### ISSUE THREAD

**Issue by carmacleod** [IBMa/equal-access#62]
Windows 10/Chrome 81 (latest)

Go to: https://www.ibm.com/able/

Hover over the "Impact" heading part way down the page.
Notice that the paperclip icon ("Copy link") is cut off on the left.

![image](https://user-images.githubusercontent.com/3331913/81845043-fed23280-951d-11ea-9251-c480327a9ef6.png)

Now focus the icon. (this can be done be clicking the icon and then typing shift+tab followed by tab).
Notice that the focus ring on the icon is also cut off.

![image](https://user-images.githubusercontent.com/3331913/81845481-9c2d6680-951e-11ea-93bf-968e799196c1.png)

**Comment by tombrunet** [comment]
This section was redesigned. This was the only header on this particular page with a permalink, so it was inconsistent. On Monday, this one at least should be gone.

**Comment by tombrunet** [comment]
Deployed.
