### ISSUE TITLE
[Rule Impl] group_withInputs_hasName - New rule around groups that have input elements as a child - part 2 #3897 

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#622]
Part 2 of issue:
https://github.com/IBMa/equal-access/issues/605

See original issue for details ^

Initial Ticket:
https://github.ibm.com/IBMa/accessibility-web-engine/issues/239

Box note:
https://ibm.ent.box.com/notes/880842248686

Link to original issue:
https://github.ibm.com/IBMa/E2E/issues/3897

**Comment by MHoov** [comment]
@aliunwala who is supposed to be reviewing this?

**Comment by aliunwala** [comment]
Created a new ticket for review in the epic.
