### ISSUE TITLE
[A11y] The word "navigation" in "IBM Design ecosystem navigation" is redundant

### ISSUE THREAD

**Issue by carmacleod** [IBMa/equal-access#64]
Windows 10/Chrome 81 (latest)

Go to: https://www.ibm.com/able/

The following nav element has `aria-label="IBM Design ecosystem navigation"`:

```html
<nav class="Switcher-module--nav--3_jdA" aria-label="IBM Design ecosystem navigation" aria-expanded="false" tabindex="-1">
```

This should just be `aria-label="IBM Design ecosystem navigation"` because the role of a `nav` element is "navigation"... which screen readers already say, so it would sound like:
> "IBM Design ecosystem navigation navigation".

**Comment by tombrunet** [comment]
This is actually coming from the Gatsby theme:
https://github.com/carbon-design-system/gatsby-theme-carbon/blob/497dca3c2e01f514ab87ead50967da2825461dd3/packages/gatsby-theme-carbon/src/components/Switcher/Switcher.js#L12

I'll see if we can override it though.

**Comment by carmacleod** [comment]
No, don't override it - they need to fix it so that others benefit.
Thanks for the github pointer. I've opened https://github.com/carbon-design-system/gatsby-theme-carbon/issues/847
