### ISSUE TITLE
[Rule Help]: deprecated elements, attributes, and aria-attributes

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#678]
### Project

a11y checker engine

### Browser

Chrome

### Operating system

MacOS

### Description

This is to enhance the RPT_Elem_Deprecated rule:

- [x] need a help file
- [x] rule messages need to be more specific

### Steps to reproduce

test in the extension

**Comment by shunguoy** [comment]
see box note https://ibm.ent.box.com/notes/919138089437.     Please first to review and finalize the messages.

**Comment by shunguoy** [comment]
@mbgower   in case you need, the dev branch is https://github.com/IBMa/equal-access/tree/dev-608

**Comment by mbgower** [comment]
I will be starting on this today

**Comment by mbgower** [comment]
@shunguo, do you create an array of attributes that are deprecated and report them all in the event of a failure, or as you only listing the attribute used? I would assume the latter, so I have made the failure messages all singular. 
![image.png](https://images.zenhubusercontent.com/5e95c376ea310424b1698b0e/067286dc-a3e5-4716-9d6a-37427008dfaa)

**Comment by mbgower** [comment]
@shunguoy I do not see any existing mdx help file for either RPT_Elem_Deprecated OR element_attribute_deprecated. The box note says it is an existing rule, so I assume the mdx file has a different name?
I'm not seeing your tests, which would allow me to trigger the rule and find the help messages and search for the string, so maybe you could advise?

**Comment by mbgower** [comment]
I have made some commits in a new branch off yours https://github.com/IBMa/equal-access/tree/rpt_element_attribute_deprecated_help

**Comment by mbgower** [comment]
@philljenkins do you have any backstory on this?

**Comment by shunguoy** [comment]
@marcjohlic this rule doesn't have a help currently.  Although it's an existing rule, it's currently not triggered.

**Comment by shunguoy** [comment]
@mbgower  the message file is in the accessibility-checker-engine/src/v2/checker/accessibility/nls/index.ts.    You can either make the message change directly, or you can send me the messages for me to make the change.

**Comment by shunguoy** [comment]
@mbgower the test files are in accessibility-checker-engine/test/v2/checker/accessibility/rules/element_attribute_deprecated_ruleunit

**Comment by mbgower** [comment]
met with Shunguo. Made minor changes to mdx file based on discussion.
