### ISSUE TITLE
[BUG]: Unable to copy Help code snippet from style_hover_persistent rule

### ISSUE THREAD

**Issue by eirckr** [IBMa/equal-access#698]
### Project

a11y checker extension

### Browser

Chrome

### Operating system

MacOS

### Description

Unable to copy code from code snippet from the help text 

### Steps to reproduce

When we trigger a rule for style_hover_persistent, we can't copy the code text snippet.

**Comment by aliunwala** [comment]
Will need to use testcases from codebase to reproduce this rule

**Comment by tombrunet** [comment]
#712 might fix this.

**Comment by tombrunet** [comment]
@eirckr Can you confirm if this is still happening?

**Comment by marcjohlic** [comment]
Shunguo will update this issue with his findings

**Comment by shunguoy** [comment]
tested a few rules.  it seems working file.  moved to test to see if any specific page may cause issue.

**Comment by eirckr** [comment]
No longer an issue
