### ISSUE TITLE
[BUG]: Help file code snippet is too long for single line, we need to make it multi line 

### ISSUE THREAD

**Issue by eirckr** [IBMa/equal-access#700]
### Project

a11y checker extension

### Browser

Chrome

### Operating system

MacOS

### Description

A help file has a code snippet that is too long to be in a single line, this code will render better in a multi line code. 

`<input aria-haspopup="tree" aria-owns="owned_listbox3" aria-expanded="true" role="combobox" aria-label="Tag" aria-activedescendant="selected_option3" aria-controls="owned_listbox3" aria-autocomplete="list" type="text">`

### Steps to reproduce

1. Conduct a scan on the following test file: 
equal-access/accessibility-checker-engine/test/v2/checker/accessibility/rules/combobox_haspopup_ruleunit/combobox_popup.html
2. Open then lean more for: The value of the combobox 'aria-haspopup' attribute "tree" does not match the 'role' value of the popup element "listbox"
3. Review the code snippet from Element location. 

Please review attachment: 
<img width="815" alt="Screen Shot 2022-02-18 at 12 54 51 PM" src="https://user-images.githubusercontent.com/62436670/154745744-5d1a99be-560e-4516-87f3-b9f9fc0e24ac.png">

**Comment by marcjohlic** [comment]
Shunguo and team also ran into this issue with AIEA - may have some info to share.

**Comment by marcjohlic** [comment]
Tom said the new rule architecture (PR #712) will resolve this issue - closing
