### ISSUE TITLE
[Question]: Is there an option to disable saving results?

### ISSUE THREAD

**Issue by evansque** [IBMa/equal-access#704]
### Project

a11y checker

### Description

I am using the [accessibility-checker](accessibility-checker
) npm package and not being able to disable saving results
I tried to set **outputFolder** to **null** or **undefined**, and it still saved the results to **results** folder
How to disable that?

**Comment by tombrunet** [comment]
@evansque Try `achecker --outputFormat null sample1.html`

**Comment by mannika19** [comment]
Hi, I added `outputFormat: [null]` in my aChecker.js file. It doesn't disable the results
