### ISSUE TITLE
[Rule RSRCH]: Identify usage of native attributes and ARIA attributes that overlap or conflict

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#708]
### Rule description

This one is "You /might/ use either one of these, but you can't use both". Note that some native attributes (e.g., 'checked') have defaults and therefore are used even when they're not there.

This rule will check when a native attribute is used with an ARIA attribute that maps to the same ARIA property. For example, using `colspan` and `aria-colspan` on the same element.

This would flag as a recommendation. Can create a dependent rule that flags a violation if the values would conflict (e.g., `checked` and `aria-checked="false"`).

### Relevant requirement(s)

4.1.1 Parsing

### High-level approach and rule scope

Would want a listing of conflicting values that we can iterate through:
```
[
  ["checked", "aria-checked"],
  ["colspan", "aria-colspan"],
 ...
]
```

### Ruleset and failure level

WCAG 2.0, WCAG 2.1, IBM

### Failure level

Recommendation

**Comment by shunguoy** [comment]
There is an existing rule on this:  HAAC_Aria_Or_HTML5_Attr.
Description: Triggers if both HTML 5 attribute and the associated WAI-ARIA attribute are in an element 
Origin:  HTML 5 - per Richard Schwerdtfeger's requirements. g1141
