### ISSUE TITLE
Clean up mdx template

### ISSUE THREAD

**Issue by mbgower** [IBMa/equal-access#717]
The mdx template (accessibility-checker-engine/help/a_rule_help_template.mdx) has a number of spaces on empty lines, which are causing odd formatting glitches.![image.png](https://images.zenhubusercontent.com/5e95c376ea310424b1698b0e/08246761-aae4-416a-a36e-8d852dcf2aa2)
![image.png](https://images.zenhubusercontent.com/5e95c376ea310424b1698b0e/c6df7b4d-459a-4d79-879d-985485e9de35)

**Comment by aliunwala** [comment]
From Triage:
@tombrunet do you know if your refactor of the Help files will also fix this? If so this can be closed.

**Comment by tombrunet** [comment]
This may be fixed, if not, please reopen
