### ISSUE TITLE
[BUG] [EXTENSION] Scanning browser protected pages results in extension load/scan issues PART 3

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#723]
- [x] Make checker catch bad urls and puts up a message to go to another page
- [x] Fix left margin problem in the Assessment view
- [x] Fix count problem in the main assessment view Current Status score and add  documentation to help the user understand what the score means.

**Comment by drjoho** [comment]
## Detailed description

> Node version:
> Platform:  chrome browser

> Describe in detail the issue you're having.
When I do a multiple scan, when there is a page with an error the tool crash as you can see in the screenshot. The same is if I scan a jpg or a pdf. The problem is that I loose all the previous work.
## Steps to reproduce the issue

1. Open this page: https://autogrill.com/it/storie/autogrill-group-supply-chain-sustainability-guidelines
2. Step two: click on the tab of the accessibility checker in the developer console
3. Step three: 
Expected: a warning from the tool that you can't scan a jpg or that particular page , but not losing the previous scanned
pages in a multiple page scan.
Actual result: crash of the accessibility scanner tab in the developer console

**Comment by drjoho** [comment]
All is working now just need to add the message for when to change to a page with a real url.

**Comment by drjoho** [comment]
OK folks I got excited and fixed more than was in this issue:
1. Checker now catches bad urls and puts up a message to go to another page
2. Marc had noticed that there was a left margin problem in the Assessment view - fixed
3. There was still a count problem in the main assessment view score till this has been fixed and some documentation added to help the user understand what the score means.

**Comment by drjoho** [comment]
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/64442976/157160204-80c6faf3-478f-4cb4-8b0d-950ff06833a9.png">

**Comment by drjoho** [comment]
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/64442976/157160326-d73cb5d2-0ad3-4109-a96e-ef0947184098.png">

**Comment by drjoho** [comment]
In Assessment View the indentation is fixed
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/64442976/157160538-93979b43-3701-4fbb-8d0f-a09dede7532a.png">

**Comment by eirckr** [comment]
If user land on the target page:  https://autogrill.com/it/storie/autogrill-group-supply-chain-sustainability-guidelines then navigates to a new page and goes back to target, the ui does not clean up. Please review attachment: 
<img width="1470" alt="Screen Shot 2022-03-08 at 10 35 19 PM" src="https://user-images.githubusercontent.com/62436670/157373935-f579b8ea-4eec-4a6b-bd28-db1bedbd7a7a.png">

**Comment by eirckr** [comment]
Validated
