### ISSUE TITLE
False positives with content in slots

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#741]
See https://codesandbox.io/s/issue-741-h46zge?file=/index.html

**Comment by ariellalgilmore** [comment]
Hi @tombrunet, seems like we are still seeing an issue with this here: https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components/iframe.html?args=&id=components-masthead--default&viewMode=story

The link element has slotted text, but still seeing an issue in the accessibility checker

<img width="1440" alt="Screen Shot 2022-09-26 at 9 42 09 AM" src="https://user-images.githubusercontent.com/20210594/192333692-72e1726f-b828-41f0-809f-533df89d46e0.png">

**Comment by MHoov** [comment]
Reopening based on Ari's comment above.

**Comment by aliunwala** [comment]
Triage:
Looks like we were able to find an example of this @shunguoy will post a picture.

**Comment by shunguoy** [comment]
able to produce with the user's page:
<img width="934" alt="Screen Shot 2022-09-29 at 3 23 43 PM" src="https://user-images.githubusercontent.com/18539498/193134511-d668fa0c-51c7-4d10-aa64-779cb8ad6fcf.png">

**Comment by shunguoy** [comment]
this specific issue is reported in a link, but I suspect the error can occur in other rules, which calculate the required data from a slot.

**Comment by eirckr** [comment]
Unable to reproduce issue with previews rules using target url: https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/web-components/iframe.html?args=&id=components-masthead--default&viewMode=story
