### ISSUE TITLE
menu element is a type of 'list', not deprecated

### ISSUE THREAD

**Issue by scottaohara** [IBMa/equal-access#752]
Was checking [the `role=directory` test case](https://w3c.github.io/html-aria/tests/deprecated-directory.html) to see if that rule had landed in the latest released build.  Noticed instead that the checker flagged use of the`menu` element with the following:
>The `<menu>` element is deprecated in HTML 5

While the w3c html spec did deprecate the `menu` element, [it is not in the HTML standard](https://html.spec.whatwg.org/multipage/grouping-content.html#the-menu-element).  It's essentially just another `ul` element that [maps to `role=list`](https://w3c.github.io/html-aam/#el-menu)

**Comment by shunguoy** [comment]
the menu element was deprecated, but it's put back in HTML 5.  This is fixed, and the fix should be in the next merge.
