### ISSUE TITLE
[BUG]: input_label_exists - Button should be labellable

### ISSUE THREAD

**Issue by tombrunet** [IBMa/equal-access#761]
### Project

a11y checker engine

### Description

`input_label_exists` does not treat `button` as a labellable element (label[for]). It should be allowed.

From https://html.spec.whatwg.org/multipage/forms.html#category-label we should allow for:
> [button](https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element), [input](https://html.spec.whatwg.org/multipage/input.html#the-input-element) (if the [type](https://html.spec.whatwg.org/multipage/input.html#attr-input-type) attribute is not in the [Hidden](https://html.spec.whatwg.org/multipage/input.html#hidden-state-(type=hidden)) state), [meter](https://html.spec.whatwg.org/multipage/form-elements.html#the-meter-element), [output](https://html.spec.whatwg.org/multipage/form-elements.html#the-output-element), [progress](https://html.spec.whatwg.org/multipage/form-elements.html#the-progress-element), [select](https://html.spec.whatwg.org/multipage/form-elements.html#the-select-element), [textarea](https://html.spec.whatwg.org/multipage/form-elements.html#the-textarea-element), [form-associated custom elements](https://html.spec.whatwg.org/multipage/custom-elements.html#form-associated-custom-element)

### Steps to reproduce

https://codesandbox.io/s/issue-761-gn43fx

**Comment by tombrunet** [comment]
See also https://github.com/IBMa/equal-access/issues/756

**Comment by mbgower** [comment]
@tombrunet I've had questions on the status of this. Any updates?

**Comment by shunguoy** [comment]
PR #1775  for @tombrunet to review.
