### ISSUE TITLE
Requesting types for the accessibility checker

### ISSUE THREAD

**Issue by dave-hart** [IBMa/equal-access#77]
### Summary

Typescript is massively popular, it would be extremely helpful to have this package provide types for the programatic API and objects.

### Justification

I want to use it in a typescript test project

### "Must have" functionality

Types

**Comment by tombrunet** [comment]
Putting this here for reference:
https://medium.com/cameron-nokes/the-30-second-guide-to-publishing-a-typescript-package-to-npm-89d93ff7bccd

The engine is already in typescript, but the Node and Karma packages are not. Shouldn't be super difficult to convert.

**Comment by tombrunet** [comment]
Conversion of accessibility-checker to typescript started in this PR: https://github.com/IBMa/equal-access/pull/305 . Still needs more testing.

**Comment by scottnath** [comment]
Hi @tombrunet, looks like #305 was merged - does that mean that accessibility-checker should not throw the `Could not find a declaration file for module 'accessibility-checker'....` error in version `^3.1.1`?

**Comment by tombrunet** [comment]
Not deployed yet. I'll close this issue when it is. Hopefully this week.

**Comment by tombrunet** [comment]
You'll want `^3.1.3`. You can see an example usage here:
https://github.com/IBMa/equal-access/blob/master/accessibility-checker/boilerplates/mocha-puppeteer-ts/test-ts/basic.test.ts
