### ISSUE TITLE
Save Domain and Path in report.html file

### ISSUE THREAD

**Issue by mgifford** [IBMa/equal-access#78]
### Summary

When exporting the report it doesn't capture the location making it harder to find.  Would be good if the report title looked more like:
  GitHub.com_IBM_equal-access_isues_new-equal-access-report.html

rather than just:
  report.html

That's not the best file name.

### Justification

The purpose of exporting pages is to share them. You probably want to share more than one if you are finding errors.  Why not make it easy to avoid having to wade through tonnes of report(1).html, report(2).html, ..., report(132).html in your hard drive.

### "Must have" functionality

Easiest would be to just prepend the domain, so GitHub.com_report.html

![Screen Shot Of report export icon](https://user-images.githubusercontent.com/116832/82335472-5efe2400-99b7-11ea-85ec-6a1e66f19d19.png)

**Comment by cpandhi** [comment]
Thanks, @mgifford for reporting this issue.

The report name could be "Accessibility Report for My scanned page Title(1)"

If the scanned page title is too long then we could trim it to take just the first part,
for example, a report for New York times with title "<title>The New York Times - Breaking News, World News & Multimedia</title> would look like:
"Accessibility report for the New York Times (1)"

**Comment by mgifford** [comment]
That would be great @cpandhi ... might even want to say "Equal Access Report for My scanned page Title(1)"

That way it's clear what tool generated the report.

**Comment by zhenwan** [comment]
This request has been implemented in Jun 18 release.https://github.com/IBMa/equal-access/releases
