### ISSUE TITLE
[New Rule]: Implicit and explicit roles

### ISSUE THREAD

**Issue by shunguoy** [IBMa/equal-access#789]
### Rule description

The rule checks if a role that exists implicitly is assigned explicitly.  For example <button role='button' />.

### Relevant requirement(s)

4.1.1 Parsing

### High-level approach and rule scope

Detect the elements with explicit roles to see if the same roles are explicitly assigned

### Ruleset and failure level

WCAG 2.0, WCAG 2.1, IBM

### Failure level

Recommendation

**Comment by maryjom** [comment]
@shunguoy Please add a link to the boxnote that explains what help is needed.
