### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by AD-United** [IBMa/equal-access#797]
### Project

a11y checker extension

### Description

Just added the extension but having difficulties launching the tool itself. Am I too open the Chrome dev tools to launch the accessibility checker?

**Comment by marcjohlic** [comment]
Yes - open the Dev tools and you will see a "lite" version of the Checker listed across the top.  There is a more advanced (or "Developer" view of the Checker that lives in an Elements sub-panel.  These three short videos can help you get oriented with the Accessibility Checker extension:  https://www.ibm.com/able/toolkit/tools#develop

**Comment by MHoov** [comment]
this might help too!
![image.png](https://images.zenhubusercontent.com/5ed6cf7a36f485fe5e575397/a40a1278-19fd-451d-9b04-18070e66beff)
