### ISSUE TITLE
[UI BUG] The responsive layout of both the fixed heading and the Scan Summary Page is having issues.

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#822]
What is happening with the formatting is the responsive layout is having issues at the at the breakpoints of the fluid grid. The breakpoints have not changed but there is formatting issues and not just the ones pointed out by @philljenkins.

![image.png](https://images.zenhubusercontent.com/61081394ffd52d20c363a4cd/4d307cff-9727-4f10-b111-f72f98039fa5)

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/64442976/163735007-03466adb-32cf-4865-a4db-02c386a2629a.png">

**Comment by drjoho** [comment]
Fixed in #823

**Comment by eirckr** [comment]
Validated
