### ISSUE TITLE
dpub aria role allowance for figure with figcaption

### ISSUE THREAD

**Issue by scottaohara** [IBMa/equal-access#847]
As discussed in https://github.com/w3c/dpub-aria/issues/42#issuecomment-1092558918, doc-example is a dpub variant of the figure role. This role being the same as figure but with the opportunity of being exposed as an "example" for its role description, needs to be an allowed role for the figure element.

[ARIA in HTML (preview)](https://pr-preview.s3.amazonaws.com/w3c/html-aria/pull/415.html#el-figure) is updating the allowed roles for `figure` with a child `figcaption` to account for this need from dpub aria.

**Comment by marcjohlic** [comment]
See #371 - both dpub related

**Comment by ErickRenteria** [comment]
Merged
