### ISSUE TITLE
[New Rule - TS3] RPT_STYLE_HinderFocus1 updated for TS

### ISSUE THREAD

**Issue by marcjohlic** [IBMa/equal-access#853]
For requirement 2.4.7 Focus Visible: RPT_STYLE_HinderFocus1 is an existing rule that needs to be upgraded.

See the [Slack thread](https://ibm-studios.slack.com/archives/GSGN38DQE/p1650902482592629) for further information.

Tom may be planning to update this one.

**Comment by drjoho** [comment]
Tom says done (reduces false positives)
