### ISSUE TITLE
Checker results view skipping - unable to scroll

### ISSUE THREAD

**Issue by marcjohlic** [IBMa/equal-access#854]
Chrome (haven't tested on FF)
Scan a page - view results - select an issue - try to scroll through the results and the focus keeps skipping back to the selected issue leaving me unable to scroll through the rest of the issues.

The attached animation demonstrates that I'm able to scroll through the results initially, but once I select an issue I can no longer scroll because the focus keeps jumping back to the selected issue.

![checkerSkip.gif](https://images.zenhubusercontent.com/58d3fa1c51aa2c3057794e7f/a7dfd157-529e-4bd1-aa8b-8a7e2f36fda5)

**Comment by shunguoy** [comment]
triage: it's fixed and close, not reproducible in the latest version of the checker
