### ISSUE TITLE
[BUG]: Chrome extension will not scan https://uat-mpsw.cs66.force.com/s/

### ISSUE THREAD

**Issue by sharitrewin** [IBMa/equal-access#855]
### Project

a11y checker extension

### Browser

Chrome

### Operating system

MacOS

### Description

Trying to scan https://uat-mpsw.cs66.force.com/s/ in Chrome with Accessibility Checker 3.1.28.
I press the Scan button and there is no response at all. (No progress spinner appears.)
I am able to scan the page in the FF version, and I am able to scan other pages in Chrome.

### Steps to reproduce

Go to https://uat-mpsw.cs66.force.com/s/
Open the Checker Extension (either view)
Click on 'Scan'

**Comment by marcjohlic** [comment]
I spotted these two errors coming up each time I press the Scan button on that page:

![image.png](https://images.zenhubusercontent.com/58d3fa1c51aa2c3057794e7f/05fcabbf-5159-427f-ab8a-96ed9bd27956)


And even before scanning, this pops up as soon as the page loads, which kind of makes it look like DevTools doesn’t fully see the page maybe  ??  which could be why Checker is getting stuck?

![image.png](https://images.zenhubusercontent.com/58d3fa1c51aa2c3057794e7f/c9e2bfd5-3396-46ad-9873-a2471acfdbc8)
