### ISSUE TITLE
[BUG]: Accordion closing on selecting an issue in FF

### ISSUE THREAD

**Issue by sharitrewin** [IBMa/equal-access#856]
### Project

a11y checker extension

### Browser

Firefox

### Operating system

MacOS

### Description

After scanning the page https://uat-mpsw.cs66.force.com/s/, when trying to explore the issues in the 'Accessibility Checker' view, almost every issue I click on causes the accordions to all be closed, although the web page scrolls and the code is highlighted.

After initial scan:
<img width="946" alt="image" src="https://user-images.githubusercontent.com/63615564/166070795-1b2db8a3-0a7e-44ac-b71a-9fbbb7bce8b0.png">

Scroll down:
<img width="931" alt="image" src="https://user-images.githubusercontent.com/63615564/166070891-a53f3f16-1746-4893-8056-3950026b7468.png">

After clicking on 'Inform the user when their input action ...' issue:
<img width="947" alt="image" src="https://user-images.githubusercontent.com/63615564/166070989-cbdcdb40-2963-4569-99ce-696ce8486723.png">

0 Recommendations are selected, even though I just clicked on one. The code with the issue is highlighted correctly. Issues at the document[1] level are handled correctly in Element Roles View, Requirements View, and Rules View, but none of the other issues are displayed correctly when clicked on in any of the three views.

I'm not seeing the same behavior in other pages scanned on FF (eg ibm.com).
This page will not scan at all in the Chrome version of the extension (issue #855), and has some errors.
I am seeing this in V3.1.28 of the extension

### Steps to reproduce

1. Go to https://uat-mpsw.cs66.force.com/s/
2. Open dev tools and go to the 'Accessibility Checker' view
3. Click 'Scan'
4. Scroll down past the issues listed for the document[1] element roles
5. Click on the first issue in the next element role option
6. The page scrolls to bring the element into view, the code is highlighted, but the issue accordions are all closed and the status bar reports that no issues are selected. At least the issue that was clicked on should be selected, and that accordion should be open with the issue highlighted.

**Comment by shunguoy** [comment]
triage: bug, it should stay opened, seems happening in Chrome too

**Comment by drjoho** [comment]
Still trying to figure out what is wrong

**Comment by drjoho** [comment]
Only seems to happen on the web site above.

**Comment by drjoho** [comment]
![image.png](https://images.zenhubusercontent.com/61081394ffd52d20c363a4cd/64e969bc-6742-4c9d-9134-0d87c9c1aa8d)

**Comment by drjoho** [comment]
![image.png](https://images.zenhubusercontent.com/61081394ffd52d20c363a4cd/56c53e83-f7c6-4852-82ae-712e1194256f)

**Comment by drjoho** [comment]
The Checker will not work for this page as our assumption is that pages are mostly static. This page is not static at all and so the references in our Checker become out of date immediately after a scan and even more so till the next scan. So I will lower the priority and close this issue.
