### ISSUE TITLE
All links to IBM accessibility checklist from toolkit are 404ing for me

### ISSUE THREAD

**Issue by mbgower** [IBMa/equal-access#86]
## Title line template: [Title]: Brief description
If I open the link directly from the toolkit, I get a 404.
If I choose "save link" and then paste it into the browser path, the page opens.

## What tool(s) are you using?
happening on both Safari and Chrome

## Steps to reproduce the issue

1. CHoose any link to the checklist on any page of the toolkit
2. Click it

https://www.ibm.com/able/toolkit/develop/coding-interactions/keyboard-interactions

## Additional information
![Screen Shot 2020-05-20 at 12 53 23 PM](https://user-images.githubusercontent.com/62436670/82480241-1c147d00-9a99-11ea-847f-f05df5129bf7.png)

- Screenshots or code
![image](https://user-images.githubusercontent.com/14298245/82464263-b9a88600-9a72-11ea-8c73-98294cbf454c.png)

`app-9974914c43e0f511eb2d.js:1 GET https://www.ibm.com/able/page-data/guidelines/ci162/keyboard.html/page-data.json 404`

**Comment by eirckr** [comment]
If you right click on url and open on new window, we're able to got the target url.

**Comment by tombrunet** [comment]
Gatsby seems to think the links are internal when they're not. We won't be able to use Markdown links into the checklist until it's migrated into the Gatsby framework. I'm converting them all now.

**Comment by tombrunet** [comment]
These should all be fixed now. Let me know if you find another.

**Comment by mbgower** [comment]
Thanks, a couple of quick checks shows they're fine.
