### ISSUE TITLE
[BUG]: cross references in design topics are incomplete

### ISSUE THREAD

**Issue by mbgower** [IBMa/equal-access#867]
### Project

able site

### Browser

Chrome

### Operating system

MacOS

### Description

It appears that on the updated design pages, the related dev topics are no longer consistently cross-referenced (they used to be).

For instance the first topic under Content design, [Headings](https://www.ibm.com/able/toolkit/design/content/#headings), has no Related topics section
![image](https://user-images.githubusercontent.com/14298245/167029597-0e4e8111-8251-4532-95c0-d3dd58ad6f9c.png)

But there is clearly at least one [directly related development topic](https://www.ibm.com/able/toolkit/develop/coding-info-and-relationships/text-meaning/#headings)  as well as at least one [related design topic](https://www.ibm.com/able/toolkit/design/visual/#text-styles)

The missing cross references are not consistent. Some topics _do_ list related topics. The second topic on the Content page (Alternative text for visuals), for instance, lists a whole bunch of them.
![image](https://user-images.githubusercontent.com/14298245/167030450-7e4f8b65-f91d-405d-90a1-fb16377f65f3.png)

Recommendation to remediate: The prior version of the toolkit should be reviewed for the cross-references, and the updated pages be revamped to include them.

### Steps to reproduce

Follow links above

**Comment by marcjohlic** [comment]
Moved to E2E repo https://github.ibm.com/IBMa/E2E/issues/4438
