### ISSUE TITLE
[BUG]: missing title and script section in help file for Rpt_Aria_ArticleRoleLabel_Implicit

### ISSUE THREAD

**Issue by zwiastunsw** [IBMa/equal-access#868]
### Project

rule-server

### Browser

Chrome

### Operating system

Windows

### Description

there is no title and script section in the Rpt_Aria_ArticleRoleLabel_Implicit.html file 
Add after head tag: 
````
    <title>Rpt_Aria_ArticleRoleLabel_Implicit - Accessibility Checker Help</title>
    <script>
        RULE_MESSAGES = {"en-US":{"0":"An element with \"article\" role must have a label that describes its purpose","Pass_0":"Rule Passed","Fail_1":"The element with \"article\" role does not have a label","group":"An element with \"article\" role must have a label that describes its purpose"}};
        RULE_ID = "Rpt_Aria_ArticleRoleLabel_Implicit";
    </script>
````

### Steps to reproduce

See Rpt_Aria_ArticleRoleLabel_Implicit.html file in rule-server/src/static/archives/22.04.19/doc/en-US/ and previous deployments

**Comment by shunguoy** [comment]
triage: related to #872,  fix #872 first, and check if this still exists

**Comment by aliunwala** [comment]
From triage:
We dont have this rule any more. This rule was deprecated.

**Comment by aliunwala** [comment]
Could we get a code snippet that triggers this for you? And possibly the version that you are using of the checker?

**Comment by aliunwala** [comment]
From triage: 
We think we found the location for this. And will hopefully prioritize it for a future sprint. 
https://github.com/IBMa/equal-access/blob/master/accessibility-checker-engine/help-v4/en-US/Rpt_Aria_ArticleRoleLabel_Implicit.html

**Comment by aliunwala** [comment]
Triage:
Since this rule is gone we cant really fix this, it is not in the latest codebase. (The older archives will hold some of these help files but they are static read only archives)
