### ISSUE TITLE
Typo in "Coding interactions" on the developer page

### ISSUE THREAD

**Issue by srambach** [IBMa/equal-access#87]
At the URL https://www.ibm.com/able/toolkit/develop I see a typo in "Coding intera**c**tions" in the white box.

**Comment by eirckr** [comment]
Please review: 
![Screen Shot 2020-05-20 at 12 47 38 PM](https://user-images.githubusercontent.com/62436670/82479687-53365e80-9a98-11ea-8c57-dcaac4abc90b.png)

**Comment by tombrunet** [comment]
Fixed
