### ISSUE TITLE
[BUG]: Update and correct message for non-scannable urls 

### ISSUE THREAD

**Issue by eirckr** [IBMa/equal-access#879]
### Project

a11y checker extension

### Browser

Chrome

### Operating system

MacOS

### Description

The current message has two typos for sites that are not scannable:
IBM Equal Access _Accesibility_ _Check_ cannot run on this URL. Please go to a different page.

![image.png](https://images.zenhubusercontent.com/58d3fa1c51aa2c3057794e7f/b0ccebb9-3773-4b9c-8253-4ba4bb69b481)

The idea is to improve this message.  This [Slack thread](https://ibm-studios.slack.com/archives/GSGN38DQE/p1652276399089429?thread_ts=1652273534.503879&cid=GSGN38DQE) has some message examples.

### Steps to reproduce

Conduct a local scan of file.

**Comment by drjoho** [comment]
Spelling fixed.

**Comment by eirckr** [comment]
Fix with https://github.com/IBMa/equal-access/pull/999
