### ISSUE TITLE
[BUG] False positive on empty link 

### ISSUE THREAD

**Issue by NiklasBr** [IBMa/equal-access#88]
Links with an SVG image are incorrectly labelled as empty.

## What tool(s) are you using?

- [ ] `accessibility-checker-engine`
- [x] `accessibility-checker`
- [ ] `karma-accessibility-checker`
- [ ] `rule-server`
- [ ] `boilerplates`
- [ ] `other`

## Detailed description

> Node version:
> Platform: Firefox plugin

> Describe in detail the issue you're having.

## Steps to reproduce the issue

This markup will produce an *Empty link* error, even though it has both an image and a title.
```html
<html lang="en">
<body>
	<header>
		<a class="header-logo-link" href="/" title="header.logo-link-home">
			<svg class="icon hide-for-small-only logo-1"><use href="#logo-1"></use></svg>
			<svg class="icon show-for-small-only logo-3"><use href="#logo-3"></use></svg>
		</a>
	</header>
</body>
<svg style="display: none;" aria-hidden="true">
	<defs>
		<g id="logo-1">
			<svg viewBox="0 0 339.03 357.51"><path d="M292.2,0h11.12V62.82h35.71V73.33H292.2Z"/></svg>
		</g>
		<g id="logo-3">
			<svg viewBox="0 0 277.6 26.743"><path d="M106.4.02h4.05V22.85h13v3.83H106.4Z"/></svg>
		</g>
	</defs>
</svg>
</html>
```

**Comment by tombrunet** [comment]
@NiklasBr Going to to a bit of investigation on this first. At one time, `title` on the `a` was not sufficient as an accessible name for a link. 

We do have a todo related to supporting SVG to support a `title` element within an SVG:
```
<svg version="1.1" width="300" height="200">
<title>Green rectangle</title>
<rect width="75" height="50" rx="20" ry="20" fill="#90ee90" stroke="#228b22" stroke-fill="1" />
</svg>
```
which I believe would be the correct way to do this...
