### ISSUE TITLE
Rules list - Manual version #4118

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#908]
see PL: [Site or Page listing Checker rules and Help content](https://ibm.box.com/s/9se9iwt8xh1d7h4cjillehndav6snh0m)

Manually create an index of rules. Currently each rule exists in individual HTML. This could be in GitPages.

Later we can automate this as part of the build process - see Automated Rules list #4118

### Why does this need to be accomplished
Users & support need an easy way (website / web page) to view a list of Checker rules and each rule's Help content - outside of the Checker itself. 

### Related issues or references
- Rules Architecture v3 #4114
- Adding rule IDs to Help [#595](https://app.zenhub.com/workspaces/equal-access-61ae71f9f8b4ec001e136462/issues/ibma/equal-access/595)

### Supporting notes and details
?

![image](https://user-images.githubusercontent.com/4451128/171960726-557a443c-eaff-4b90-b762-bd1bc7218179.png)

**Comment by marcjohlic** [comment]
Tom created a prototype for this - we can move on to #908 with this idea.   We no longer need this manual version.  Closing.
