### ISSUE TITLE
Enhancement: Add support for webdriver.io #3553

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#910]
Add support for webdriver.io,

need a way to detect the driver instance, either selenium or webdriver and switch between the executions.

![image](https://user-images.githubusercontent.com/4451128/171960971-b533e67a-3987-4772-b018-feadc1ab7195.png)

**Comment by shunguoy** [comment]
triage: we don't support webdriver.io yet.  review this, we need to work on in the future.  put to backlog now.

**Comment by aliunwala** [comment]
Link to the connected issue:
https://github.ibm.com/IBMa/E2E/issues/3553

**Comment by aliunwala** [comment]
Link to connected roadmap:
https://github.ibm.com/org-ids/roadmap/issues/2678

**Comment by drjoho** [comment]
Tom and I worked to get webdriverio infrastructure set up.

**Comment by drjoho** [comment]
Directory

/Users/drjoho/Documents/GitHub/equal-access/accessibility-checker/boilerplates/webdriverio

FIrst time

npm install

npm run build

========================

To run webdriverio

npm I

npm run wido

**Comment by drjoho** [comment]
Next steps:

accessibility-checker/test/mocha/aChecker.Playwright/aChecker.Scans/aChecker.Content.Playwright.spec.mjs

Covert to webdriverio/test/specs/example.e2e.ts

**Comment by drjoho** [comment]
@tombrunet I put the four failed rules in the skiplist. Can you check why they are not skipping make them skip and close issue.

**Comment by drjoho** [comment]
All functionality is there. Skips work and it runs clean. Still needs documentation (another issue i guess)
