### ISSUE TITLE
Accessibility checker keyboard shortcuts #1171

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#930]
Accessibility Checker 3.0.1

Keyboard operation of the Accessibility Checker could be made much more efficient and enjoyable if we added a few keyboard shortcuts.  Suggestions are:

* Scan
* Reset
* Jump to next/previous highlighted issue

In the current release, each line in the list view is a tab stop. Where there are many issues, navigating through them will be arduous.  Supporting instant access to scan or reset will save users from having to navigate all the way back to the buttons at the top.

Exploring highlighted issues would be much faster if there was a shortcut to jump the focus to the next highlighted issue.  That way the user can easily navigate through all the issues for their component, in any view.

![image](https://user-images.githubusercontent.com/4451128/172451658-facd7f70-3320-4893-a9bd-63154949bde2.png)

**Comment by aliunwala** [comment]
Triage:
Dev needs to investigate the possibility of this in dev from within the elements subpanel.

**Comment by tombrunet** [comment]
This is handled by new treegrid
