### ISSUE TITLE
Checker spreadsheet report level 3 description #2960

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#932]
In the checker's exported spreadsheet, in the Issue Summary Sheet, the description of Level 3 is problematic because it mentions the IBM Requirements, and users may actually be scanning against WCAG 2.0 or WCAG 2.1.

A more generally applicable description would be:

'Level 3 - necessary to meet requirements'

![image](https://user-images.githubusercontent.com/4451128/172452286-da7f1699-e47c-4b36-bccb-78f8dd488fe9.png)

**Comment by MHoov** [comment]
@aliunwala tom moved this to sprint to do

**Comment by aliunwala** [comment]
Pushing this back as I have been having trouble getting new laptop working

**Comment by aliunwala** [comment]
Pushed a fix for this for both the accessibility-extension/accessiblity-checker

**Comment by eirckr** [comment]
Validated
