### ISSUE TITLE
Ability to check off 'needs review' items in Checker #3109 + batch actions + matching HTML report

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#936]
### Describe what needs to be accomplished
Ability to check off 'needs review' items in Checker (assessment view?)

### Why does this need to be accomplished
After reviewing the issues found by the checker, some can be ignored. Developers and testers would like to be able to get rid of those issues from their view and from saved reports.

### Related issues or references
Parking lot submission [Check off 'needs review' items in Checker](https://ibm.box.com/s/2dwri31ke5rao6o45k5nk7wx92xesy5k)

### Supporting notes and details
Tom advises we used to have code to mark an issue 'ignored', or to make a comment. There is no UI for it today and would need to be designed.

![image](https://user-images.githubusercontent.com/4451128/172453433-b7c76c28-1b75-468d-b2d7-f7010c638da3.png)

**Comment by aliunwala** [comment]
Triage:
This is not a trivial ask (on dev) as we need to store state. But it is a very cool feature that is worth taking some time to design and think about.

**Comment by MHoov** [comment]
Alex is working on this design now

**Comment by MHoov** [comment]
Folding in three design issues from internal board:
- Ability to check off 'needs review' items in Checker (3109)
- Update the issue presentation in the Checker's HTML report to match the latest Checker (3197)
- Filter the results side of the checker based off card pushes on the summary side of the checker (1496)

Design review held on June 20th. Final designs in [Mural](https://app.mural.co/invitation/mural/ibm14/1684260151197?sender=alexandra0696&key=02074eb6-44e1-460f-905d-2a91126f9a49) and in [Figma](https://www.figma.com/file/intddqthciXilHQCLWppQ7/a11y-checker?type=design&node-id=428%3A78341&t=3q8PzjFDvf3FKOoj-1).

Ready for implementation

**Comment by MHoov** [comment]
@drjoho will create a new issue for the matching the HTML report and then close this issue as a dup of the epic

**Comment by drjoho** [comment]
Closed as is now a dup replaced by other issues in Epic 5.4 Checker Extension
