### ISSUE TITLE
Add summary of problematic Carbon components to Checker report #3105

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#937]
### Describe what needs to be accomplished
Add summary of problematic components to Checker report (spreadsheet)

Identify the lowest level role for the violation using the last part of the ARIA path, then use the tokens provided by Carbon to identify instances to tally them up

### Why does this need to be accomplished
To help them understand the magnitude of fixing specific violations by knowing how many instances are occurring by the specific component.

### Related issues or references
Parking lot submission [Use Analytics to Improve our Checker Guidance](https://ibm.box.com/s/l2v0xal6r5cgk3bqigj2u988dhub2xad)

![image](https://user-images.githubusercontent.com/4451128/172453577-1e59706a-a3fc-4d86-af4c-9fca58457300.png)

**Comment by aliunwala** [comment]
Triage: 
This should not be taken up to be worked on until we can find a metric to find "problematic components" without that this not able to be sorted on the report to find the "least accessible" components

**Comment by sharitrewin** [comment]
I don't think that paper is useful for making component-based recommendations, but I do recommend you talk to Jeff Chew about his plans for making it possible to identify Carbon components in the DOM.
