### ISSUE TITLE
Checker for Microsoft Edge Store #3104

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#938]
### Describe what needs to be accomplished
Put Checker specifically on Microsoft Edge store.

You can already deploy it for Edge from the Chrome store, but we don't explicitly call that out.

### Why does this need to be accomplished
We don't have a pre-built checker for Edge and it seems like it would be a minimal amount of work to accomplish the build part at least since Edge is built on Chrome. We would need to investigate the legal and administrative work associated with putting the checker on the edge store.

### Related issues or references
Park lot submission [Checker for Microsoft Edge Store](https://ibm.box.com/s/ctpno1ryp0q84l3zhllh5zlizmbaqrau)

### Supporting notes and details
* Think the effort to build will be minimal.
* Unsure what sort of maintenance effort this will create.

![image](https://user-images.githubusercontent.com/4451128/172453829-1c2885f6-0b58-40d0-b4de-d60d1ce0edcf.png)

**Comment by aliunwala** [comment]
Triage:
We need to investigate this and see if this is possible. We should open up a Microsoft account and see what happens after importing this in.

**Comment by aliunwala** [comment]
Triage:
We need to investigate this and see if this is possible. We should open up a Microsoft account and see what happens after importing this in.

**Comment by MHoov** [comment]
@ErickRenteria something for you to try and do in R5.2

**Comment by drjoho** [comment]
@ErickRenteria move to sprint-to-do or remove sprint.

**Comment by MHoov** [comment]
@ErickRenteria @tombrunet @drjoho No updates in this issue since Jun 7

**Comment by ErickRenteria** [comment]
The checker is now live in the Edge browser: https://microsoftedge.microsoft.com/addons/detail/ibm-equal-access-accessib/ompccpejakabkmfepbijnagedbdfldka
