### ISSUE TITLE
Accessibility Checker extension dark theme #3103

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#939]
### Describe what needs to be accomplished
Users have chose a dark theme for their operating system, and our panel does not adapt.
Also our panels shows as bright white panel when everything else is dark - this can an accessibility issue.

### Why does this need to be accomplished
Several users have requested

### Supporting notes and details
* Might be simple, but could also run into a lot of accessibility issues - we have not explored Carbon dark theme.

![image](https://user-images.githubusercontent.com/4451128/172453991-ee41c6f4-ac13-425e-b86d-459176306ceb.png)

**Comment by tombrunet** [comment]
Included this in the rearch work
