### ISSUE TITLE
'Jump' keyboard shortcut for accessibility checker #3166

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#944]
### Summary

In the Accessibility Checker's Accessibility Checker tab within the Elements panel, provide a 'jump' keyboard shortcut: Cmd-J (Mac) or Ctrl-J (Windows).

When focus is in the Accessibility Checker tab within the Elements panel, this command causes the keyboard focus to jump from its current location to the last issue the user selected, opening accordions as necessary to expose the issue.

An issue is selected if the user clicks on it, or presses Enter when it has keyboard focus, or clicks 'learn more' to open the help for the issue.

If the page has been re-scanned since the user last selected an issue, and the same issue still exists, jump to that issue. If the issue does not exist, a message shows, saying "Issue not found. The previously focused issue was not found in this scan."

Moving to a new URL clears the previously selected issue.

### Justification

When keyboard users are working through a list of issues, every time they go to the code and come back to the issue list, they must navigate through all the earlier issues to get back to their place.  This can be slow and tedious.

### Context

This issue emerged from the earlier issue [#1707](https://github.ibm.com/IBMa/E2E/issues/1707), and complements the other existing issue on keyboard shortcuts for the checker: [#1171](https://github.ibm.com/IBMa/E2E/issues/1171)

![image](https://user-images.githubusercontent.com/4451128/172455305-76e4c436-6c9e-4c7d-87bc-20d091d22bfe.png)

**Comment by aliunwala** [comment]
Triage:
This seems like a specific request for a keyboard shortcut. @tombrunet Do you know if there is a large need for this and if so we might want to raise the priority. 

Our guess from triage is we might need to cache a variable to hold the previously visited node and then cmd+j can jump you back to that node.

**Comment by tombrunet** [comment]
This should no longer be needed with https://github.com/IBMa/equal-access/pull/1371 . It manages focus better for the tree grid and manages focus through the scan transition better.
