### ISSUE TITLE
Update the issue presentation in the Checker's HTML report to match the latest Checker #3197

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#947]
### Summary

Make the display of issues in the HTML report match the way they are displayed in the Checker itself.  There are three differences:

* Order of issue count and icon
* Indentation of issues
* Order of display of issues

Current checker:

![Screen Shot 2021-06-08 at 10.30.16 AM.png](https://zenhub.ibm.com/images/5821294ffdfd5b9223bb7e4d/7120a8cd-6f66-4fe1-86b0-411729299c27)

Current HTML report:

![Screen Shot 2021-06-08 at 10.31.06 AM.png](https://zenhub.ibm.com/images/5821294ffdfd5b9223bb7e4d/7d20c1a0-82e8-4493-9536-9e2b0073aadc)

### Justification

Having information in a different order between the report and the checker itself may cause confusion for users moving between the two.

### "Must have" functionality

Use the same order in both the checker and the report.

![image](https://user-images.githubusercontent.com/4451128/172456056-960c5850-7c3a-41f2-a54b-5b068cae6160.png)

**Comment by MHoov** [comment]
Being implemented as part of #936
