### ISSUE TITLE
[Node] A11y Checker command-line reports generator is confusing

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#950]
**Target env:**  npx achecker 
**Browser:** N/A
**URL:** N/A

**:beetle: Issue:**
When we run the npx achecker with a .txt file for scanning urls, the generated repots structure is confusing. 

**Repro:**
![Screen Shot 2020-06-04 at 11 51 00 AM](https://media.github.ibm.com/user/175242/files/cbd11980-a659-11ea-9093-8039b00d521e)
![Screen Shot 2020-06-04 at 11 51 20 AM](https://media.github.ibm.com/user/175242/files/cbd11980-a659-11ea-9417-4d82a2579162)

![image](https://user-images.githubusercontent.com/4451128/172456553-b963cffe-a5d9-40c3-bf5e-dc968dbb1799.png)

**Comment by shunguoy** [comment]
triage: put into the backlog till we get to the packaging work.

**Comment by marcjohlic** [comment]
Triage:  Reviewed - this is something we can look into when we start the Checker package work

**Comment by MHoov** [comment]
@sct-will something for checker packages consideration

**Comment by sct-will** [comment]
In my investigation, I could not reproduce this issue following testing with version [3.1.41](https://www.npmjs.com/package/accessibility-checker/v/3.1.41) of the accessibility checker. Please retest with this version or later, and reopen this issue if the issue persists. 

Here is the contents of the results folder based on the set of input URLs you provided:

<img width="381" alt="cummins" src="https://user-images.githubusercontent.com/78674552/205726201-50b6b21f-c9a4-427b-81b7-35c0bd9b0a3d.png">
