### ISSUE TITLE
Checker: Interaction between multi-scan and changing rule set #3287

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#954]
### Describe what needs to be accomplished
When a user changes the rule set or deployment in the middle of storing scans, they currently get a report that lists only the final rule set/deployment date, and does not indicate that earlier scans were made with different options. This is inaccurate.

### Why does this need to be accomplished
The multi-scan report should accurately reflect the scans that were done.

### Related issues or references
This cropped up when working on #3217, when it became unnecessary to close and reopen dev tools after changing the options. Now users can change the options mid-stream very smoothly.  The question is whether their stored scans should be cleared or the report should be amended to reflect that scans may be done with different rule sets. Clearing stored scans could be annoying if users want to compare their results for different rule sets.

![image](https://user-images.githubusercontent.com/4451128/172457499-e95c727d-63f0-4675-bd5e-5c5b623e9e2f.png)

**Comment by tombrunet** [comment]
Should probably just disable the ability to change rulesets while scan storing is active.

**Comment by tombrunet** [comment]
Can we pop a modal to warn that we'll clear your stored scans if you change archive / guidlines?

**Comment by MHoov** [comment]
READY FOR IMPLEMENTATION

Re: internal [design issue 3287 ](https://github.ibm.com/IBMa/E2E/issues/3287)

Design in this[ Figma file](https://www.figma.com/file/intddqthciXilHQCLWppQ7/a11y-checker?type=design&node-id=535-83455)

![image.png](https://images.zenhubusercontent.com/5ed6cf7a36f485fe5e575397/6a9deb87-a464-4a24-a398-13971580aa9b)

**Comment by drjoho** [comment]
Basically if a user has stored scans put up modal (as designed).
1. if user chooses cancel the rule set is not changed and stored scans remain
2. if user chooses "Change deployment dates" then the stored scans will be deleted and the deployment date changed.

**Comment by drjoho** [comment]
Underlying data i.e., ability to get whether stored scans exist (in Options) and the ability to clear stored scans (in Options) has been done. This was difficult in that Options was outside the extension browser tab structure. 

Next I will put the logic in to put up a modal if stored scans exist. The user will then either cancel (i.e., not change the ruleset deployment date or guidelines) or they will choose change whereby we will delete the stored scans followed by performing the ruleset change.

**Comment by drjoho** [comment]
Done just a bit of cleanup and dev test before handing over to QA.

**Comment by ErickRenteria** [comment]
This needs a little more work 
https://github.com/IBMa/equal-access/issues/1599

**Comment by drjoho** [comment]
If cancel need to set the change in deployment date or guidelines back to the active ones.

**Comment by drjoho** [comment]
@ErickRenteria All works. You thought there was a problem with the numbering of the scan labels, i.e., scan_1, scan_2, etc. However, they were designed to run continuously incrementally due to the fact that the user can delete scans anywhere. I can show you if needed. This is the second or third time we have revisited this issue. The numbers have no meaning. The label is just there if the user wants to name the scan something meaningful. So I am done and the PR is ready.

**Comment by drjoho** [comment]
I left it for you to close if you have any questions let me know.
