### ISSUE TITLE
Add list of features to Checker ReadMe.md

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#955]
Add list of features to Checker ReadMe.md

### Why does this need to be accomplished
Nice list of our checker capabilities that can be used elsewhere

From the original requestor/issue:
### Summary

The Repository should have a features section in the README.md, so that the users can know all the features available.

This is a Documentation request.

### Justification

It is hard to know the exact features provided by the repo, which leads to a disadvantage when comparing with other accessibility solutions available.

### "Must have" functionality

Documentation of the features of the project and sub-projects.

### Related issues or references
See [EA issue #454](https://github.com/IBMa/equal-access/issues/454) 

![image](https://user-images.githubusercontent.com/4451128/172457665-2c40e325-5c47-4b62-a067-08b43e3cf457.png)

**Comment by sct-will** [comment]
This is in progress.

**Comment by sct-will** [comment]
Updated PR here: https://github.com/IBMa/equal-access/pull/1230

**Comment by ErickRenteria** [comment]
Validated
