### ISSUE TITLE
Add a way (waiting / hourglass) to show the user the checker is working if the scan or a visualization takes a long time #3607

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#961]
When the checker runs on long pages or has a large page that we put a visualization on it can take some time where it can appear to the user that the Checker is not reacting to the user request. So, it would be helpful to have some UI / screen reader notification to let the user know that the Checker is working towards the desired result.

![image](https://user-images.githubusercontent.com/4451128/172458978-c2d1b7c5-7506-4aa9-b885-f8cc4d48f1a8.png)

**Comment by aliunwala** [comment]
Triage:
This has been done for the scan as of now. So half this ticket is done. 

We still need to do this for the tabstops visualization.

**Comment by marcjohlic** [comment]
Do we have a good example of Tab Stops taking a long(er) time to load?  I just tried it on Amazon and NYT (two of our bigger tests) and the Tab Stops displayed in less than a second.

Do we still need this issue?

**Comment by tombrunet** [comment]
@drjoho

**Comment by drjoho** [comment]
My sense is the same as Marc as I have not seen the ksm take long enough to merit a waiting / hourglass.
So, I will close this issue.
