### ISSUE TITLE
Create design solutions to surface rules that map to more than 1 requirements in Checker #3774

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#963]
As per https://github.ibm.com/IBMa/E2E/issues/3736 we are going to need some design input on ways to surface to auditors that more than one requirement maps to one issue. I can quickly describe some suggestions to explore, if desired. 

![image](https://user-images.githubusercontent.com/4451128/172459737-df0ece54-8066-44c7-bcc2-64ce5b02d3a3.png)

**Comment by aliunwala** [comment]
Triage: 
Had a long discussion about this during triage. We agreed this was probably not sev 1 but we also really need design to dream up what this might look like to make it less confusing. That said we are also not sure how many users are adversely effected by this (there are users that have noticed the number discrepancy but we are not sure that was a problem for them.)

**Comment by aliunwala** [comment]
This is the same issue as https://github.com/IBMa/equal-access/issues/966

Please look at that one for further info #966 has been closed as a dupe

**Comment by MHoov** [comment]
Belongs on internal board. Reopened original issue
