### ISSUE TITLE
Investigate - filter the results side of the checker based off card pushes on the summary side of the checker #1496

### ISSUE THREAD

**Issue by aliunwala** [IBMa/equal-access#969]
### Describe what needs to be accomplished
Investigate if we can provide a feature to the user to be able to filter the checker side by pushing a card for issue type on the Summery side of the Checker Assessment panel.

![image](https://media.github.ibm.com/user/1065/files/5b5d1100-c831-11ea-98d6-23ea0c79df19)

### Supporting notes and details
* How long do you think this will take to complete?

![image](https://user-images.githubusercontent.com/4451128/172492781-0aacdfff-24b6-4ae1-a6e6-1399b3aa90c0.png)

**Comment by tombrunet** [comment]
See https://react.carbondesignsystem.com/?path=/story/components-tile--selectable

**Comment by MHoov** [comment]
READY FOR IMPLEMENTATION:

Re: internal [design issue 1219](https://github.ibm.com/IBMa/E2E/issues/1219)

**DEV NOTE: Splash screen is not necessary if the user visits the elements panel first**

[Designs in figma.](https://www.figma.com/file/intddqthciXilHQCLWppQ7/a11y-checker?type=design&node-id=534-83201)

Firefox:
![Firefox pop up assessment](https://media.github.ibm.com/user/163626/files/59902722-a131-46dc-8e22-f6b48f5f377a)

Chrome:
![Chrome pop up assessment](https://media.github.ibm.com/user/163626/files/0e297400-4adf-4bfa-87d1-8a45a29b953f)

**Comment by MHoov** [comment]
Being implemented as part of issue #936
