### ISSUE TITLE
[Question]: Help:  the detail info link "learn more" direct to a blank view.

### ISSUE THREAD

**Issue by liupeig** [IBMa/equal-access#970]
### Project

a11y checker

### Description

Help:  the detail info link "learn more" directed to a blank view.
I try to scan our site's page with Firefox 101.0(64) on MacOS 12.4 and get the scan result.
while I check  any one violation record and then click the link 'learn more', it was directed to the blank view .
My checker ver. 3.1.30 with options(rule sets: Latest Deployment,  a11y guideline: IBM Accessibility)
The process likes the below captures. Could anyone give me advice? Thx in advance 
<img width="1401" alt="2" src="https://user-images.githubusercontent.com/107132538/172659338-d04b2c29-16b4-4d99-a5a3-fd9b24cbb415.png">

<img width="1435" alt="1" src="https://user-images.githubusercontent.com/107132538/172659267-874426df-df89-45af-85e1-5f0ae692f5de.png">

**Comment by liupeig** [comment]
@shunguoy Could you please help to take a look?

**Comment by shunguoy** [comment]
@liupeig  I tried a test page, and the help panel was displayed correctly.  Can you please remove and reinstall the checker to try again?  If it happens again, could you send me the page link?  Thanks.

**Comment by liupeig** [comment]
@shunguoy , Thx for your support. Maybe network issue I can't reproduce this issue. I'll close this issue.
