### ISSUE TITLE
[BUG] Accessibility checker hangs and never finishes the scan.

### ISSUE THREAD

**Issue by leftyrivera** [IBMa/equal-access#99]
## What tool(s) are you using?

- [x] `accessibility-checker`

## Detailed description

Node version: v10.15.3
Platform: Win10

I'm trying to use the accessibility-checker in a build using protractor. The checker never ends and at the end I get a timeout error.

I thought I was using the tool the wrong way and then I tried using the browser and I got the same behavior. The screen shots are from Firefox (76.0.1 - 64 bit) but I see the same behavior in Chrome (83.0.4103.61 (Official Build) (64-bit))

## Steps to reproduce the issue

1. Go to https://angular.carbondesignsystem.com/3.28.0/?path=/story/search--basic.
2. Try to scan the page.
3. The scan never ends and there is an error in the browser console.
```
RULE EXCEPTION: Rpt_Aria_MultipleSearchLandmarks /html[1]/body[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[2]/div[1]/div[1]/iframe[1]/html[1]/body[1]/div[3]/storybook-dynamic-app-root[1]/ng-component[1]/ibm-search[1]/div[1] ace</o</e.getAriaLabel@sandbox eval code:16:16738
ace</o</e.findAriaLabelDupes/<@sandbox eval code:16:16825
ace</o</e.findAriaLabelDupes@sandbox eval code:16:16800
run@sandbox eval code:16:185183
ace</u</e.prototype.run@sandbox eval code:16:96176
ace</d</e.prototype.run@sandbox eval code:16:98129
ace</c</e.prototype.check@sandbox eval code:16:94356
62/</<@moz-extension://3a8cd637-4a8b-44af-b0d6-d25968c96d00/tabListeners.js:1:2851
1/o/<@moz-extension://3a8cd637-4a8b-44af-b0d6-d25968c96d00/tabListeners.js:1:1626
o@moz-extension://3a8cd637-4a8b-44af-b0d6-d25968c96d00/tabListeners.js:1:1371
62/<@moz-extension://3a8cd637-4a8b-44af-b0d6-d25968c96d00/tabListeners.js:1:2656
13/addListener/<@moz-extension://3a8cd637-4a8b-44af-b0d6-d25968c96d00/tabListeners.js:1:1806
```

## Additional information
![image](https://user-images.githubusercontent.com/5672847/83263781-1e5b9300-a18d-11ea-9f3e-3cf18c42c9ae.png)

![image](https://user-images.githubusercontent.com/5672847/83263812-2d424580-a18d-11ea-9210-df687a6d9f39.png)

**Comment by tombrunet** [comment]
This is already fixed in the `preview` archive. You can get the preview archive if you click on the bee in the toolbar, and go to the Options. Will try to get this into a regular rule archive soon.

**Comment by tombrunet** [comment]
In the `accessibility-checker` you can define an `achecker.js` config file to specify the `preview` archive also.

**Comment by tombrunet** [comment]
We're due for a June deployment anyway, so will try to have this out as `latest` tonight.

**Comment by tombrunet** [comment]
Deployed as `03June2020` / `latest`
