### ISSUE TITLE
Adjust Rule element_tabbable_visible so it does not trigger if the element top is 0 or left 0

### ISSUE THREAD

**Issue by drjoho** [IBMa/equal-access#993]
For issue number 1 or the orange triangle 1 the rule element_tabbable_visible should not trigger, even though either x or y of the top left corner of the element rectangle is 0. 

![image.png](https://images.zenhubusercontent.com/61081394ffd52d20c363a4cd/9652c901-953c-4e51-a2ac-77b62160c755
)

**Comment by shunguoy** [comment]
#994

**Comment by eirckr** [comment]
I do not see element_tabbable_visible being trigger in the image. @drjoho can you please review: 
<img width="1799" alt="Screen Shot 2022-06-29 at 2 15 01 PM" src="https://user-images.githubusercontent.com/62436670/176517874-46f33e7d-fca2-4d80-bf34-db0600e27cf8.png">

**Comment by eirckr** [comment]
Not fixed: 
<img width="1765" alt="Screen Shot 2022-06-30 at 10 52 41 AM" src="https://user-images.githubusercontent.com/62436670/176722783-b5fb5a6d-f73d-43e3-a7c0-7ed45599cc86.png">

**Comment by shunguoy** [comment]
@eirckr  did you use dev-003 in your test?

**Comment by shunguoy** [comment]
@eirckr  based on your screenshot, you don't have a clean Autoro test page.  Clean up your cache, those tabbable errors will be gone.

**Comment by eirckr** [comment]
Validated
